"""Cybersecurity, advanced and job ready projects. These are engineering
projects: they integrate earlier work, include automated testing and ask the
learner to defend design decisions the way they would in a review."""

from app.seed.lab.builders import project

ADVANCED = [
    project(
        slug="detection-engineering-pipeline",
        title="Detection Engineering Pipeline",
        level="advanced",
        phase="Phase 9, Detection Engineering",
        est_hours=20,
        summary="Treat detections as software: write Sigma rules, test them against labelled data in continuous integration, and measure their quality.",
        build="A repository where every detection is a Sigma rule with metadata, and a pipeline that on each change validates the rule, converts it to a SIEM query, runs it against a labelled set of malicious and benign events, and fails the build if it misses an attack or fires on normal activity. A report tracks coverage by ATT&CK technique.",
        problem="Detection rules written by hand in a SIEM console drift, break silently and nobody can say how good they are. Mature teams manage detections like code, with review, tests and measurement.",
        why="Detection engineering is one of the fastest growing security specialisations. A working pipeline with tests and coverage metrics shows engineering discipline that most candidates cannot demonstrate.",
        skills=["Sigma rule writing", "Detection as code", "Continuous integration", "Test data design", "ATT&CK coverage analysis", "Query translation", "Metrics for detection quality"],
        tools=[
            ("Sigma and pySigma", "A vendor neutral rule format and the library that validates rules and converts them to SIEM queries."),
            ("Python 3 and pytest", "Run the rules against the labelled events and assert the outcomes."),
            ("GitHub Actions", "Runs the validation and tests on every change so a broken rule cannot be merged."),
            ("A labelled event dataset", "Events you generate or take from public attack datasets, each marked malicious or benign."),
            ("MITRE ATT&CK data", "Used to map rules to techniques and compute a coverage report."),
        ],
        deliverable="A GitHub repository with at least ten Sigma rules, labelled test data, a test harness, a CI workflow that passes, a generated coverage report and documentation of the contribution process.",
        requirements=[
            "Write at least ten detection rules in Sigma with title, description, status, level, tags, false positive notes and references.",
            "Validate rule syntax and required metadata automatically.",
            "Convert the rules to the query language of a SIEM you used earlier and keep the output in the repository.",
            "Provide labelled test events and compute true positive and false positive results for each rule.",
            "Fail the pipeline when a rule misses a malicious test event or fires on a benign one.",
            "Generate an ATT&CK coverage report from the rule tags.",
            "Document how someone proposes, reviews and retires a detection.",
        ],
        milestones=[
            ("build", "Design the repository", "Plan the folders for rules, test data, tooling and reports, and a naming convention for rules and tests."),
            ("build", "Write the first five rules", "Cover distinct techniques with complete metadata. Write the benign and malicious test events at the same time."),
            ("build", "Build the validator", "Check that every rule parses and has the required fields. Fail clearly with the file and field that is wrong."),
            ("build", "Build the test harness", "Evaluate rules against the labelled events and report true positives, false positives and misses."),
            ("build", "Write five more rules", "Cover persistence, credential access, discovery and a cloud technique, each with tests that include a near miss."),
            ("build", "Convert rules for the SIEM", "Generate queries and check that at least two run correctly in your lab SIEM."),
            ("build", "Set up the CI workflow", "Run validation and tests on every push and pull request. Protect the main branch so failing changes cannot merge."),
            ("test", "Break a rule on purpose", "Weaken a rule and confirm that the pipeline fails for the right reason. Record the failing run."),
            ("test", "Measure quality", "Report precision and recall on your labelled data and say honestly how small the data set is."),
            ("document", "Generate the coverage report", "Produce a table of ATT&CK techniques covered, by how many rules and how well tested."),
            ("document", "Write the contribution guide", "Explain how to propose a rule, what a reviewer checks, and how to retire a rule that is noisy."),
        ],
        documentation=[
            ("README", "What the pipeline does, how to add a rule and how to run the tests locally."),
            ("Detection standards", "The metadata every rule must include and the quality bar a rule must meet before it is accepted."),
            ("Coverage report", "Techniques covered, number of rules, test status and the gaps."),
            ("Pipeline diagram", "The path from a pull request through validation, tests and conversion to a merged rule."),
            ("Limitations", "The size and bias of the test data and what the pipeline cannot prove."),
        ],
        security_notes=[
            "Use sample or generated events only. Never publish real telemetry from an employer.",
            "Do not include working malware or payloads in test data. Events that describe behaviour are enough.",
            "Pin your dependencies and treat rule files from outside sources as untrusted until reviewed.",
        ],
        interview=[
            ("Why manage detections as code, and what problems did the pipeline solve?", "Review, history, automated tests, repeatable deployment and the failure modes of console edited rules."),
            ("How did you build test data, and how do you know it is representative?", "Malicious and benign sets, near misses, the bias of generated data and how you would improve it."),
            ("What do precision and recall mean for a detection, and which matters more?", "Alert quality versus attacks missed, the cost of each for analysts and the dependence on severity."),
            ("A rule fires thousands of times a day. Describe what you do.", "Find the common benign pattern, tighten the logic or add a justified exclusion, retest and record the change."),
            ("How do you stop a bad change to a rule reaching production?", "Required checks, review, branch protection and staged rollout."),
            ("What does your coverage report not tell a manager?", "Rule count versus real quality, data source gaps, attacker evasion and why 100 percent coverage is a misleading goal."),
        ],
        criteria=[
            "At least ten rules pass validation with full metadata.",
            "My CI pipeline runs on every change, and I have a recorded run that failed on purpose and one that passed.",
            "Each rule has labelled malicious and benign tests and I report precision and recall.",
            "The coverage report is generated from the rules, not typed by hand.",
            "No real telemetry, secrets or malware are in the repository.",
        ],
        readme={
            "overview": "A detection engineering pipeline that validates, tests and measures Sigma rules automatically on every change.",
            "problem": "Detections written ad hoc drift, break without notice and cannot be shown to work, so analysts either miss attacks or drown in noise.",
            "solution": "Rules stored as code, tested against labelled events in continuous integration, converted for a SIEM and tracked in a coverage report.",
            "architecture": "Rule files and labelled events feed a validator and test harness, which run in GitHub Actions. Passing rules are converted to SIEM queries and summarised in a coverage report.",
            "installation": "git clone YOUR_REPOSITORY_URL\ncd detection-pipeline\npython3 -m venv .venv\nsource .venv/bin/activate\npip install -r requirements.txt\npytest",
            "usage": "python tools/validate.py rules/\npython tools/test_rules.py\npython tools/coverage.py > reports/coverage.md",
        },
        hints=[
            "Write a near miss event for each rule, such as the same process started by a normal parent. Near misses expose weak logic faster than anything else.",
            "Keep the harness simple. The value is in the test data and the discipline, not in clever code.",
            "Make the pipeline fail with a message that tells the author which rule and which event caused the failure.",
        ],
        common_mistakes=[
            "Testing only with malicious events, which proves nothing about noise.",
            "Mapping rules to ATT&CK techniques loosely to inflate the coverage report.",
            "Letting CI pass with tests that are skipped or that never assert anything.",
            "Including real malware samples or employer data as test events.",
        ],
        recommended_before=["siem-detection-lab"],
        cv_bullet="Built a detection as code pipeline with ten Sigma rules, labelled test data, GitHub Actions validation and an ATT&CK coverage report, measuring precision and recall for each rule.",
    ),
    project(
        slug="cloud-attack-path-analyzer",
        title="Cloud Attack Path Analyzer",
        level="advanced",
        phase="Phase 8, Cloud Security",
        est_hours=22,
        summary="Model cloud identities and resources as a graph and find the chains of permissions an attacker could use to reach sensitive data.",
        build="A tool that reads identity and resource relationships from a cloud environment (or a realistic exported dataset), builds a graph, and searches it for privilege escalation and data access paths, such as a developer role that can assume an admin role or a compromised instance that can read a sensitive bucket. It ranks the paths and recommends the smallest change that breaks each one.",
        problem="Single misconfigurations are easy to list. Real attacks chain them: a small permission here, a trust relationship there, and suddenly a low privilege identity reaches production data. Teams need to see the paths, not only the individual findings.",
        why="Attack path analysis is how modern cloud security products work, and thinking in graphs is a mark of senior security engineering. A working analyzer shows you understand identity as the new perimeter.",
        skills=["Advanced IAM", "Graph modelling", "Privilege escalation techniques", "Python data structures", "Risk prioritisation", "Remediation design", "Cloud threat modelling"],
        tools=[
            ("Python 3", "Builds the model and runs the analysis."),
            ("networkx", "A graph library with the path finding algorithms the analyzer needs."),
            ("boto3 or exported IAM data", "Reads real relationships from a sandbox account, or from a saved export so the project works without a live account."),
            ("Terraform", "Creates a small sandbox environment with deliberate escalation paths to test against."),
            ("Graphviz or a similar tool", "Draws the paths so a person can understand them quickly."),
        ],
        deliverable="A GitHub repository with the analyzer, a sample environment export, Terraform for a sandbox with planted paths, ranked findings, diagrams of the paths, tests and a README.",
        requirements=[
            "Model identities, roles, policies, trust relationships and resources as nodes and edges.",
            "Implement at least four attack path patterns, such as role assumption chains, permission to modify a policy, compute instance role to storage access, and passing a privileged role to a new resource.",
            "Find paths from a chosen low privilege starting identity to a chosen sensitive target.",
            "Rank paths by length and by the sensitivity of the target, and explain the ranking.",
            "For each path, identify the single change that breaks it with least impact.",
            "Draw each path as a diagram that a non specialist can follow.",
            "Work from a saved export so the analysis can be tested without a cloud account.",
        ],
        milestones=[
            ("build", "Study and list the escalation patterns", "Write down the patterns you will detect and why each one works, from reading provider documentation and public research."),
            ("build", "Design the graph model", "Define node and edge types and what each edge means, for example can assume or can read."),
            ("build", "Build the data loader", "Read identities, policies and trust documents from an export file and from a live sandbox as an option."),
            ("build", "Build the graph", "Turn the loaded data into a graph, resolving policies into allowed actions on specific resources."),
            ("build", "Implement path search", "Find paths from a start identity to a target and implement the four attack patterns as edge rules."),
            ("build", "Rank and recommend", "Score each path and compute which single edge, if removed, breaks the most paths."),
            ("build", "Visualise the paths", "Generate diagrams for the top paths with clear labels."),
            ("test", "Test against planted paths", "Use the Terraform sandbox or a crafted export with known paths. The tool must find all of them and report no path that does not exist."),
            ("test", "Prove the fix works", "Apply the recommended change to the export and show the path disappears."),
            ("document", "Write the threat model and README", "Explain what the tool assumes, what it cannot see and how to read the output."),
            ("document", "Publish the examples", "Add sanitised sample exports and diagrams so a reviewer can see results without any account."),
        ],
        documentation=[
            ("README", "What the analyzer finds, how to run it and how to read a path."),
            ("Pattern catalogue", "Each escalation pattern, how it works, the permissions involved and how to prevent it."),
            ("Graph model", "Node and edge definitions with a small worked example."),
            ("Path diagrams", "Diagrams of the top paths from the sample environment, with the recommended fix highlighted."),
            ("Assumptions and limits", "What the model ignores, such as conditions, boundaries and resource policies, and the effect on accuracy."),
        ],
        security_notes=[
            "Sanitise every export. Account identifiers, role names and resource names from a real organisation must never be published.",
            "Use a read only identity for live analysis and never store credentials in the project.",
            "Describe the patterns for defence. Do not provide step by step abuse guidance against real accounts.",
        ],
        interview=[
            ("Describe one attack path your tool found and how an attacker would use it.", "Starting identity, each permission used in order, the final target and why each step was allowed."),
            ("Why model this as a graph rather than a list of findings?", "Chained risk, path finding, the ability to compute the single best fix and the limits of isolated checks."),
            ("How do you decide which fix to recommend for a path?", "The smallest change that removes the path with the least operational impact, and how you checked other paths were not affected."),
            ("What does your model get wrong or ignore?", "Condition keys, permission boundaries, service control policies and resource policies, and how each could add or remove paths."),
            ("How would you keep this analysis current as the environment changes?", "Scheduled collection, diffing graphs over time and alerting on newly created paths."),
            ("How would you explain the highest risk path to a non technical executive?", "Plain language, the business data at risk, the likelihood and one clear decision to approve."),
        ],
        criteria=[
            "The analyzer finds every path I planted and reports no false paths in my tests.",
            "Every reported path has a recommended fix and I proved a fix removes the path.",
            "Diagrams exist for the top paths and are readable without the code.",
            "The tool runs from a sanitised export with no cloud account.",
            "The repository contains no real account identifiers or credentials.",
        ],
        readme={
            "overview": "A Python analyzer that models cloud identities and permissions as a graph and finds attack paths to sensitive resources.",
            "problem": "Misconfigurations chain together, so listing individual findings hides the routes an attacker would actually take to sensitive data.",
            "solution": "A graph based analysis that finds and ranks privilege escalation and data access paths and recommends the smallest change that breaks each.",
            "architecture": "A loader reads identity and policy data, a builder creates the graph, pattern rules add edges, a path finder searches it, and a reporter ranks results and draws diagrams.",
            "installation": "git clone YOUR_REPOSITORY_URL\ncd cloud-attack-path-analyzer\npython3 -m venv .venv\nsource .venv/bin/activate\npip install -r requirements.txt\npytest",
            "usage": "python analyze.py --export samples/environment.json --start dev-user --target prod-customer-data",
        },
        hints=[
            "Start with a tiny graph of five nodes you can check by hand. If the tool cannot get that right, a large export will only hide the bug.",
            "Keep the pattern rules separate from the graph code so each pattern can be tested and explained on its own.",
            "Write the expected paths in the test before running the analyzer.",
        ],
        common_mistakes=[
            "Treating every allowed action as an attack edge, which floods the output with paths that cannot be used.",
            "Committing a raw export that still contains real account numbers.",
            "Ranking paths only by length so a short, harmless path outranks a longer, serious one.",
            "Recommending broad fixes such as removing all permissions, which would break the business.",
        ],
        recommended_before=["cloud-security-posture-checker"],
        cv_bullet="Built a cloud attack path analyzer that models IAM relationships as a graph, detects privilege escalation chains, ranks them and recommends minimal fixes, verified against planted paths.",
    ),
    project(
        slug="automated-incident-response-pipeline",
        title="Automated Incident Response Pipeline",
        level="advanced",
        phase="Phase 10, Portfolio",
        legacy_title="Build an automated security alert system",
        est_hours=22,
        summary="Receive an alert, enrich it, decide on a response, and act with human approval and a full audit trail, in a safe sandbox.",
        build="A pipeline that receives alerts from a webhook, enriches them with context, classifies them with explainable rules, runs a response playbook such as disabling a test account, isolating a sandbox instance or opening a ticket, requires human approval for any destructive step, and records every action in an audit log. It also keeps a record of every decision for review.",
        problem="Analysts spend most of their time on repetitive steps: look up the address, check the user, gather logs, open a ticket. Automation can do the repetitive part in seconds, but automation that acts without control becomes an incident of its own.",
        why="Security automation is a major part of modern SOC and cloud security roles. The skill that matters is knowing what to automate, where a human must decide and how to make automation safe, and that is exactly what this project teaches.",
        skills=["Webhook and API design", "Playbook design", "Enrichment", "Human in the loop controls", "Audit logging", "Idempotency and error handling", "Safe automation"],
        tools=[
            ("Python and FastAPI", "Receives alerts and runs the pipeline stages."),
            ("A job queue or background tasks", "Processes alerts reliably without blocking the receiver."),
            ("SQLite or PostgreSQL", "Stores alerts, decisions, approvals and the audit log."),
            ("A chat webhook or email in a test workspace", "Sends the human approval request and the notification."),
            ("AWS sandbox or a local mock", "The target of the response actions, so nothing real can be harmed."),
        ],
        deliverable="A GitHub repository with the pipeline, playbooks as code, a sandbox target, an audit log sample, tests including failure cases, an architecture diagram and a README with a safety design section.",
        requirements=[
            "Accept alerts at an authenticated webhook and validate every field.",
            "Enrich alerts with at least two sources of context and record where each fact came from.",
            "Classify alerts with explainable rules and store the reason for the classification.",
            "Implement at least three playbooks, with at least one destructive action that waits for human approval.",
            "Make every action idempotent, so receiving the same alert twice does not repeat a response.",
            "Record every decision, approval and action in an append only audit log.",
            "Include a kill switch that stops all automated actions at once, and test it.",
        ],
        milestones=[
            ("build", "Design the workflow and safety rules", "Draw the pipeline from alert to closure, and write down which steps are automatic, which need approval and which are never automated."),
            ("build", "Build the alert receiver", "Create an authenticated endpoint with strict validation and a queue so slow processing never loses an alert."),
            ("build", "Build enrichment", "Add context lookups and store each fact with its source and time."),
            ("build", "Build classification", "Write explainable rules that choose a playbook and store the reasoning."),
            ("build", "Build the playbooks", "Write playbooks as code, with a safe action, a notification, and a destructive action that waits for approval."),
            ("build", "Build approval and the kill switch", "Send an approval request, accept the decision securely and record it. Add a global switch that disables all actions."),
            ("build", "Build the audit log", "Record every step with time, actor, input and result in a way that is append only."),
            ("test", "Test failure behaviour", "Test duplicate alerts, a failed enrichment source, a timed out approval and an action that errors halfway."),
            ("test", "Run an end to end scenario", "Replay a realistic alert through the whole pipeline in the sandbox and capture the audit log."),
            ("document", "Write the safety design", "Explain every control that stops the automation from doing harm and the failure it protects against."),
            ("document", "Write the README and runbook", "Include an architecture diagram, setup, a sample audit log and what an operator does if the pipeline misbehaves."),
        ],
        documentation=[
            ("README", "What the pipeline does, how to run it in the sandbox and what it will never do automatically."),
            ("Architecture diagram", "Receiver, queue, enrichment, classification, playbooks, approval and audit log."),
            ("Playbook catalogue", "Each playbook with trigger, steps, approvals and rollback."),
            ("Safety design", "Controls for authentication, approval, idempotency, the kill switch and blast radius."),
            ("Sample audit log", "A complete record from one alert, showing every decision and action."),
        ],
        security_notes=[
            "Automation holds powerful credentials. Give it the smallest permissions possible and keep them in a secret store or environment variables, never in the code.",
            "Authenticate the webhook. An open endpoint lets anyone trigger your response actions.",
            "Run destructive playbooks only against the sandbox and keep a human approval on anything that cannot be undone.",
        ],
        interview=[
            ("Which steps did you automate and which did you leave to a human, and why?", "Reversible versus irreversible actions, confidence in the classification and the cost of a wrong automatic action."),
            ("How do you make sure duplicate or replayed alerts do not trigger the response twice?", "Idempotency keys, state checks before acting and recording what has already happened."),
            ("What happens when an enrichment source is down?", "Timeouts, partial results, marking the alert as degraded and never blocking or silently failing."),
            ("How would an attacker try to abuse your pipeline, and how did you defend it?", "Forged alerts, injection through alert fields, approval spoofing and over privileged credentials."),
            ("Why an append only audit log, and what does it let you answer later?", "Accountability, reconstructing decisions, finding bad rules and satisfying reviewers."),
            ("How would you measure whether the automation is actually helping?", "Time to respond, analyst time saved, false action rate and approvals that were rejected."),
        ],
        criteria=[
            "A replayed alert runs through the whole pipeline and the audit log shows every step.",
            "A duplicate alert does not repeat the action.",
            "A destructive action never runs without a recorded approval.",
            "The kill switch stops automated actions and I tested it.",
            "No credentials are in the repository and tests pass on a clean checkout.",
        ],
        readme={
            "overview": "A security incident response pipeline that enriches alerts, chooses a playbook and acts safely with human approval and a full audit trail.",
            "problem": "Responding to alerts involves repetitive steps that slow analysts down, but uncontrolled automation can cause outages and new incidents.",
            "solution": "A pipeline that automates the safe, repetitive work, asks a human before anything destructive and records every decision for review.",
            "architecture": "An authenticated webhook feeds a queue. Workers enrich and classify each alert, select a playbook, request approval where needed, perform actions on a sandbox target and write an audit log.",
            "installation": "git clone YOUR_REPOSITORY_URL\ncd incident-response-pipeline\npython3 -m venv .venv\nsource .venv/bin/activate\npip install -r requirements.txt\ncp .env.example .env\nuvicorn app.main:app --reload",
            "usage": "python scripts/replay_alert.py samples/credential_stuffing.json\nThen view the approval request and the audit log.",
        },
        hints=[
            "Write the list of things the automation must never do first, and build tests that prove it cannot.",
            "Treat every alert field as untrusted input. Alerts are produced by systems that attackers can influence.",
            "Make each playbook step a small function with a dry run mode so you can test it without acting.",
        ],
        common_mistakes=[
            "Giving the automation administrator credentials for convenience.",
            "Automating a destructive action because it is exciting rather than because it is safe.",
            "Having no record of why an action was taken.",
            "Testing only the happy path and never a failed or repeated alert.",
        ],
        recommended_before=["soc-alert-dashboard", "detection-engineering-pipeline"],
        cv_bullet="Built a security incident response pipeline with authenticated alert ingestion, enrichment, explainable classification, approval gated playbooks, idempotent actions and an append only audit log.",
    ),
    project(
        slug="cloud-security-operations-platform",
        title="End to End Cloud Security Operations Platform",
        level="job_ready",
        phase="Phase 10, Portfolio",
        est_hours=40,
        summary="Your flagship project: a small security operations platform that detects, investigates and responds across a cloud environment, documented like a real engineering project.",
        build="A platform that brings your earlier work together. A sandbox cloud environment produces logs, a pipeline ingests them, tested detections raise alerts, a dashboard lets an analyst triage with context, and an approved response runs automatically. It ships with infrastructure as code, a threat model, a runbook, a cost estimate and a recorded demonstration of one realistic incident from first log to closure.",
        problem="Security teams need joined up capability: collection, detection, triage and response working together and owned by someone who understands every part. Employers want to see that you can design the whole system and defend its tradeoffs, not only build one tool.",
        why="This is the project you talk about for most of an interview. It proves you can combine cloud, detection, automation and documentation into one coherent, secure and testable system, which is what a job ready cloud security or security engineering candidate does.",
        skills=["Security architecture", "Infrastructure as code", "Cloud logging", "Detection and response integration", "Threat modelling", "Cost awareness", "Technical communication"],
        tools=[
            ("Terraform", "Builds and destroys the whole platform from code so it is reproducible and cheap."),
            ("AWS sandbox account", "Hosts the monitored environment and the platform, with a billing alert in place."),
            ("CloudTrail and VPC flow logs", "The native sources of truth about who did what in the cloud and what traffic moved."),
            ("Your earlier projects", "The detection pipeline, alert dashboard and response pipeline become components of the platform."),
            ("GitHub Actions", "Tests and validates infrastructure and detections on every change."),
            ("Draw.io or a similar diagram tool", "Produces the architecture and data flow diagrams for the documentation."),
        ],
        deliverable="A public repository with infrastructure as code, integrated components, a threat model, an architecture diagram, a runbook, a cost estimate, test evidence, a recorded incident walkthrough and a README written for a hiring manager.",
        requirements=[
            "Deploy the whole platform from code and destroy it with one command.",
            "Collect at least two native cloud log sources and store them with a documented retention choice.",
            "Run at least eight tested detections, reusing your detection pipeline.",
            "Show alerts in a triage dashboard with enrichment and a recorded decision for each.",
            "Run at least two response playbooks with human approval for destructive steps.",
            "Write a threat model for the platform itself, covering how it could be attacked and what limits the damage.",
            "Provide a runbook, a cost estimate, and a recorded walkthrough of one simulated incident.",
            "Pass automated checks in CI for formatting, tests, secret scanning and infrastructure validation.",
        ],
        milestones=[
            ("build", "Write the design document", "Define goals, scope, the architecture, the data flow and the decisions you are making, before you build anything."),
            ("build", "Deploy the foundation", "Create the monitored environment, logging, storage and access controls with infrastructure as code, using least privilege roles."),
            ("build", "Integrate collection and detection", "Ship logs into the pipeline and run your tested detections against them."),
            ("build", "Integrate triage", "Send alerts to the dashboard with enrichment and make sure analyst decisions are recorded."),
            ("build", "Integrate response", "Connect the approval gated playbooks to the sandbox environment and verify the audit trail covers the whole path."),
            ("build", "Harden the platform", "Apply the threat model: authentication, secrets handling, network limits and logging of the platform itself."),
            ("build", "Add CI checks", "Run tests, linting, secret scanning and infrastructure validation on every change, and protect the main branch."),
            ("test", "Run the incident walkthrough", "Simulate one realistic attack, follow it through detection, triage and response, and record the results with timestamps."),
            ("test", "Test teardown and rebuild", "Destroy and rebuild the platform from code and confirm it works again with no manual steps."),
            ("document", "Write the threat model and runbook", "Document risks, controls, residual risk and what an operator does during an outage or a false alarm."),
            ("document", "Write the cost estimate and lessons", "Estimate monthly cost with the assumptions stated and describe the changes needed for production."),
            ("document", "Record the demonstration", "Produce a short recording or a screenshot sequence that shows one incident from first log to closure."),
        ],
        documentation=[
            ("README for a hiring manager", "What the platform is, why it exists, a short demonstration and links to the deeper documents."),
            ("Design document", "Goals, non goals, architecture, key decisions and the alternatives you rejected."),
            ("Threat model", "Assets, attackers, abuse paths, controls and residual risk for the platform itself."),
            ("Runbook", "Operating the platform, handling alerts, responding to failure and rebuilding it."),
            ("Cost estimate", "Monthly cost with assumptions, what drives it and how it scales."),
            ("Incident walkthrough", "A timeline of one simulated attack with the evidence at each stage."),
            ("Lessons and limitations", "What you would change, what you cut and what would be needed for production."),
        ],
        security_notes=[
            "A security platform is a high value target. Treat its credentials, its logs and its response permissions with more care than the systems it watches.",
            "Set billing alerts, tag every resource and destroy the environment when you are not using it.",
            "Run the simulated attack only inside your own sandbox account, and never publish account identifiers, keys or real data.",
        ],
        interview=[
            ("Walk me through the whole platform from a log being created to an analyst closing the alert.", "Each component in order, what data passes between them and where a failure would hurt most."),
            ("What were the three biggest design decisions, and what did you reject?", "Tradeoffs such as managed versus self hosted components, cost versus coverage and automation versus approval."),
            ("How could someone attack your platform, and what limits the damage?", "Credential theft, forged alerts, poisoned logs and over privileged roles, with the controls and residual risk you documented."),
            ("How much does it cost to run, and what would change at ten times the size?", "Your estimate, the cost drivers such as log volume and retention, and scaling choices."),
            ("What is the weakest part of the platform, and how would you fix it?", "An honest limitation and a concrete plan, which shows judgement and not only skill."),
            ("How did you prove it works?", "Tests, the incident simulation, the teardown and rebuild, and the evidence you can show."),
            ("If you joined our team tomorrow, what would you do with this experience?", "Connect the project to the reality of the role: onboarding a new log source, writing a detection, improving a response."),
        ],
        criteria=[
            "I can destroy and rebuild the whole platform from code without manual steps.",
            "An end to end simulated incident is recorded from first log to closure.",
            "The threat model, runbook and cost estimate are written and the README links to them.",
            "CI passes, including secret scanning, and the repository history contains no credentials.",
            "I can explain every design decision and name the weakest part of my own system.",
        ],
        readme={
            "overview": "A small cloud security operations platform that detects, investigates and responds to incidents in a sandbox environment, built and documented like a real engineering project.",
            "problem": "Security teams need collection, detection, triage and response working together, and the people running them need to understand the whole system.",
            "solution": "A reproducible platform defined as code that ingests cloud logs, runs tested detections, supports analyst triage and performs approved responses with a full audit trail.",
            "architecture": "Cloud logs flow into storage and the detection pipeline. Alerts reach the triage dashboard and the response pipeline, which acts on the sandbox with approvals. Infrastructure as code and CI wrap the whole system.",
            "installation": "git clone YOUR_REPOSITORY_URL\ncd cloud-security-operations-platform\ncp terraform.tfvars.example terraform.tfvars\n(edit the placeholders)\nterraform init\nterraform apply",
            "usage": "Run scripts/simulate_incident.sh to produce a safe test incident, then open the dashboard to triage it. Run terraform destroy when finished.",
        },
        hints=[
            "Write the design document before the code. If you cannot explain the architecture on paper, building it will not fix that.",
            "Integrate one thin vertical slice first, one log to one detection to one alert to one response, and widen it afterwards.",
            "Keep a decisions log as you go. It becomes the best part of your interview answers.",
        ],
        common_mistakes=[
            "Copying components together without understanding how data moves between them.",
            "Leaving the environment running and paying for it.",
            "Documenting only what works and hiding the limitations.",
            "Skipping the threat model for the platform itself.",
        ],
        recommended_before=["detection-engineering-pipeline", "cloud-attack-path-analyzer", "automated-incident-response-pipeline"],
        cv_bullet="Designed and built an end to end cloud security operations platform with infrastructure as code, tested detections, analyst triage and approval gated response, documented with a threat model, runbook and cost analysis.",
    ),
]
