"""Cybersecurity, beginner projects. Each one is a small, finished tool that
teaches one core skill and leaves behind something a stranger can run."""

from app.seed.lab.builders import project

BEGINNER = [
    project(
        slug="network-recon-tool",
        title="Network Reconnaissance Tool",
        level="beginner",
        phase="Phase 2, Networking",
        legacy_title="Build a Python port scanner",
        est_hours=8,
        summary="A Python command line scanner that finds open TCP ports on a host you own and reports what is listening.",
        build="A command line tool that takes a target host and a port range, checks which TCP ports accept a connection, grabs a service banner where one is offered, and writes a clear report to the terminal and to a JSON file.",
        problem="Before anyone can defend a machine they need to know what it exposes. Every open port is a door, and forgotten services on forgotten ports are how many breaches begin. Analysts and administrators check this constantly, and you will do it by hand until you build the tool that does it for you.",
        why="Port scanning is the first move in both attack and defence. Building your own scanner forces you to understand how a TCP connection really starts, which is the knowledge behind firewall rules, alerts about scanning and every network investigation you will do later.",
        skills=["TCP and ports", "Python sockets", "Command line interfaces", "Threading basics", "Reading and writing JSON", "Responsible scanning"],
        tools=[
            ("Python 3", "The language the scanner is written in, using only the standard library so there is nothing to install."),
            ("socket module", "Opens the TCP connections that decide whether a port is open."),
            ("argparse", "Gives the tool a proper command line with help text instead of editing the code for every run."),
            ("concurrent.futures", "Scans many ports at once so a full range finishes in seconds instead of minutes."),
            ("Nmap", "A trusted scanner you run on the same target to compare results and prove your tool is correct."),
        ],
        deliverable="A GitHub repository containing the scanner, a sample JSON report from a scan of your own machine, tests, and a README that explains the tool and the legal limits of scanning.",
        requirements=[
            "Accept a target host and a port range from the command line, with sensible defaults and a help message.",
            "Refuse to run against anything except localhost, a private address range, or a host you explicitly confirm you own.",
            "Report each port as open, closed or filtered, using a connection timeout so filtered ports do not hang the scan.",
            "Scan ports concurrently with a configurable number of workers.",
            "Attempt a short banner grab on open ports and record what the service says, if anything.",
            "Write results to the terminal in a readable table and to a JSON file with a timestamp.",
            "Handle bad input, unreachable hosts and interrupted scans without a stack trace.",
        ],
        milestones=[
            ("build", "Set up the project", "Create the folder, a virtual environment and a main file. Write the argument parser first so the shape of the tool exists before the logic does."),
            ("build", "Check a single port", "Write a function that opens a TCP connection to one port with a timeout and returns open, closed or filtered. Test it against a port you know is open on your own machine."),
            ("build", "Scan a range", "Loop over a range of ports and collect the results. Confirm the answers match what Nmap reports for the same range."),
            ("build", "Add concurrency", "Use a thread pool so many ports are checked at once. Measure the scan time before and after and note the difference."),
            ("build", "Grab banners", "For open ports, read the first bytes the service sends and store them. Handle services that stay silent until you send something."),
            ("build", "Add the safety guard", "Block public addresses unless the user passes an explicit confirmation flag. Explain in the help text why the guard exists."),
            ("build", "Handle errors", "Cover an invalid port range, a hostname that does not resolve, a timeout and Ctrl+C. Each should print a clear message and exit cleanly."),
            ("test", "Write automated tests", "Start a local listener on a random port inside the test, then assert the scanner finds it open and finds a neighbouring port closed."),
            ("test", "Compare with Nmap", "Scan the same range with your tool and with Nmap on a machine you own. Record any difference and explain it."),
            ("document", "Write the README", "Use the README Builder. Include a sample run, the JSON format and a clear section on legal and ethical use."),
            ("document", "Capture evidence", "Save a screenshot of a real scan and the sample JSON report into a docs folder."),
        ],
        documentation=[
            ("README", "What the tool does, how to install and run it, an example scan, and the rule that you only scan systems you own or have written permission to test."),
            ("Sample output", "A saved JSON report and a terminal screenshot from a scan of your own machine, so a reader can see it working without running it."),
            ("Design decisions", "Why threads instead of one port at a time, what timeout you chose and what that trades off between speed and accuracy."),
            ("Test results", "What the tests cover, and the Nmap comparison table showing where your results matched and where they differed."),
        ],
        security_notes=[
            "Only scan machines you own or have written permission to test. Unauthorised scanning can break the law in many countries and will break your reputation.",
            "Do not put real internal addresses or hostnames of any employer or school in your repository or screenshots.",
            "Keep a safe default target of 127.0.0.1 so a beginner cannot scan something by accident.",
        ],
        interview=[
            ("Explain what happens at the network level when your scanner checks a port that is open, closed and filtered.", "The TCP three way handshake, a reset from a closed port, and silence from a firewall that drops packets, and how your timeout turns silence into the filtered state."),
            ("Why does a full connect scan get noticed more easily than a SYN scan, and why did you choose a connect scan?", "A connect scan completes the handshake and appears in application logs, a SYN scan does not complete it but needs raw sockets and privileges, and a connect scan needs neither."),
            ("How did you decide the number of worker threads and the timeout?", "Measured results, the cost of too many threads, and how a short timeout trades accuracy for speed on slow networks."),
            ("A scan reports port 8080 filtered but the service is running. What could explain it?", "A firewall rule, a timeout that was too short, rate limiting, or the service binding only to another interface."),
            ("How would a defender detect your scanner, and what would they see in their logs?", "Many connection attempts from one source to many ports in a short time, and the pattern a detection rule would look for."),
            ("What legal and ethical rules did you build into the tool, and why?", "Authorisation, the scope guard, and why a safe default matters when the tool might be used by a beginner."),
        ],
        criteria=[
            "I ran the scanner against a machine I own and saved the output.",
            "My results match Nmap for the same port range, or I can explain every difference.",
            "The tool refuses to scan an address I did not confirm.",
            "Automated tests run and pass on a clean checkout.",
            "The README explains how to run it and states the legal limits of scanning.",
        ],
        readme={
            "overview": "A Python command line port scanner that reports open TCP ports and service banners and saves results as JSON.",
            "problem": "You cannot secure what you cannot see. Administrators and analysts need a fast way to learn which ports a machine exposes.",
            "solution": "A standard library scanner that checks ports concurrently, grabs banners, and writes a readable report, with a guard that blocks scanning targets you have not confirmed.",
            "architecture": "Argument parser, then a target safety check, then a thread pool that calls a single port checker, then a report writer for the terminal and JSON.",
            "installation": "git clone YOUR_REPOSITORY_URL\ncd network-recon-tool\npython3 -m venv .venv\nsource .venv/bin/activate\npython -m pytest",
            "usage": "python scanner.py 127.0.0.1 --ports 1-1024 --workers 100 --output report.json",
        },
        hints=[
            "Use connect_ex instead of connect so a refused connection returns a number instead of raising an exception.",
            "Test against your own machine first. Start a quick listener with python3 -m http.server 8000 so you have a known open port.",
            "Put the port checking in one small function with no printing, so tests can call it directly.",
        ],
        common_mistakes=[
            "Scanning a host you do not own while testing. Stick to localhost and machines in your own network.",
            "Forgetting a timeout, which makes the scan hang forever on filtered ports.",
            "Printing results from inside the worker threads, which interleaves output and cannot be tested.",
            "Writing the report only to the screen, so there is no evidence to show anyone later.",
        ],
        cv_bullet="Built a concurrent Python TCP port scanner with banner grabbing and JSON reporting, validated against Nmap results and tested with automated unit tests.",
    ),
    project(
        slug="password-security-analyzer",
        title="Password Security Analyzer",
        level="beginner",
        phase="Phase 4, Python",
        legacy_title="Build a password-strength checker",
        est_hours=6,
        summary="A tool that scores password strength with real rules, checks a local wordlist, and never stores or transmits the passwords it sees.",
        build="A Python tool that evaluates a password using length, character variety, common patterns and a list of known leaked passwords, then explains in plain words what is weak and how to fix it.",
        problem="Weak and reused passwords are still one of the most common ways accounts are taken over. Many strength meters only count symbols, which tells users very little. A useful analyzer explains why a password is weak and respects the fact that the password itself is sensitive.",
        why="Credential security is central to identity and access work, and handling secrets safely is a habit every security engineer needs. This project teaches both the analysis and the discipline of never leaking the thing you analyse.",
        skills=["Python functions and modules", "Regular expressions", "Entropy and password strength", "Hashing", "Safe handling of secrets", "Unit testing"],
        tools=[
            ("Python 3", "The language for the analyzer and its tests."),
            ("re module", "Detects patterns such as repeated characters, keyboard runs and years."),
            ("hashlib", "Hashes passwords with SHA 256 so the list of known bad passwords can be checked without keeping plain text."),
            ("pytest", "Lets you prove each rule works with small repeatable tests."),
            ("A public common password list", "A downloaded list of the most common leaked passwords, used offline for the check. Record where it came from in the README."),
        ],
        deliverable="A GitHub repository with the analyzer, a command line interface, a test suite, and a README that explains how the score is calculated and why passwords are never stored.",
        requirements=[
            "Score a password from 0 to 100 using documented rules, not guesses.",
            "Estimate entropy from the length and the size of the character set used.",
            "Check the password against a local list of common passwords, comparing hashes where practical.",
            "Detect and penalise repeated characters, keyboard sequences, years and the user's own name or email.",
            "Return specific feedback, for example 'too short' or 'appears in a common password list', not just a number.",
            "Read the password with a hidden prompt, never as a command line argument, and never write it to a log or file.",
            "Provide a function other code can import, plus the command line wrapper.",
        ],
        milestones=[
            ("build", "Set up the project", "Create the folder, a virtual environment, a package folder and a tests folder. Decide the scoring rules on paper before coding them."),
            ("build", "Implement length and character rules", "Count length and the character classes used and turn them into a base score."),
            ("build", "Calculate entropy", "Estimate bits of entropy from length and character set size. Explain in a comment why the number is only an estimate."),
            ("build", "Add the common password check", "Load the wordlist once, then check candidates quickly. Compare hashes so the list can be stored and checked without printing it."),
            ("build", "Detect weak patterns", "Add checks for repeats, sequences such as qwerty or 12345, years and personal information the user supplies."),
            ("build", "Write helpful feedback", "Return a list of human readable reasons and one suggestion each. A beginner should understand every line."),
            ("build", "Build the command line", "Use getpass so the password is hidden and never appears in shell history or the process list."),
            ("test", "Write unit tests", "Cover strong, weak, empty and very long passwords, plus each pattern rule. Aim for tests that fail if you break a rule."),
            ("test", "Check for leaks", "Run the tool and search your logs, history and output files to confirm the password never appears anywhere."),
            ("document", "Write the README", "Use the README Builder. Explain the scoring model, its limits and the privacy design."),
            ("document", "Capture evidence", "Save a screenshot of the tool rating a weak and a strong password, using throwaway examples."),
        ],
        documentation=[
            ("README", "How the score is calculated, how to run the tool and why a high score does not guarantee safety."),
            ("Scoring model", "A short table of each rule, how many points it gives or removes and the reason for the number."),
            ("Privacy design", "A paragraph explaining that passwords are read with a hidden prompt and never stored, logged or sent anywhere."),
            ("Test results", "A summary of the tests, listing the rules covered and any known weaknesses in the model."),
        ],
        security_notes=[
            "Never put a real password of your own in a test, screenshot or example. Use made up examples.",
            "Do not send passwords to any online service to check them. Keep the check local.",
            "State clearly in the README that the score is an estimate and that long, unique passphrases and a password manager beat any rule set.",
        ],
        interview=[
            ("How do you calculate entropy for a password, and what are the limits of that number?", "Length and character set size, why a random password and a predictable one of the same length score the same, and why entropy alone misleads."),
            ("Why should the password never be passed as a command line argument?", "Shell history, process lists visible to other users, and logs that capture the command."),
            ("How did you check against the common password list without storing plain passwords?", "Hashing, comparison of digests, and the point that hashing a small known list is not secure storage."),
            ("Why is a rule that requires one symbol and one number often a bad rule?", "Users satisfy it predictably, such as Password1!, and length and unpredictability matter more than composition."),
            ("How would attackers crack a password that passes your checks?", "Dictionary and rule based guessing, credential stuffing from other leaks and the role of slow hashing on the defender side."),
            ("What would you change to use this inside a real sign up form?", "Run it server side or in the browser, add rate limiting, integrate a breached password service and avoid logging input."),
        ],
        criteria=[
            "The analyzer gives different, sensible scores for a very weak, an average and a strong password.",
            "A password from the common list is always flagged, whatever else it contains.",
            "I confirmed the password never appears in any log, file or shell history.",
            "Automated tests run and pass on a clean checkout.",
            "The README explains the scoring model and its limits.",
        ],
        readme={
            "overview": "A Python tool that rates password strength with explained rules and checks against a list of known bad passwords, without ever storing the password.",
            "problem": "Weak and reused passwords cause account takeovers, and simple strength meters give users little useful guidance.",
            "solution": "An analyzer that combines entropy, pattern detection and a common password check, and explains each weakness in plain language.",
            "architecture": "A scoring library with one function per rule, a feedback builder, and a thin command line wrapper that reads input through a hidden prompt.",
            "installation": "git clone YOUR_REPOSITORY_URL\ncd password-security-analyzer\npython3 -m venv .venv\nsource .venv/bin/activate\npip install -r requirements.txt\npython -m pytest",
            "usage": "python analyze.py\n(you will be asked for a password with hidden input)",
        },
        hints=[
            "Write the scoring rules as separate small functions that each return points and a reason. It makes both the tests and the feedback easy.",
            "Use getpass.getpass for input, and make the library function take a string so tests can call it directly.",
            "Load the common password list into a set once. Checking a set is far faster than scanning a list.",
        ],
        common_mistakes=[
            "Testing with a real password of your own and then committing the screenshot.",
            "Printing the password in a debug message and forgetting to remove it.",
            "Treating the score as proof of safety instead of an estimate.",
            "Rewarding complexity rules that are easy to game, such as one symbol at the end.",
        ],
        cv_bullet="Built a Python password analyzer that estimates entropy, detects weak patterns and checks a local breached password list, with privacy by design and a unit test suite.",
    ),
    project(
        slug="network-traffic-investigation",
        title="Network Traffic Investigation",
        level="beginner",
        phase="Phase 6, SOC Fundamentals",
        legacy_title="Analyze network traffic",
        est_hours=8,
        summary="Investigate a packet capture of a suspicious incident, write the timeline and findings, and automate the first pass with a Python script.",
        build="A written investigation of a public sample packet capture, covering what happened and which hosts were involved, with a timeline and indicators of compromise, plus a small Python script that extracts the key facts from the capture automatically.",
        problem="When an alert fires, an analyst often has a packet capture and a question: was this machine compromised, and what did it talk to? Reading raw traffic is slow, so analysts learn to find the signal quickly and explain it clearly to people who are not network experts.",
        why="Packet analysis and clear incident write ups are core SOC skills. A hiring manager reading your report can see how you think, which matters more than any tool name on a CV.",
        skills=["Packet analysis", "Reading protocols such as DNS, HTTP and TCP", "Indicators of compromise", "Timeline building", "Incident writing", "Python scripting for analysis"],
        tools=[
            ("Wireshark", "The standard tool for opening a capture, following streams and reading protocols packet by packet."),
            ("tshark", "The command line version of Wireshark, used to extract fields into text that a script can process."),
            ("Python 3", "Automates the first pass so the same questions can be answered on any capture."),
            ("A public sample capture", "Exercises from malware traffic analysis sites use captures that are published for training. Cite the source in your report."),
        ],
        deliverable="A GitHub repository with an investigation report in Markdown, the extraction script, the extracted data, and screenshots, all without the raw capture if its licence does not allow redistribution.",
        requirements=[
            "Use a public training capture and cite where it came from.",
            "Identify the internal hosts, the external hosts and the protocols seen.",
            "Build a timeline of the key events with timestamps.",
            "List indicators of compromise such as addresses, domains and file names, each with the evidence that points to it.",
            "Separate what the evidence proves from what you only suspect.",
            "Write a script that extracts DNS queries, HTTP requests and top talkers from the capture into a summary.",
            "State a clear conclusion and recommended response actions.",
        ],
        milestones=[
            ("build", "Choose and read the exercise", "Pick a published training capture with a short scenario. Read the scenario and write down the questions you want the capture to answer."),
            ("build", "Get an overview", "Use the capture statistics to find the busiest hosts, the protocols and the time range. Note anything unusual before diving in."),
            ("build", "Investigate DNS and HTTP", "Look at the domain lookups and web requests. Follow streams of interest and note what was requested, from whom and when."),
            ("build", "Identify the suspicious behaviour", "Decide which hosts and connections look malicious or compromised, and gather the specific packets that support each claim."),
            ("build", "Build the timeline", "Order the key events by time, each with the evidence and the host involved."),
            ("build", "Automate the first pass", "Use tshark to export fields and a Python script to produce a summary of top talkers, DNS queries and HTTP requests."),
            ("test", "Validate the script", "Run the script against the capture and check its output against what you found by hand. Fix any mismatch."),
            ("test", "Challenge your conclusions", "For each indicator, ask what innocent explanation could exist and note why you reject it."),
            ("document", "Write the investigation report", "Include summary, scope, timeline, indicators, evidence, conclusion and recommended actions, written for a manager."),
            ("document", "Write the README and capture evidence", "Explain how to reproduce your work with the same capture, and add screenshots of the key packets."),
        ],
        documentation=[
            ("Investigation report", "A short professional report with an executive summary, a timeline, indicators of compromise with evidence, a conclusion and recommended actions."),
            ("Method", "The steps and filters you used, so another analyst could repeat the investigation and reach the same result."),
            ("Screenshots", "Annotated screenshots of the packets that prove each finding."),
            ("Limitations", "What the capture could not tell you and what additional logs you would ask for."),
        ],
        security_notes=[
            "Packet captures of real malware may contain live malicious files. Analyse them in a virtual machine or only read the traffic, and never run extracted files.",
            "Do not publish a capture that contains real personal data. Use public training material and respect its licence.",
            "Defang indicators in your report, for example write example[.]com, so nobody clicks a malicious address by accident.",
        ],
        interview=[
            ("Walk me through how you decided which host in the capture was compromised.", "The evidence trail from unusual outbound traffic to a specific host, and how you ruled out other hosts."),
            ("What do the DNS queries in this capture tell you that the HTTP traffic does not?", "Domains contacted before connections, possible command and control, and traffic that never reached a web request."),
            ("How do you tell malicious beaconing from normal background traffic?", "Regular timing, small repeated requests, unusual destinations and user agents."),
            ("What is an indicator of compromise, and how did you decide which to include?", "Evidence backed artefacts others can search for, and why a weak indicator causes false positives."),
            ("What would you recommend the organisation do next, in order?", "Contain, preserve evidence, investigate scope, eradicate and recover, and the reason for the order."),
            ("What could this capture not tell you, and what would you ask for next?", "Endpoint logs, firewall logs, proxy logs, and the limits of network only visibility such as encrypted traffic."),
        ],
        criteria=[
            "My report names the compromised host and backs the claim with specific packets.",
            "My timeline is ordered and every entry has evidence.",
            "My script reproduces the main facts I found by hand.",
            "I separated proven findings from suspicions.",
            "Indicators are defanged and I did not publish anything I should not.",
        ],
        readme={
            "overview": "A packet capture investigation with a full incident report and a Python script that automates the first pass of analysis.",
            "problem": "Analysts need to turn a raw capture into a clear answer about what happened, who was involved and what to do next.",
            "solution": "A structured investigation using Wireshark and tshark, a timeline with evidence for every claim, and a script that extracts the key facts automatically.",
            "architecture": "A capture file is read by tshark, exported to fields, summarised by a Python script, then interpreted by hand into the investigation report.",
            "installation": "Install Wireshark and tshark, then:\ngit clone YOUR_REPOSITORY_URL\ncd network-traffic-investigation\npython3 -m venv .venv\nsource .venv/bin/activate",
            "usage": "python summarize.py path/to/capture.pcap --output summary.json",
        },
        hints=[
            "Start from statistics, not packets. Conversations and protocol hierarchy show you where to look.",
            "Write each claim as a sentence followed by the filter or packet number that proves it.",
            "Use tshark with the fields option to export clean columns, then let Python count and group them.",
        ],
        common_mistakes=[
            "Calling something malicious because it looks odd, with no packet to support it.",
            "Opening a file extracted from a malware capture on your real machine.",
            "Writing a report that lists tools used but never states a conclusion.",
            "Publishing live malicious domains as clickable links.",
        ],
        cv_bullet="Investigated a malware packet capture with Wireshark and tshark, produced an incident timeline with indicators of compromise, and automated triage with a Python extraction script.",
    ),
    project(
        slug="security-log-analyzer",
        title="Security Log Analyzer",
        level="beginner",
        phase="Phase 7, SIEM",
        legacy_title="Build a basic log analyzer",
        est_hours=9,
        summary="A Python tool that parses authentication and web server logs, finds suspicious patterns such as brute force attempts, and produces a report.",
        build="A command line tool that reads Linux authentication logs and web server access logs, parses them into structured events, detects failed login bursts, suspicious paths and unusual sources, and writes a report of the findings with the evidence lines.",
        problem="Logs hold the story of what happened on a system, but they are huge and messy. A security team cannot read them by eye, so they build parsers and rules that turn lines of text into answers such as who failed to log in a hundred times.",
        why="Everything in a SIEM starts with parsing and detection logic. If you can write a parser and a few honest rules yourself, you understand what the expensive tools are doing and you can write better detections later.",
        skills=["Log parsing", "Regular expressions", "Detection rules and thresholds", "Time windows", "Reporting", "Unit testing with sample data"],
        tools=[
            ("Python 3", "Parses the logs and applies the detection rules."),
            ("re module", "Extracts timestamps, users, addresses and request details from raw log lines."),
            ("collections and datetime", "Count events per source and group them into time windows."),
            ("Sample log files", "Generated or published sample authentication and access logs, with any real addresses removed."),
            ("pytest", "Proves that each rule fires on the right lines and stays quiet on normal ones."),
        ],
        deliverable="A GitHub repository with the parser, the detection rules, sample logs, a generated report, tests and a README explaining each rule and its false positive risks.",
        requirements=[
            "Parse at least two log formats, such as Linux auth.log and a web server access log, into structured events.",
            "Detect repeated failed logins from one source inside a time window, with a configurable threshold.",
            "Detect a successful login that follows many failures from the same source.",
            "Detect suspicious web requests such as probes for admin pages or path traversal strings.",
            "Output findings with severity, the rule that fired and the original log lines as evidence.",
            "Handle malformed lines without crashing and report how many were skipped.",
            "Provide sample logs that trigger each rule and some that must not.",
        ],
        milestones=[
            ("build", "Set up the project and sample data", "Create the structure and generate or collect sample logs. Remove or replace any real addresses and usernames."),
            ("build", "Parse authentication logs", "Write a parser that turns each line into an event with time, user, source address and outcome. Count the lines that fail to parse."),
            ("build", "Parse web access logs", "Write a second parser for request lines with address, method, path and status code."),
            ("build", "Write the brute force rule", "Group failures by source address inside a sliding time window and flag sources over the threshold."),
            ("build", "Write the success after failures rule", "Flag a successful login from a source that just failed many times, which is a stronger signal than failures alone."),
            ("build", "Write the web probe rule", "Flag requests for known sensitive paths and traversal patterns, and explain how each could also be legitimate."),
            ("build", "Produce the report", "Output findings as readable text and JSON, each with severity, rule name and evidence lines."),
            ("test", "Test every rule", "Write tests with lines that must trigger and lines that must not. Include an edge case at the exact threshold."),
            ("test", "Measure false positives", "Run against a clean log and record what fires. Tune the thresholds and write down why you chose them."),
            ("document", "Write the rule documentation", "For each rule write what it detects, why it matters, how it can false alarm and how to tune it."),
            ("document", "Write the README and capture evidence", "Use the README Builder and add a sample report and screenshot."),
        ],
        documentation=[
            ("README", "What the tool detects, how to run it on a log file and how to read the report."),
            ("Rule catalogue", "One short entry per rule: purpose, logic, threshold, false positive risks and tuning advice."),
            ("Sample report", "A generated report from the sample logs showing findings with evidence."),
            ("Test results", "What the tests prove and what the false positive measurement showed."),
        ],
        security_notes=[
            "Log files often contain real usernames, addresses and tokens. Anonymise every sample before it goes into a public repository.",
            "Do not commit logs from a real system you do not own.",
            "Explain in the README that detection thresholds are judgement calls, not facts, and need tuning for each environment.",
        ],
        interview=[
            ("Explain how your brute force rule works and how you picked the threshold and window.", "Counting failures per source in a time window, the tradeoff between catching slow attacks and flagging forgetful users, and how you tested it."),
            ("Why is a success after many failures more serious than the failures alone?", "It suggests the guess worked, so an account may now be compromised, which changes the response from monitor to act."),
            ("What false positives would your rules produce in a real office?", "Shared addresses behind one NAT, users who mistype, monitoring tools that probe paths, and how you would reduce them."),
            ("How would an attacker evade your brute force rule?", "Spreading attempts over many sources or a long period, and what other signals would catch that."),
            ("How does what you built relate to what a SIEM does?", "Ingestion, parsing into fields, correlation and alerting, and what a SIEM adds such as scale and search."),
            ("A log line fails to parse. What should the tool do, and why?", "Skip and count it rather than crash or silently drop it, because unparsed lines can hide attacks."),
        ],
        criteria=[
            "Every rule fires on my sample attack lines and stays quiet on normal lines.",
            "The tool never crashes on a malformed line and reports how many it skipped.",
            "Each finding includes the original log lines as evidence.",
            "I documented the false positive risk of every rule.",
            "Sample data contains no real personal data and tests pass on a clean checkout.",
        ],
        readme={
            "overview": "A Python log analyzer that parses authentication and web logs and detects brute force attempts, successful logins after failures and suspicious web requests.",
            "problem": "Logs are too large to read by eye, so security teams need parsers and rules that surface the few lines that matter.",
            "solution": "Structured parsing, a small set of explainable detection rules with configurable thresholds, and a report that includes the evidence lines.",
            "architecture": "Parsers turn log lines into events, a rule engine evaluates events over time windows, and a reporter writes text and JSON findings.",
            "installation": "git clone YOUR_REPOSITORY_URL\ncd security-log-analyzer\npython3 -m venv .venv\nsource .venv/bin/activate\npip install -r requirements.txt\npython -m pytest",
            "usage": "python analyze.py samples/auth.log --format auth --threshold 5 --window 300",
        },
        hints=[
            "Parse first, detect second. Rules that work on structured events are far easier to test than rules that work on raw text.",
            "Keep a sliding window as a sorted list of timestamps per source and drop entries that are too old.",
            "Write the failing sample line before you write the rule that should catch it.",
        ],
        common_mistakes=[
            "Using only real logs from a live system and publishing them with real addresses inside.",
            "Hard coding thresholds with no explanation of why they were chosen.",
            "Counting failures across all time instead of inside a window.",
            "Dropping malformed lines silently so a gap in the data goes unnoticed.",
        ],
        cv_bullet="Developed a Python log analyzer that parses authentication and web logs and detects brute force, success after failure and web probing patterns, with tuned thresholds and a tested rule set.",
    ),
]
