"""Cybersecurity, intermediate projects. These combine several skills, work on
realistic data and ask for design decisions rather than following steps."""

from app.seed.lab.builders import project

INTERMEDIATE = [
    project(
        slug="web-application-security-assessment",
        title="Web Application Security Assessment",
        level="intermediate",
        phase="Phase 5, Security Fundamentals",
        est_hours=14,
        summary="Assess a deliberately vulnerable web application you run yourself, document each finding with evidence and write remediation advice.",
        build="A professional style security assessment of a training web application running on your own machine. You test for common vulnerability classes, prove each finding with evidence, rate its risk, and write the report a client would receive, including how each issue should be fixed.",
        problem="Organisations hire testers and analysts to find weaknesses before attackers do, and the value is not in finding a bug but in explaining it clearly: what it is, how it was proven, how serious it is and exactly how to fix it.",
        why="Web applications are the most exposed part of most companies. Knowing the OWASP Top 10 in practice, and being able to write a clear finding, is useful for security analyst, penetration tester, application security and cloud security roles alike.",
        skills=["OWASP Top 10", "HTTP and web requests", "Intercepting proxies", "Risk rating", "Vulnerability reporting", "Remediation advice", "Safe testing scope"],
        tools=[
            ("OWASP Juice Shop", "A training web application built to be broken legally. You run it in a container on your own machine."),
            ("Docker", "Runs the training application in an isolated container that you can reset at any time."),
            ("Burp Suite Community or OWASP ZAP", "An intercepting proxy that lets you see and change the requests your browser sends."),
            ("Browser developer tools", "Show requests, responses, cookies and storage without extra software."),
            ("A report template", "A consistent finding format with title, severity, evidence, impact and fix."),
        ],
        deliverable="A GitHub repository with an assessment report, evidence screenshots, a finding register and a short remediation plan, without any exploit that works against real systems.",
        requirements=[
            "Test only an application you run yourself and state the scope at the top of the report.",
            "Find and document at least six distinct issues across at least four OWASP Top 10 categories.",
            "Prove each finding with a request and response or a screenshot, and record the steps to reproduce.",
            "Rate each finding with a consistent method, such as likelihood and impact, and justify the rating.",
            "Write a specific remediation for each finding, with a code level or configuration level fix.",
            "Write an executive summary for a non technical reader and a technical section for developers.",
            "Include a limitations section stating what you did not test.",
        ],
        milestones=[
            ("build", "Set up the lab", "Run the training application in a container on your own machine and confirm that the proxy sees your browser traffic. Write the scope statement."),
            ("build", "Map the application", "Browse every feature, record the pages, forms, login flow and API calls. A map of the attack surface comes before any testing."),
            ("build", "Test authentication and sessions", "Examine login, password reset, cookies and session handling. Record what you find with evidence."),
            ("build", "Test input handling", "Test search boxes and forms for injection and script injection issues, using the training application's own challenges."),
            ("build", "Test access control", "Check whether one user can reach another user's data by changing identifiers in requests."),
            ("build", "Test configuration and exposure", "Look for exposed files, verbose error messages, missing security headers and outdated components."),
            ("build", "Rate every finding", "Apply your rating method to each issue and record the reasoning."),
            ("test", "Reproduce each finding from scratch", "Reset the application and follow your own steps exactly. A finding that you cannot reproduce is not a finding."),
            ("test", "Verify the fixes you recommend", "For at least two findings, describe or demonstrate how the fix removes the problem, for example a parameterised query."),
            ("document", "Write the report", "Executive summary, scope, method, finding register, detailed findings, remediation plan and limitations."),
            ("document", "Prepare the repository", "Add the report as Markdown or PDF, evidence in a docs folder and a README that explains the scope and legal boundaries."),
        ],
        documentation=[
            ("Assessment report", "The main deliverable. Executive summary, scope, method, risk rating approach, detailed findings and a prioritised fix list."),
            ("Finding register", "A table with identifier, title, category, severity, status and the location of the evidence."),
            ("Evidence", "Screenshots or request and response pairs for each finding, with any secrets and personal data removed."),
            ("Remediation plan", "The order in which a development team should fix the issues, with the reason for the order."),
        ],
        security_notes=[
            "Only test applications you own or are explicitly authorised to test. Training applications exist so you never need to touch a real site.",
            "Do not publish working exploits against real, current software. Document the weakness and the fix instead.",
            "Run training applications on a local only network and never expose them to the internet, because they are intentionally vulnerable.",
        ],
        interview=[
            ("Pick one finding and walk me through how you found it, proved it and rated it.", "Discovery steps, the evidence, the reasoning behind likelihood and impact, and what made it more or less severe."),
            ("Explain SQL injection and how to prevent it properly.", "Untrusted input changing the query structure, and parameterised queries as the fix rather than blacklists or escaping."),
            ("What is broken access control and why is it so common?", "Authorisation checked in the interface but not on the server, insecure direct object references and how to test for them."),
            ("How is cross site scripting different from injection on the server, and how do you defend against it?", "Script running in a victim's browser, output encoding, content security policy and cookie flags."),
            ("How did you decide the severity of each finding?", "A consistent method, exploitability, impact and exposure, and why the same bug can have different severity in different systems."),
            ("A developer says a finding is not exploitable in practice. How do you respond?", "Reproduction steps, a clear demonstration, honest acknowledgement of constraints and a proportionate rating."),
        ],
        criteria=[
            "I documented at least six findings from at least four OWASP categories.",
            "Every finding has steps to reproduce and evidence, and I reproduced each from a clean reset.",
            "Every finding has a specific, correct remediation.",
            "The report has a scope statement and a limitations section.",
            "No real secrets, personal data or working exploits against real software are in the repository.",
        ],
        readme={
            "overview": "A full security assessment of a deliberately vulnerable web application, with evidence, risk ratings and remediation guidance.",
            "problem": "Web applications are heavily targeted, and teams need findings that are proven, rated consistently and explained in a way developers can act on.",
            "solution": "A methodical assessment of a training application covering authentication, input handling, access control and configuration, written up as a professional report.",
            "architecture": "A local container running the training application, an intercepting proxy between the browser and the application, and an evidence folder that feeds the report.",
            "installation": "docker run -p 127.0.0.1:3000:3000 bkimminich/juice-shop\n(open http://127.0.0.1:3000 in your browser)",
            "usage": "Read report/assessment.md for the findings. Evidence for each finding is in docs/evidence.",
        },
        hints=[
            "Bind the training application to 127.0.0.1 only, so nobody else on your network can reach it.",
            "Record the request and response as you go. It is much harder to reconstruct evidence afterwards.",
            "Write the remediation while the finding is fresh, and make it specific enough that a developer could implement it today.",
        ],
        common_mistakes=[
            "Listing tool output as findings without proving or explaining anything.",
            "Rating everything as critical, which makes the report impossible to prioritise.",
            "Writing generic advice such as validate input instead of naming the actual fix.",
            "Exposing the vulnerable application to the internet by publishing its port.",
        ],
        recommended_before=["network-recon-tool", "password-security-analyzer"],
        cv_bullet="Performed a structured web application security assessment against OWASP Juice Shop, documenting reproducible findings across OWASP Top 10 categories with risk ratings and developer focused remediation.",
    ),
    project(
        slug="siem-detection-lab",
        title="SIEM Detection Lab",
        level="intermediate",
        phase="Phase 7, SIEM",
        est_hours=16,
        summary="Build a small SIEM, ingest logs from real sources, write detection rules, and prove they fire by running safe attack simulations.",
        build="A working lab where a Linux host and a Windows style log source send events into a SIEM, you build searches and dashboards, write at least six detections mapped to MITRE ATT&CK, and prove each one by running a safe simulation of the behaviour.",
        problem="A SIEM with no good detections is an expensive log store. Analysts are valued for knowing which behaviours matter, how to express them as searches and how to prove that an alert fires when it should.",
        why="SIEM work is at the centre of SOC analyst and detection engineer roles. A lab that shows ingestion, detections and proof of testing is the clearest evidence you can offer that you can do the job.",
        skills=["Log ingestion", "SIEM searching", "Detection logic", "MITRE ATT&CK mapping", "Dashboards", "Atomic testing", "False positive tuning"],
        tools=[
            ("Elastic Stack or Wazuh", "A free SIEM you run yourself, which collects, stores and searches logs."),
            ("Docker or a virtual machine", "Hosts the SIEM and the log sources on your own machine."),
            ("Sysmon or auditd", "Generate rich endpoint events on Windows or Linux that detections can use."),
            ("Atomic Red Team", "Runs small, documented, safe simulations of attacker techniques so you can test detections."),
            ("MITRE ATT&CK", "The shared vocabulary for naming the technique each detection covers."),
        ],
        deliverable="A GitHub repository with the lab setup instructions, the detection rules as code, a detection catalogue mapped to ATT&CK, test evidence for each rule, dashboard exports and a README.",
        requirements=[
            "Ingest logs from at least two different sources into the SIEM and confirm fields are parsed.",
            "Write at least six detection rules, each mapped to an ATT&CK technique.",
            "Store every rule as a file in the repository, not only inside the SIEM interface.",
            "Test each rule with a safe simulation and record the alert that proves it fired.",
            "Document the expected false positives of each rule and tune at least two of them.",
            "Build one dashboard that gives an analyst a useful overview of the environment.",
            "Include a data source coverage table showing which techniques you can and cannot see.",
        ],
        milestones=[
            ("build", "Stand up the SIEM", "Install and start the SIEM in containers or a virtual machine. Confirm you can log in and that data storage works."),
            ("build", "Ingest the first log source", "Ship Linux authentication logs or endpoint events into the SIEM and check the fields are parsed correctly."),
            ("build", "Ingest the second log source", "Add a second source such as web server logs or Windows events, and normalise field names so searches work across both."),
            ("build", "Write the first three detections", "Cover failed logins, a new user being created and a suspicious command. Save each as a rule file with metadata."),
            ("build", "Write the next three detections", "Cover persistence, a privilege change and an unusual process or network connection."),
            ("build", "Build the analyst dashboard", "Show event volume by source, authentication outcomes and the top alerts. Export it into the repository."),
            ("test", "Simulate each technique", "Run a matching safe simulation for each detection and capture the alert. A rule with no proof does not count."),
            ("test", "Tune for false positives", "Generate normal activity, see what fires wrongly, and adjust two rules. Record the before and after."),
            ("document", "Write the detection catalogue", "A table of rule, technique, data source, logic summary, test and false positive notes."),
            ("document", "Write the README and runbook", "Setup instructions that someone else can follow, plus the screenshots that show the lab working."),
        ],
        documentation=[
            ("README", "What the lab is, how to build it from nothing, and what it detects."),
            ("Architecture diagram", "Log sources, the pipeline into the SIEM, the detection layer and the analyst view."),
            ("Detection catalogue", "Every rule with ATT&CK mapping, data source, logic, test method and false positive notes."),
            ("Test evidence", "A screenshot or exported alert for each simulation, with the command used."),
            ("Coverage gaps", "An honest list of techniques you cannot currently detect and what data you would need."),
        ],
        security_notes=[
            "Run attack simulations only on machines you own and that are isolated from your normal network.",
            "Never expose the SIEM or the lab machines to the internet. Default credentials in lab software are well known.",
            "Do not commit the SIEM's generated passwords, certificates or tokens. Use an example environment file with fake values.",
        ],
        interview=[
            ("Choose one detection and explain what behaviour it catches, the logic, and how you proved it works.", "The attacker technique, the data source it depends on, the search logic, the simulation you ran and the alert you saw."),
            ("How did you decide what to detect first?", "Prioritising common, high impact techniques that your data sources can actually see."),
            ("What is a false positive, and how did you reduce one in your lab?", "A benign event that triggers the rule, the analysis that revealed it and the specific tuning that fixed it without hiding real attacks."),
            ("Why store detections as code in a repository?", "Version history, review, testing, repeatable deployment and the ability to explain who changed what and why."),
            ("What can your lab not see, and why does that matter?", "Data source gaps, blind spots such as encrypted or unlogged activity, and the risk of assuming no alert means no attack."),
            ("How would this lab change for a company with ten thousand endpoints?", "Volume, retention cost, agent management, parsing at scale, alert triage workload and access control."),
        ],
        criteria=[
            "Logs from two sources are searchable with consistent field names.",
            "At least six detection rules exist as files in my repository.",
            "Each rule has recorded proof that it fired during a simulation.",
            "I tuned at least two rules and documented the before and after.",
            "The README lets another person rebuild the lab and I included no secrets.",
        ],
        readme={
            "overview": "A home SIEM lab that ingests endpoint and system logs, runs six or more ATT&CK mapped detections and proves each with a safe simulation.",
            "problem": "A SIEM only protects an organisation if it has detections that are accurate, tested and understood by the people who respond to them.",
            "solution": "A reproducible lab with rules stored as code, simulations for every detection, tuning notes and an analyst dashboard.",
            "architecture": "Log sources forward events to the SIEM, which parses and stores them. Detection rules run on the stored data and raise alerts that appear on the dashboard.",
            "installation": "git clone YOUR_REPOSITORY_URL\ncd siem-detection-lab\ncp .env.example .env\n(edit the placeholder passwords in .env)\ndocker compose up -d",
            "usage": "Run a simulation from simulations/, then search for the alert in the SIEM and compare it with the expected result in detections/.",
        },
        hints=[
            "Build the pipeline for one source end to end before adding the second. Parsing problems are easier to fix when there is only one.",
            "Write the simulation before the rule. Knowing the exact events it produces makes the logic obvious.",
            "Keep rule files small and named after the behaviour, such as new_local_admin_created.",
        ],
        common_mistakes=[
            "Using rules copied from the internet that you cannot explain or prove.",
            "Leaving default credentials on lab software and exposing it to the network.",
            "Counting a rule as done without ever making it fire.",
            "Committing a populated environment file with real passwords.",
        ],
        recommended_before=["security-log-analyzer", "network-traffic-investigation"],
        cv_bullet="Built a SIEM detection lab with two log sources and six ATT&CK mapped detections stored as code, validated with Atomic Red Team simulations and tuned to reduce false positives.",
    ),
    project(
        slug="cloud-security-posture-checker",
        title="Cloud Security Posture Checker",
        level="intermediate",
        phase="Phase 8, Cloud Security",
        est_hours=14,
        summary="A Python tool that scans a cloud account for risky configuration such as public storage and over broad permissions, and reports findings with fixes.",
        build="A tool that inspects an AWS account, which can be a free tier or sandbox account, for common misconfigurations: publicly readable storage buckets, unencrypted volumes, overly permissive security groups, missing multi factor authentication and wildcard permissions. It scores the findings and tells the owner how to fix each one.",
        problem="Most cloud breaches come from configuration mistakes rather than clever exploits. Teams create resources quickly and nobody checks them. Security engineers build and run checks that find these problems before an attacker does.",
        why="Cloud posture management is one of the most hired for areas in security. Showing that you can read an account's real configuration through the API, judge risk and recommend fixes demonstrates the exact work of a cloud security engineer.",
        skills=["AWS identity and access management", "Cloud networking", "Storage security", "Boto3 and cloud APIs", "Least privilege", "Infrastructure as code basics", "Reporting for engineers"],
        tools=[
            ("AWS free tier account", "A real but low cost account where you can create safe test resources and a read only user for the checker."),
            ("Python 3 and boto3", "The language and the official AWS library used to read configuration."),
            ("Terraform", "Creates the intentionally weak test resources and tears them down, so the lab is repeatable and cheap."),
            ("moto or localstack", "Lets the unit tests run without touching a real account."),
            ("AWS CLI", "Confirms your findings by hand and manages credentials safely."),
        ],
        deliverable="A GitHub repository with the checker, Terraform for the intentionally misconfigured test resources, sample findings output, tests and a README with the least privilege policy the tool needs.",
        requirements=[
            "Use a dedicated read only identity with the minimum permissions the checker needs, and publish that policy.",
            "Implement at least six checks, covering storage, identity, network and encryption.",
            "Give every finding a severity, the resource affected, an explanation of the risk and a fix.",
            "Output a human readable summary and a machine readable JSON file.",
            "Create intentionally weak resources with infrastructure as code and show the checker finds them, then fixes them and shows the findings disappear.",
            "Never read or print secret values such as access keys or the content of stored objects.",
            "Run the unit tests against mocked services so no real account is needed to test.",
        ],
        milestones=[
            ("build", "Create a safe test account setup", "Set a billing alert, create a read only user for the checker and configure credentials locally without writing them into the project."),
            ("build", "Create the weak test resources", "Use Terraform to create a few intentionally misconfigured resources in your sandbox. Document each weakness you planted."),
            ("build", "Write the storage checks", "Detect buckets that allow public access or lack encryption, and buckets with no access logging."),
            ("build", "Write the identity checks", "Detect users without multi factor authentication, old access keys and policies that grant wildcard permissions."),
            ("build", "Write the network checks", "Detect security groups that open sensitive ports such as 22 or 3389 to the entire internet."),
            ("build", "Build scoring and the report", "Assign severity, sort findings and write both a readable summary and a JSON file."),
            ("test", "Write mocked unit tests", "Use moto to test each check with one compliant and one non compliant resource."),
            ("test", "Run against the weak resources", "Show the checker finds every planted weakness, then apply the fixes and show the findings clear."),
            ("document", "Document the least privilege policy", "Explain each permission the tool needs and why it needs nothing more."),
            ("document", "Write the README and clean up", "Include run instructions, sample output and a section on destroying the test resources so they do not cost money."),
        ],
        documentation=[
            ("README", "What the tool checks, how to run it safely and how to destroy the lab resources."),
            ("Check catalogue", "Each check with the risk it addresses, the API calls it makes and the recommended fix."),
            ("Required permissions", "The exact read only policy the checker needs, with a line explaining each action."),
            ("Before and after evidence", "Sample output showing findings on the weak resources and a clean result after fixing them."),
        ],
        security_notes=[
            "Never commit AWS access keys, secret keys, session tokens or a populated credentials file. Use environment variables or a named profile outside the project.",
            "Set a billing alert and destroy test resources when you finish so a mistake does not become a bill.",
            "Keep the checker read only. A tool that can change an account needs far more review than one that can only read it.",
        ],
        interview=[
            ("Why is public storage so dangerous, and how does your tool detect it?", "Bucket policies, access control lists and account level public access blocks, and why several settings must be checked together."),
            ("What does least privilege mean, and how did you apply it to your own tool?", "Granting only the actions needed, scoping resources, and the reasoning for each permission in your published policy."),
            ("How would you stop these misconfigurations from being created in the first place?", "Infrastructure as code review, policy as code guardrails, service control policies and preventive versus detective controls."),
            ("How do you avoid false positives, such as a bucket that is public on purpose?", "Allow lists with justification, tagging and expiry, and why exceptions must be visible rather than silent."),
            ("What is the shared responsibility model and where does your tool fit in it?", "What the provider secures and what the customer must configure, and the customer side that posture checks address."),
            ("How would you run this across fifty accounts?", "Cross account roles, central aggregation, scheduling, rate limits and keeping the credentials short lived."),
        ],
        criteria=[
            "The checker finds every misconfiguration I planted and nothing it should not.",
            "After I fix the resources, the findings disappear.",
            "The tool uses a read only identity and I published its permission policy.",
            "No access keys, tokens or account identifiers are in the repository history.",
            "Unit tests run against mocked services on a clean checkout, and I destroyed the lab resources.",
        ],
        readme={
            "overview": "A Python tool that audits an AWS account for common security misconfigurations and reports risk and remediation.",
            "problem": "Cloud accounts accumulate public storage, wide open networks and powerful permissions that nobody reviews, and attackers scan for them continuously.",
            "solution": "A read only checker that inspects storage, identity, network and encryption settings, scores what it finds and says how to fix it.",
            "architecture": "Credentials come from the environment. Check modules call the cloud APIs, produce findings, and a reporter writes a summary and JSON. Terraform creates the test resources.",
            "installation": "git clone YOUR_REPOSITORY_URL\ncd cloud-posture-checker\npython3 -m venv .venv\nsource .venv/bin/activate\npip install -r requirements.txt\npython -m pytest",
            "usage": "export AWS_PROFILE=posture-readonly\npython checker.py --region eu-west-2 --output findings.json",
        },
        hints=[
            "Build each check as its own function that takes a client and returns a list of findings. It makes mocking trivial.",
            "Use a named AWS profile for the read only user so credentials never appear in your shell history or your code.",
            "Tag everything Terraform creates with the project name so it is easy to find and destroy.",
        ],
        common_mistakes=[
            "Using your administrator credentials for the checker because it is quicker.",
            "Committing a credentials file or a Terraform state file that contains account details.",
            "Leaving test resources running and paying for them.",
            "Treating every public resource as a vulnerability without context.",
        ],
        recommended_before=["password-security-analyzer", "network-recon-tool"],
        cv_bullet="Built a read only Python cloud posture checker for AWS covering storage, identity, network and encryption, validated against Terraform planted misconfigurations and mocked unit tests.",
    ),
    project(
        slug="soc-alert-dashboard",
        title="SOC Alert Dashboard",
        level="intermediate",
        phase="Phase 9, Detection Engineering",
        legacy_title="Create a mini SOC dashboard",
        est_hours=14,
        summary="A web dashboard where analysts see alerts, triage them with context, and record decisions, backed by a small API and database.",
        build="A small web application that ingests alerts as JSON, stores them in a database, enriches them with simple context such as address reputation notes and asset criticality, and lets an analyst filter, triage and close alerts with a recorded reason. It includes metrics such as alerts by severity and mean time to triage.",
        problem="Analysts drown in alerts. A good queue shows what matters first, gives the context needed to decide, and keeps a record of every decision so the team can learn which alerts are noise.",
        why="This project proves you can build, not only use, security tooling. It shows API design, data modelling, authentication thinking and an understanding of how analysts actually work, which is attractive for security engineering and SOC automation roles.",
        skills=["Python web APIs", "SQL databases", "Alert triage workflow", "Data enrichment", "Frontend basics", "Authentication and input validation", "SOC metrics"],
        tools=[
            ("FastAPI", "Provides the API for ingesting and updating alerts with automatic input validation."),
            ("SQLite", "A simple file database that is enough for one analyst and needs no server."),
            ("SQLAlchemy", "Defines the alert tables and queries in a way that is safe from injection."),
            ("A simple frontend", "Plain HTML with a little JavaScript, or a small framework, to show the queue and the details."),
            ("pytest", "Tests the API endpoints and the enrichment logic."),
        ],
        deliverable="A GitHub repository with the API, the database model, the dashboard, sample alerts, tests, screenshots and a README that explains the triage workflow.",
        requirements=[
            "Ingest alerts through an API endpoint with strict validation of every field.",
            "Store alerts with severity, source, rule name, status, timestamps and analyst notes.",
            "Enrich each alert with asset criticality and a simple indicator lookup from a local file.",
            "Let an analyst filter by severity and status, open an alert, and set a status with a required reason.",
            "Record an audit trail of every status change with who and when.",
            "Show metrics: alerts by severity, open alerts by age and mean time to triage.",
            "Require a login or an API key for the write endpoints and never trust client supplied data.",
        ],
        milestones=[
            ("build", "Design the data model", "Sketch the alert, the status history and the asset tables. Decide which fields are required and which values are allowed."),
            ("build", "Build the ingest API", "Create the endpoint that accepts alerts, validates them and stores them. Reject anything malformed with a clear error."),
            ("build", "Add enrichment", "Look up asset criticality and indicators from local files, and store the result with the alert."),
            ("build", "Build the queue view", "List alerts sorted by severity and age with filters. Show the key facts at a glance."),
            ("build", "Build the alert detail and triage", "Show full context and let an analyst set a status with a required reason. Save every change in an audit trail."),
            ("build", "Add metrics", "Compute alerts by severity, open alert age and mean time to triage, and display them."),
            ("build", "Add authentication", "Protect write actions with login or an API key stored outside the code."),
            ("test", "Write API tests", "Test valid and invalid ingests, filters, status changes and the rule that a reason is required."),
            ("test", "Test with realistic volume", "Load a few thousand sample alerts and check that the queue stays usable. Note what you would change at ten times that."),
            ("document", "Write the API and workflow documentation", "Document endpoints, fields and the triage statuses and what each one means."),
            ("document", "Write the README and capture screenshots", "Use the README Builder and add screenshots of the queue, a detail view and the metrics."),
        ],
        documentation=[
            ("README", "What the dashboard does, how to run it and the triage workflow it supports."),
            ("API reference", "Endpoints, fields, validation rules and example requests and responses."),
            ("Data model", "A diagram or table of the database structure and the reason for each field."),
            ("Screenshots", "The queue, an alert detail and the metrics view, with sample data only."),
        ],
        security_notes=[
            "The dashboard is itself a security tool, so validate every input, use parameterised queries and never render alert content as raw HTML.",
            "Store the API key or secret key in an environment variable and include a fake example file in the repository.",
            "Use only sample alerts. Never load real alert data from an employer into a public project.",
        ],
        interview=[
            ("Describe the life of an alert in your system from ingest to closure.", "Validation, storage, enrichment, triage with a reason, status history and metrics."),
            ("Why must an analyst give a reason when closing an alert?", "Auditability, learning which rules are noisy and the value of decisions that others can review."),
            ("How did you protect the dashboard from malicious alert content?", "Output encoding, strict validation, parameterised queries and the idea that logs and alerts are untrusted input."),
            ("How did you choose the fields and statuses?", "Mapping to how analysts actually work, avoiding statuses that mean the same thing, and keeping the model simple."),
            ("How would you change the design for a team of twenty analysts?", "Assignment, locking, roles and permissions, a real database server, and notifications."),
            ("What metrics would you show a SOC manager, and which would you distrust?", "Mean time to triage and false positive rate, and why raw alert counts can mislead."),
        ],
        criteria=[
            "I can ingest a batch of alerts, triage one with a reason and see the audit trail.",
            "Invalid alerts are rejected with a clear error and never stored.",
            "Write actions require authentication.",
            "The metrics match the stored data when I check them by hand.",
            "Tests pass on a clean checkout and no secrets are in the repository.",
        ],
        readme={
            "overview": "A small SOC alert dashboard with an ingest API, enrichment, a triage queue, an audit trail and operational metrics.",
            "problem": "Analysts need a prioritised queue with context and a record of decisions, or alert volume overwhelms them and the team cannot learn from its own work.",
            "solution": "An API and web interface that ingests validated alerts, adds context, supports triage with required reasons and reports metrics.",
            "architecture": "Alerts arrive at the ingest API, pass validation and enrichment, are stored in the database and are displayed by the dashboard, which writes status changes to an audit table.",
            "installation": "git clone YOUR_REPOSITORY_URL\ncd soc-alert-dashboard\npython3 -m venv .venv\nsource .venv/bin/activate\npip install -r requirements.txt\ncp .env.example .env\nuvicorn app.main:app --reload",
            "usage": "Send an alert with the sample script in scripts/send_sample_alerts.py, then open http://127.0.0.1:8000 to triage it.",
        },
        hints=[
            "Define the allowed severities and statuses as a fixed list in one place and reuse it for validation, filters and the interface.",
            "Write the audit trail from the start. Adding it later means rewriting every status change.",
            "Seed the database from a JSON file so you and the tests always start from the same data.",
        ],
        common_mistakes=[
            "Trusting alert content and rendering it directly in the page.",
            "Building a beautiful interface before the data model is settled.",
            "Letting an analyst close an alert with no reason.",
            "Committing the database file with data in it, or an API key in the code.",
        ],
        recommended_before=["security-log-analyzer", "network-traffic-investigation"],
        cv_bullet="Built a SOC alert dashboard with a validated ingest API, enrichment, triage workflow with audit trail and operational metrics, secured against injection and covered by automated tests.",
    ),
]
