"""Technical terms the Job Description Analyzer can recognise in a posting.

Each entry is a canonical name and the spellings that mean the same thing.
Matching is whole-word and case-insensitive, so "java" never matches inside
"javascript". The list is deliberately limited to concrete tools, languages
and practices, not soft skills, because a soft skill in a posting is a
sentence, not something a lesson or a project can prove.
"""

LEXICON: list[tuple[str, list[str]]] = [
    # Languages
    ("Python", ["python"]),
    ("JavaScript", ["javascript", "js", "ecmascript"]),
    ("TypeScript", ["typescript"]),
    ("Java", ["java"]),
    ("C#", ["c#", "csharp"]),
    ("C++", ["c++"]),
    ("Go", ["golang"]),
    ("Rust", ["rust"]),
    ("Ruby", ["ruby", "ruby on rails"]),
    ("PHP", ["php"]),
    ("Swift", ["swiftui", "swift programming"]),
    ("Kotlin", ["kotlin"]),
    ("Bash", ["bash", "shell scripting", "shell script"]),
    ("PowerShell", ["powershell"]),
    ("SQL", ["sql", "postgresql", "postgres", "mysql", "t-sql"]),
    ("R", ["r programming", "rstudio"]),
    ("HTML and CSS", ["html", "css", "html5", "css3", "sass", "tailwind"]),
    # Web and mobile
    ("React", ["react", "react.js", "reactjs", "next.js", "nextjs"]),
    ("Node.js", ["node.js", "nodejs", "node js", "express.js"]),
    ("Angular", ["angular"]),
    ("Vue", ["vue", "vue.js"]),
    ("Django", ["django"]),
    ("Flask", ["flask"]),
    ("FastAPI", ["fastapi"]),
    ("Spring", ["spring boot"]),
    (".NET", [".net", "asp.net", "dotnet"]),
    ("REST APIs", ["rest api", "rest apis", "restful", "restful apis", "api development"]),
    ("GraphQL", ["graphql"]),
    ("React Native", ["react native"]),
    ("Flutter", ["flutter"]),
    ("Android", ["android", "android studio"]),
    ("iOS", ["ios", "xcode"]),
    # Data and AI
    ("pandas", ["pandas"]),
    ("NumPy", ["numpy"]),
    ("scikit-learn", ["scikit-learn", "sklearn"]),
    ("PyTorch", ["pytorch"]),
    ("TensorFlow", ["tensorflow"]),
    ("Machine learning", ["machine learning", "ml models"]),
    ("Statistics", ["statistics", "statistical analysis", "hypothesis testing"]),
    ("Data visualization", ["data visualization", "data visualisation", "tableau", "power bi", "looker"]),
    ("Excel", ["excel", "google sheets", "spreadsheets"]),
    ("Airflow", ["airflow"]),
    ("Spark", ["spark", "pyspark"]),
    ("Data warehousing", ["data warehouse", "data warehousing", "snowflake", "bigquery", "redshift"]),
    ("Jupyter", ["jupyter"]),
    ("LLM APIs", ["llm", "llms", "large language model", "large language models", "prompt engineering"]),
    ("Vector databases", ["vector database", "vector databases", "pinecone", "embeddings"]),
    ("MongoDB", ["mongodb", "nosql"]),
    # Cloud and infrastructure
    ("AWS", ["aws", "amazon web services"]),
    ("Azure", ["azure"]),
    ("Google Cloud", ["gcp", "google cloud"]),
    ("Docker", ["docker", "containers", "containerization"]),
    ("Kubernetes", ["kubernetes", "k8s"]),
    ("Terraform", ["terraform", "infrastructure as code"]),
    ("CI/CD", ["ci/cd", "github actions", "jenkins", "gitlab ci", "continuous integration"]),
    ("Linux", ["linux", "unix", "ubuntu", "kali"]),
    ("Networking", ["networking", "tcp/ip", "dns", "dhcp", "vpn", "firewalls", "firewall", "routing and switching"]),
    ("Git", ["git", "github", "gitlab", "version control"]),
    ("IAM", ["iam", "identity and access management"]),
    ("Windows", ["windows server", "active directory", "windows 10", "windows 11", "microsoft 365", "office 365"]),
    ("Monitoring", ["prometheus", "grafana", "datadog", "observability"]),
    # Security
    ("SIEM", ["siem", "splunk", "microsoft sentinel", "qradar", "elastic security"]),
    ("Wireshark", ["wireshark", "packet analysis", "packet capture"]),
    ("Nmap", ["nmap", "vulnerability scanning", "nessus"]),
    ("Incident response", ["incident response", "incident handling", "triage"]),
    ("MITRE ATT&CK", ["mitre att&ck", "mitre attack"]),
    ("Penetration testing", ["penetration testing", "pentesting", "pen testing", "burp suite", "metasploit"]),
    ("Threat detection", ["threat detection", "threat hunting", "detection engineering", "log analysis"]),
    ("Security frameworks", ["nist", "iso 27001", "soc 2", "owasp", "cis controls"]),
    ("Cloud security", ["cloud security", "guardduty", "security groups"]),
    # Quality and process
    ("Test automation", ["selenium", "playwright", "cypress", "test automation", "automated testing"]),
    ("Unit testing", ["unit testing", "unit tests", "pytest", "jest", "junit"]),
    ("Agile", ["agile", "scrum", "kanban", "sprint planning"]),
    ("Jira", ["jira", "ticketing", "service desk", "servicenow", "zendesk"]),
    ("Data structures and algorithms", ["data structures", "algorithms"]),
    ("System design", ["system design", "software architecture", "distributed systems", "microservices"]),
    ("Documentation", ["technical documentation", "api documentation", "docs-as-code", "markdown"]),
    # Design and product
    ("Figma", ["figma"]),
    ("Adobe Creative Suite", ["photoshop", "illustrator", "indesign", "adobe creative"]),
    ("Prototyping", ["prototyping", "wireframing", "wireframes", "prototypes"]),
    ("User research", ["user research", "usability testing", "user interviews"]),
    ("Design systems", ["design systems", "design system"]),
    ("Accessibility", ["accessibility", "wcag"]),
    ("Product analytics", ["product analytics", "product metrics", "a/b testing", "ab testing", "mixpanel", "amplitude"]),
    ("Roadmapping", ["roadmapping", "product roadmap", "product strategy"]),
    ("No-code tools", ["zapier", "airtable", "webflow", "bubble.io", "make.com", "no-code"]),
]
