"""New careers: Design & Product (motion design, business analysis, UX research)."""

CAREERS = [
    dict(
        slug="motion-design", name="Motion Design",
        summary="Bring brands and products to life with animation: logo and explainer videos, interface micro-interactions and motion that ships as video or Lottie files, planned with timing, easing and sound.",
        beginner_summary="You'll learn why good animation feels natural, then build bouncing balls, button animations and a short brand video you can show employers.",
        difficulty=3, avg_timeline_weeks=30,
        entry_roles=["Junior Motion Designer", "Motion Graphics Artist (junior)", "Junior Video Editor with motion skills", "Social Media Motion Designer"],
        tools=["Adobe After Effects", "Figma", "LottieFiles", "Adobe Illustrator", "Adobe Premiere Pro", "DaVinci Resolve", "Rive"], remote_potential=75,
        earning_notes="Hiring is reel-driven, so a short, polished showreel counts for more than any certificate. Many people start in freelance, social media or agency work, or by adding motion to a design or video editing job. Pay tends to rise with speed, storytelling skill and specialisms such as product motion or 3D.",
        icon="film",
        skills_required=["Animation principles (timing, spacing, easing, anticipation, follow through)", "Storyboarding and planning a piece before animating it", "Keyframe animation and layer structure in After Effects", "Designing UI motion that helps users instead of distracting them", "Exporting for the target: Lottie, video formats and file size budgets", "Basic sound design and editing so motion lands on the beat"],
        certifications=["Adobe Certified Professional in Video Design"],
        interview_prep=[
            "Pick one piece from your reel and explain the timing and easing choices in it",
            "How do you decide whether a piece of interface motion helps the user or gets in the way",
            "A developer tells you your Lottie animation is 400 KB and slows the page. What do you check and change",
            "A client says the draft needs to 'pop more' and the deadline is tomorrow. What do you do",
            "Walk through how you would storyboard a 30 second explainer for a product you have never used",
            "Which of the twelve animation principles matter most in UI work, and which would you drop",
        ],
        learning_resources=[
            {"label": "The Animator's Survival Kit by Richard Williams", "note": "The standard book on timing, spacing and the principles of animation, useful for motion graphics as much as character work."},
            {"label": "Adobe After Effects tutorials", "note": "Free, official tutorials from Adobe covering keyframes, shape layers, the graph editor and rendering."},
            {"label": "Material Design motion guidelines", "note": "Free guidance from Google on duration, easing and purposeful motion in real interfaces."},
        ],
        roadmap_outline={
            "beginner": [
                "Study the twelve principles of animation and spot them in ads, title sequences and app interactions you use",
                "Learn the After Effects basics: compositions, shape layers, keyframes and the graph editor",
                "Animate a bouncing ball until you can control weight, timing and easing on purpose",
                "Learn to read a motion brief and sketch a rough storyboard before you open any software",
            ],
            "intermediate": [
                "Animate icons and UI states, such as a toggle, a like button and a success tick, in short durations",
                "Export an animation with Bodymovin and play it on a web page with lottie-web",
                "Prototype the same interactions in Figma with Smart Animate and compare them with your After Effects version",
                "Learn to keep files light: fewer layers and keyframes, simple shapes and a size budget per animation",
                "Animate a logo reveal and a kinetic typography piece with a clear beginning, middle and end",
            ],
            "advanced": [
                "Write, record and storyboard a 45 second explainer, then animate it scene by scene",
                "Add a voiceover, music and sound effects and cut it together in a video editor",
                "Export one project in several formats and sizes for web, social and product, with a file size table",
                "Cut a 60 to 90 second showreel that opens with your strongest piece, and ask working motion designers to critique it",
            ],
        },
    ),
    dict(
        slug="business-analysis", name="Business Analysis",
        summary="Work out what a business actually needs, then write it down clearly enough for a team to build and test: interviews, process maps, user stories with acceptance criteria and checks against the data.",
        beginner_summary="You'll learn to ask the right questions, map how work really happens, and turn what people tell you into clear requirements that developers and testers can use.",
        difficulty=3, avg_timeline_weeks=22,
        entry_roles=["Junior Business Analyst", "Associate Business Analyst", "Business Systems Analyst (junior)", "Operations or Process Analyst", "Requirements Analyst (junior)"],
        tools=["Jira", "Confluence", "Camunda Modeler", "Bizagi Modeler", "Lucidchart", "Miro", "SQL", "Microsoft Excel"], remote_potential=70,
        earning_notes="Many analysts move in from inside a company, from support, operations, QA, finance or admin roles where they already know how the work runs. Outside hires usually need one sound sample of requirements work and a good grasp of the sector. Pay tends to grow with domain knowledge and with the size of the projects you can run.",
        icon="clipboard",
        skills_required=["Eliciting needs through stakeholder interviews and workshops", "Process modelling in BPMN, as-is and to-be", "Writing requirements, user stories and Given/When/Then acceptance criteria", "Gap analysis, impact analysis and prioritisation (MoSCoW)", "Requirements traceability and user acceptance test planning", "Checking assumptions in data with basic SQL"],
        certifications=["IIBA Entry Certificate in Business Analysis (ECBA)", "IIBA Certification of Capability in Business Analysis (CCBA, needs documented work experience)", "IIBA Certified Business Analysis Professional (CBAP, needs substantial documented work experience)", "PMI Professional in Business Analysis (PMI-PBA, needs documented work experience)"],
        interview_prep=[
            "A stakeholder asks you to 'add a button that emails the report' instead of describing the problem. How do you find the real need",
            "Two senior stakeholders give you conflicting requirements and both call theirs a Must Have. What do you do",
            "Midway through user acceptance testing, users reject a feature that matches the signed-off requirement. How do you handle it",
            "Write acceptance criteria in Given/When/Then for a password reset feature, live",
            "Walk me through how you would model the as-is process for returning an online order",
            "How do you keep requirements traceable when a change request arrives halfway through the build",
        ],
        learning_resources=[
            {"label": "BABOK Guide from IIBA", "note": "The standard reference for business analysis tasks and techniques, free to IIBA members."},
            {"label": "Camunda's BPMN tutorial and reference", "note": "A free, clear introduction to BPMN symbols and good modelling habits."},
            {"label": "Atlassian University", "note": "Free courses on Jira and Confluence, the two tools most analysts use daily."},
        ],
        roadmap_outline={
            "beginner": [
                "Learn the core vocabulary: stakeholder, scope, business case, requirement, as-is and to-be",
                "Skim the knowledge areas in the BABOK Guide to see what an analyst is expected to do",
                "Learn the BPMN basics: pools, lanes, tasks, gateways and events",
                "Learn enough SQL (SELECT, WHERE, JOIN, GROUP BY) to check what a table really contains",
                "Learn Jira basics: epics, stories, statuses and a simple board",
            ],
            "intermediate": [
                "Prepare open interview questions, run an interview with a real person and write up the notes",
                "Write user stories with Given/When/Then acceptance criteria for a small feature",
                "Run a gap analysis between how a process works now and how it needs to work",
                "Prioritise a requirements list with MoSCoW and be ready to explain what was cut",
                "Document it all in Confluence using a clear requirements page structure",
            ],
            "advanced": [
                "Build a traceability matrix from business objective to requirement to test case",
                "Write a UAT plan with scenarios, entry and exit criteria and a defect process",
                "Facilitate a short workshop that resolves conflicting requirements and records the decision",
                "Assemble one case study from discovery to a reviewed requirements pack",
                "Study for the ECBA, and plan CCBA or CBAP once you have the work experience they require",
            ],
        },
    ),
    dict(
        slug="ux-research", name="UX Research",
        summary="Find out what users do and need through interviews, surveys, usability tests and card sorts, then turn the evidence into findings that change what a team builds.",
        beginner_summary="You'll learn to plan a study, talk to real people without steering them, and turn messy notes into clear findings a team can act on.",
        difficulty=3, avg_timeline_weeks=26,
        entry_roles=["Junior UX Researcher", "Associate UX Researcher", "Research Assistant (UX)", "Usability Analyst", "Research Operations Coordinator"],
        tools=["Dovetail", "Maze", "Optimal Workshop", "Miro", "Google Forms", "UserTesting", "Zoom"], remote_potential=70,
        earning_notes="Dedicated junior research roles are scarce and competitive, so many people come in from design, psychology, market research, customer support or analytics. Teams hire on evidence that you can run a sound study and change a decision with it. Pay tends to follow the scope of the questions you can own and how well you influence stakeholders.",
        icon="search",
        skills_required=["Planning studies: research questions, methods, recruitment and ethics (consent, privacy)", "Interviewing and moderating sessions without leading participants", "Survey design and quantitative basics (task success, SUS)", "Card sorting and tree testing for information architecture", "Synthesis with affinity mapping and thematic analysis", "Communicating findings so a team acts on them"],
        certifications=["Nielsen Norman Group UX Certification (earned through NN/g courses and exams)", "Google UX Design Professional Certificate"],
        interview_prep=[
            "A product manager asks you to run a survey that will 'prove' users want a feature. What do you say and do",
            "You have one week and no budget to learn why people abandon a sign-up form. What would you do",
            "Your findings contradict what the lead designer has spent three months building. How do you share them",
            "Rewrite this question so it is not leading: 'How much do you love our new dashboard?'",
            "How do you choose between interviews, a survey and a usability test for a given research question",
            "How many participants do you need, and what can you honestly claim from that number",
        ],
        learning_resources=[
            {"label": "Just Enough Research by Erika Hall", "note": "A short, practical book on choosing and running research that fits a real team's time and budget."},
            {"label": "Rocket Surgery Made Easy by Steve Krug", "note": "A step-by-step guide to running small, quick usability tests yourself."},
            {"label": "Nielsen Norman Group articles", "note": "Free articles on interviews, surveys, card sorting, sample sizes and reporting from a long-standing UX research firm."},
        ],
        roadmap_outline={
            "beginner": [
                "Learn the difference between generative and evaluative research, and between attitudes and behaviour",
                "Learn research ethics: informed consent, privacy, data retention and treating participants fairly",
                "Practise writing neutral, open questions and rewriting leading ones",
                "Write a one page research plan with goals, questions, method, participants and timeline",
            ],
            "intermediate": [
                "Run and record a set of interviews, then code the transcripts into themes",
                "Run a card sort and a tree test to evaluate how a site's content is organised",
                "Write a short survey in Google Forms and learn its limits as evidence",
                "Learn the basics of quantitative measures: task success, time on task and the System Usability Scale",
                "Practise affinity mapping on a board in Miro or Dovetail",
            ],
            "advanced": [
                "Run a diary study and combine it with a survey and interviews",
                "Build a journey map and persona that cite the evidence behind every claim",
                "Set up a simple research repository so findings can be found and reused",
                "Present findings to a sceptical audience with a clear recommendation and ask",
                "Build a portfolio with two or three studies that each ended in a changed decision",
            ],
        },
    ),
]


META = {
    "motion-design": dict(
        keywords=["motion designer", "motion graphics", "animation", "animator", "after effects", "lottie", "bodymovin", "micro-interactions", "explainer video", "video editing", "kinetic typography", "easing", "storyboard", "premiere pro", "logo animation", "ui animation", "rive", "brand video"],
        who_its_for="People who watch how things move and want to control it, and who can be patient with frame-level detail. The catch is that you need both taste and technical discipline, and your reel is judged on polish.",
        portfolio_expectations=[
            "A showreel of 60 to 90 seconds that opens with your strongest piece",
            "A set of UI micro-interactions exported as Lottie, with file sizes listed and a working web demo",
            "A 30 to 45 second brand or explainer video with script, storyboard, sound and captions",
            "A short breakdown of one piece showing sketches, style frames and the timing and easing choices you made",
        ],
        career_progression=["Junior Motion Designer", "Motion Designer", "Senior Motion Designer", "Motion Design Lead, Art Director or Creative Director"],
    ),
    "business-analysis": dict(
        keywords=["business analyst", "ba", "requirements", "requirements gathering", "user stories", "acceptance criteria", "bpmn", "process mapping", "process modelling", "use cases", "gap analysis", "uat", "stakeholder", "jira", "confluence", "ecba", "cbap", "systems analyst"],
        who_its_for="Curious, organised people who like asking why, listening carefully and writing things down precisely. Often reached from inside a company. The catch is that you have to keep people with competing interests on one page without owning the final decisions.",
        portfolio_expectations=[
            "An as-is and to-be process model in BPMN with the pain points marked",
            "A requirements pack with user stories, Given/When/Then acceptance criteria and MoSCoW priorities",
            "A traceability matrix and a UAT plan for a realistic change",
            "A short write-up of interviews or a workshop, showing the questions you asked and what changed because of the answers",
        ],
        career_progression=["Junior Business Analyst", "Business Analyst", "Senior Business Analyst", "Lead Business Analyst, Product Owner or Head of Business Analysis"],
    ),
    "ux-research": dict(
        keywords=["ux researcher", "user researcher", "user research", "usability testing", "interviews", "surveys", "card sorting", "tree testing", "diary study", "personas", "journey map", "dovetail", "maze", "optimal workshop", "research ops", "design research", "sus", "affinity mapping"],
        who_its_for="Curious, careful listeners who like finding out why people behave as they do and can stay neutral when the evidence is inconvenient. The catch is that it is not a design role: your output is evidence and persuasion, and junior openings are rare, so many people arrive from adjacent jobs.",
        portfolio_expectations=[
            "A research plan with goals, method, recruitment, consent wording and ethics notes for a real study",
            "A card sort and tree test with the data, the findings and the structure you recommended",
            "A synthesis case study that shows raw notes, themes and the evidence behind each insight",
            "A research readout, with an evidence-based journey map, that ends in clear recommendations and what the team decided",
        ],
        career_progression=["Junior UX Researcher", "UX Researcher", "Senior UX Researcher", "Lead Researcher, Research Manager or Head of Research"],
    ),
}


PROJECTS = {
    "motion-design": {
        "skills": [
            {"key": "animation_principles", "label": "Animation Principles, Timing and Easing", "category": "foundation"},
            {"key": "storyboarding_planning", "label": "Storyboarding and Planning", "category": "foundation"},
            {"key": "ui_micro_interactions", "label": "UI Micro-interactions and Lottie", "category": "core"},
            {"key": "export_and_performance", "label": "Export Formats and Performance Budgets", "category": "core"},
            {"key": "sound_and_edit", "label": "Sound and Editing for Motion", "category": "advanced"},
        ],
        "skill_edges": [
            ("animation_principles", "storyboarding_planning"),
            ("animation_principles", "ui_micro_interactions"),
            ("ui_micro_interactions", "export_and_performance"),
            ("storyboarding_planning", "sound_and_edit"),
            ("export_and_performance", "sound_and_edit"),
        ],
        "phases": [
            {
                "title": "Foundations",
                "summary": "Learn how timing, spacing and easing create weight and personality, using the oldest exercise in animation, the bouncing ball, in After Effects.",
                "skill_key": "animation_principles",
                "projects": [{
                    "title": "Animate a bouncing ball three ways to learn timing, easing and squash and stretch",
                    "teaches": "how timing, easing curves and squash and stretch change what an object feels like, using keyframes and the graph editor.",
                    "prerequisites": ["A computer that can run Adobe After Effects (7-day free trial) and a phone that can record video", "Having read a short summary of the twelve principles of animation"],
                    "expected_output": "A short comparison video of three versions of the same bouncing ball (linear, eased, and fully principled with squash, stretch and anticipation), plus a one page note listing the frame counts and curve choices behind each.",
                    "steps": [
                        "Film a real ball being dropped and bouncing on your phone, ideally in slow motion, and note how many frames it spends near the top of each bounce compared with near the floor.",
                        "Plan on paper before you start the After Effects trial: sketch the ball's path, the floor line and which frames hold the key poses.",
                        "In After Effects create a 1920 by 1080 composition at 30 fps and 4 seconds long, draw an ellipse with the Ellipse Tool (Q) on a shape layer, and set Position keyframes for three bounces (press P, then U to see keyframes).",
                        "Version A: leave the keyframes linear and render a preview, noting how robotic it feels.",
                        "Version B: select the keyframes and press F9 for Easy Ease, then open the Graph Editor (Shift+F3) and drag the speed handles so the ball accelerates into the floor and slows at the top of each bounce.",
                        "Version C: add Scale keyframes so the ball stretches while falling fast, squashes on impact and recovers, keep its volume plausible, add anticipation before the first drop and shorten each bounce so it loses energy.",
                        "Add a soft shadow ellipse on its own layer that scales and fades with the ball's height to anchor it to the floor.",
                        "Choose Composition > Add to Adobe Media Encoder Queue (or Add to Render Queue), export each version as H.264 MP4, and place the three clips side by side in one comparison video.",
                        "Write your one page note: for each version, the number of frames per bounce, which curve you used and what it makes the ball feel like (rubber, steel, balloon).",
                    ],
                    "hints": [
                        "Compare your reference video with your timeline frame by frame; real objects spend more frames near the top of a bounce than near the floor.",
                        "To make the same ball feel heavy, shorten the bounce and lengthen the settle; to make it feel light, hold longer at the apex.",
                        "The Graph Editor's speed graph is easier for easing than the value graph: aim for a steep rise into the floor and a flat curve at the apex.",
                        "The After Effects trial is time-limited, so finish planning and your reference footage before you start it.",
                    ],
                    "common_mistakes": [
                        "Leaving every keyframe on Easy Ease with default handles, which makes everything feel soft and weightless.",
                        "Stretching the ball so far it changes volume, which reads as rubber but not as the same object.",
                        "Making each bounce the same height and duration, so the ball never seems to lose energy.",
                        "Skipping the reference footage and animating from memory.",
                    ],
                    "difficulty": 1,
                }],
            },
            {
                "title": "Building Real Skills",
                "summary": "Design small interface animations that give feedback to users, export them as Lottie files and keep each one within a size budget a developer would accept.",
                "skill_key": "ui_micro_interactions",
                "projects": [{
                    "title": "Build three UI micro-interactions and ship them as Lottie files with a file size budget",
                    "teaches": "how to design short, purposeful interface motion, export it through Bodymovin and prove it plays correctly on a web page within a size budget.",
                    "prerequisites": ["Finished the bouncing ball exercise or equal comfort with keyframes and the graph editor", "Adobe After Effects with the Bodymovin extension", "A free Figma account and a text editor", "Basic ability to open an HTML file in a browser"],
                    "expected_output": "Three Lottie JSON files (a toggle, a like button and a submit-to-success tick), a small web page that plays them on click with lottie-web, and a table giving each file's size in KB and duration in milliseconds.",
                    "steps": [
                        "Choose three interactions: a toggle switch, a heart or like button, and a button that turns into a success tick. Write one line for each saying what the user needs to know when it plays.",
                        "Draw the artwork in Figma, or take simple SVGs from the open source Phosphor Icons set, and export them as SVG.",
                        "Import the SVG into After Effects and choose Layer > Create > Create Shapes from Vector Layer so you keep editable shape layers; avoid raster images and heavy effects.",
                        "Animate each interaction in a 30 fps composition, keeping small feedback under about 400 ms and using ease-out so it responds immediately and settles gently.",
                        "Install Bodymovin for After Effects following the instructions in the airbnb/lottie-web GitHub repository, open it from Window > Extensions, check the Report tab for unsupported features, then render each composition to JSON.",
                        "Preview each file in the LottieFiles web previewer and note its size in KB; set yourself a budget (for example 30 KB per file) and reduce layers, keyframes and path points until you meet it.",
                        "Build a small HTML page that loads lottie-web from cdnjs and plays each animation on click with lottie.loadAnimation and a click listener.",
                        "Add support for reduced motion: check window.matchMedia('(prefers-reduced-motion: reduce)') and show the final frame instead of playing the animation.",
                        "Rebuild one interaction as a Figma prototype using Smart Animate and an ease-out curve at about 200 ms, and write three sentences comparing it with your Lottie version.",
                    ],
                    "hints": [
                        "Lottie supports only part of After Effects, so build with shape layers, trim paths and basic transforms and test early after export.",
                        "A path with fewer points and a layer with fewer keyframes both shrink the JSON; merge shapes and delete hidden layers before exporting.",
                        "Compare your animation at real size next to the surrounding interface; motion that looks great at 800 percent zoom is often too large in context.",
                        "Use anticipation sparingly in UI; users are waiting for a response and a long wind-up feels like lag.",
                    ],
                    "common_mistakes": [
                        "Using effects or expressions that Bodymovin cannot export, then discovering it only after the render.",
                        "Making interaction feedback so long that users wait on it before they can continue.",
                        "Exporting without checking file size, then handing a developer a file much larger than the icon deserves.",
                        "Ignoring reduced motion settings, so the animation plays for users who have asked their device to minimise motion.",
                    ],
                    "difficulty": 3,
                }],
            },
            {
                "title": "Advanced Practice",
                "summary": "Plan, animate, score and export a complete brand explainer, and deliver it in the versions a real client would need, with a performance budget for each.",
                "skill_key": "sound_and_edit",
                "projects": [{
                    "title": "Produce a 45 second brand explainer with storyboard, sound mix and multi-format exports",
                    "teaches": "how to carry a motion piece from script and storyboard through animation, sound and a simple edit to several export sizes with a clear size budget.",
                    "prerequisites": ["Completed the Lottie micro-interaction project", "Adobe After Effects, plus the free DaVinci Resolve for the edit and sound mix", "The free Audacity audio editor and a phone or headset microphone", "A fictional company, or a real small business that has agreed to be your subject"],
                    "expected_output": "A 45 second explainer video with voiceover, music, sound effects and burned-in captions, exported as 16:9, 1:1 and 9:16 MP4s, plus a one page project note with the script, storyboard and a table of file sizes.",
                    "steps": [
                        "Write a script of about 100 words that explains one idea in the subject's product, ending with one clear call to action.",
                        "Record a scratch voiceover in Audacity, remove noise and long gaps, and time it; let the voiceover set the length of each scene.",
                        "Storyboard 8 to 10 frames in Figma or on paper, noting the duration of each scene in seconds and how you move from one scene to the next.",
                        "Design two style frames in Illustrator or Figma with palette, type and key shapes, and get feedback from at least one person before animating.",
                        "Animate each scene in its own After Effects precomp at 30 fps, choosing one easing rule for the whole piece (for example a quick ease-out for entrances) so it feels consistent.",
                        "Import the renders and voiceover into DaVinci Resolve (free), add music from a source whose licence you have checked (YouTube Audio Library or Pixabay Music) and sound effects from Freesound, and lower the music under the voice.",
                        "Check loudness with Fairlight's loudness meter and aim near the commonly used online target of about -14 LUFS, then add captions so the video works with sound off.",
                        "Export H.264 MP4s at 1920 by 1080 for web, 1080 by 1080 for feed posts and 1080 by 1920 for vertical stories, re-framing the layout for each rather than cropping blindly.",
                        "Record file sizes in a table, show the piece to three people with and without sound, ask them to explain the message back to you, and revise the scene that confused them.",
                    ],
                    "hints": [
                        "Animate to the voiceover from the start; changing the audio length later means re-timing every scene.",
                        "Hit the key sound on the first frame of a movement, not the last; hits that land a few frames early usually feel tighter.",
                        "Design the 1:1 and 9:16 versions from the storyboard stage, keeping key text inside a safe margin.",
                        "If the file is too large, lower the bitrate before you lower the resolution, and check the result at full screen.",
                    ],
                    "common_mistakes": [
                        "Starting to animate before the script and storyboard are settled, then rebuilding scenes when the message changes.",
                        "Using music or sound effects without checking their licence.",
                        "Leaving music louder than the voice, or exporting with no captions for people watching muted.",
                        "Cropping one 16:9 master into vertical, which cuts off text and focal points.",
                    ],
                    "difficulty": 5,
                }],
            },
        ],
    },
    "business-analysis": {
        "skills": [
            {"key": "process_modelling", "label": "Process Modelling with BPMN", "category": "foundation"},
            {"key": "elicitation", "label": "Stakeholder Elicitation", "category": "core"},
            {"key": "requirements_writing", "label": "Requirements and User Stories", "category": "core"},
            {"key": "gap_impact_prioritisation", "label": "Gap, Impact and Prioritisation", "category": "advanced"},
            {"key": "traceability_uat", "label": "Traceability and UAT Planning", "category": "advanced"},
        ],
        "skill_edges": [
            ("process_modelling", "elicitation"),
            ("elicitation", "requirements_writing"),
            ("requirements_writing", "gap_impact_prioritisation"),
            ("gap_impact_prioritisation", "traceability_uat"),
        ],
        "phases": [
            {
                "title": "Foundations",
                "summary": "Learn to see a process as steps, people and decisions, and to draw it in BPMN so the pain points are visible to everyone who works in it.",
                "skill_key": "process_modelling",
                "projects": [{
                    "title": "Map the as-is returns process of an online shop in BPMN and mark the pain points",
                    "teaches": "how to turn a messy real-world process into a clear BPMN swimlane diagram and spot where it breaks down.",
                    "prerequisites": ["A free download of Camunda Modeler", "A published returns policy from an online retailer, or a small online seller willing to talk for 20 minutes", "Basic familiarity with the BPMN symbols for tasks, gateways and events"],
                    "expected_output": "A BPMN 2.0 diagram (the .bpmn file plus a PNG or SVG export) of how an online returns process works today, with five annotated pain points and a list of open questions for the people who run it.",
                    "steps": [
                        "Pick one process with a clear start and end: a customer asks to return an item, and it ends with a refund, exchange or rejection.",
                        "Gather the facts from the retailer's public returns policy, or from a short interview with a small online seller, and list every person or system that touches the return (customer, support, warehouse, payment provider).",
                        "Open Camunda Modeler, create a new BPMN diagram, add a pool for the business and a lane for each role.",
                        "Add a start event, then each task, naming tasks with a verb and an object such as 'Check return window' or 'Issue refund'.",
                        "Add exclusive gateways for each decision (is it within the return window, is the item damaged, is the customer asking for a refund or an exchange) and label every outgoing path.",
                        "Add end events for each outcome and separate end events for the rejection and refund cases rather than joining them.",
                        "Mark five pain points on the diagram using text annotations, such as manual re-keying of data, waiting for a response, or an unclear rule.",
                        "Write a list of open questions you could not answer from the facts you had, then ask someone who knows the process to review the diagram and correct what you got wrong.",
                    ],
                    "hints": [
                        "Model what actually happens, including workarounds, and not what the policy says should happen.",
                        "If a gateway has one outgoing path, you have probably missed a decision; if it has more than three, split it.",
                        "Keep it to one page; if you need more space, make a sub-process rather than a longer diagram.",
                        "Show your first draft to someone who works in the process; their corrections are the part of the work that makes you good at it.",
                    ],
                    "common_mistakes": [
                        "Drawing the process as a flowchart with no lanes, so nobody can see who does what.",
                        "Naming tasks vaguely, for example 'Process return', so nobody can tell what the step is.",
                        "Modelling only the happy path and leaving out rejections, delays and exceptions.",
                        "Moving to a to-be solution before the as-is process is agreed.",
                    ],
                    "difficulty": 1,
                }],
            },
            {
                "title": "Building Real Skills",
                "summary": "Interview real people about a real problem, turn the answers into user stories with testable acceptance criteria, and record them in the tools a team uses.",
                "skill_key": "requirements_writing",
                "projects": [{
                    "title": "Turn two stakeholder interviews into a prioritised backlog of Jira stories with Given/When/Then criteria",
                    "teaches": "how to prepare and run interviews, extract needs rather than solutions, and write prioritised stories with acceptance criteria in Jira and Confluence.",
                    "prerequisites": ["Completed a BPMN process mapping exercise", "Free Jira and Confluence plans from Atlassian", "Two people willing to be interviewed about how their group handles one process, such as a club, a volunteer team or a family business"],
                    "expected_output": "A Jira project with one epic and 8 stories, each with two or three Given/When/Then acceptance criteria and a MoSCoW label, plus a Confluence requirements page with the stakeholder map, interview notes and your prioritisation reasoning.",
                    "steps": [
                        "Choose a small, real problem such as how a club handles membership sign-ups and renewals, and write a one sentence problem statement.",
                        "Draw a stakeholder map in Miro or on paper using a power and interest grid, naming who is affected and who decides.",
                        "Write an interview guide with eight open questions (for example 'Tell me about the last time this went wrong') and ask permission before taking notes.",
                        "Run two interviews of about 20 minutes each, take notes without leading the person, and write them up the same day.",
                        "List 12 to 15 needs from the notes, rewriting any stated solution ('add a spreadsheet') into the underlying need ('know who has paid').",
                        "Create a Jira project from the free plan, add one epic and write 8 stories in the form 'As a [role], I want [capability], so that [benefit]'.",
                        "Add two or three Given/When/Then acceptance criteria to each story, so a tester could pass or fail each one.",
                        "Label each story Must, Should, Could or Won't have this time (MoSCoW) and write a sentence explaining each Won't.",
                        "Publish a Confluence page containing the problem statement, stakeholder map, key findings, the story list and the open questions, then ask one interviewee whether it matches what they said.",
                    ],
                    "hints": [
                        "Ask 'why' and 'what happens then' more often than 'would you like'; people describe problems better than they design solutions.",
                        "A good acceptance criterion has a specific input and an observable result, with no words like 'quickly' or 'easy'.",
                        "If a story needs more than one 'and', it is probably two stories.",
                        "Keep a short list of assumptions at the top of your Confluence page and mark each as confirmed or unconfirmed.",
                    ],
                    "common_mistakes": [
                        "Writing requirements that name a screen or a technology instead of a need.",
                        "Marking everything Must have, so the prioritisation tells the team nothing.",
                        "Writing acceptance criteria that cannot be tested, such as 'the system should be user friendly'.",
                        "Writing stories that nobody has confirmed with the person who has the problem.",
                    ],
                    "difficulty": 3,
                }],
            },
            {
                "title": "Advanced Practice",
                "summary": "Take a change from objective through gap analysis, data checks, traceability and a user acceptance test plan, the work that decides whether a project delivers what it promised.",
                "skill_key": "traceability_uat",
                "projects": [{
                    "title": "Analyse a stock reorder alert change with SQL data checks, a traceability matrix and a UAT plan",
                    "teaches": "how to test requirements against real data, assess the gap and impact of a change, and link objectives to tests so nothing is missed or untested.",
                    "prerequisites": ["Completed the stakeholder interview and user story project", "DB Browser for SQLite (free) and the Northwind sample database in its SQLite form from a public GitHub repository", "Basic SQL: SELECT, WHERE, JOIN, GROUP BY", "Google Sheets"],
                    "expected_output": "A change pack for 'automatic low-stock reorder alerts' containing a gap and impact analysis, a record of SQL data checks and what they changed, a traceability matrix from objective to test case, and a UAT plan with eight Given/When/Then test scenarios.",
                    "steps": [
                        "Write a business objective for the Northwind trading company, such as 'reduce the number of products that run out before a reorder is placed', and three requirements that support it.",
                        "Write a gap analysis table with columns for the capability needed, how the company does it now (as far as the data shows), the gap and the effort to close it.",
                        "Open the Northwind database in DB Browser for SQLite and examine the Products table, including the UnitsInStock, UnitsOnOrder, ReorderLevel and Discontinued columns.",
                        "Write SQL to count products at or below their reorder level, and then check how many have a ReorderLevel of zero or are discontinued; note any result that makes a requirement ambiguous.",
                        "Revise the requirements in light of the data (for example a rule for products with no reorder level) and record each change and the reason.",
                        "Write an impact analysis listing the roles, processes, reports and data fields affected by the change, with one risk and one mitigation for each.",
                        "Build a traceability matrix in Google Sheets with columns for objective, requirement, user story, test case and status, and check that every requirement has at least one test.",
                        "Write a UAT plan covering scope, who tests, entry and exit criteria, eight scenarios in Given/When/Then form and how defects are logged and given a severity.",
                        "Write a one page summary for a sponsor with the recommendation, key risks and the three questions that still need an answer before build.",
                    ],
                    "hints": [
                        "Write your SQL checks into the pack alongside the result; a requirement based on data no one has checked is a guess.",
                        "When a query surprises you, treat it as a finding to resolve with the data owner, not as a reason to quietly change the requirement.",
                        "Every row of the traceability matrix should read in both directions: from objective down to test, and from test back up to objective.",
                        "UAT scenarios should be written in the business's language so the people who will use the system can run them without help.",
                    ],
                    "common_mistakes": [
                        "Treating the gap analysis as a list of wishes rather than a comparison of current and needed capability.",
                        "Running SQL checks but not recording what changed in the requirements as a result.",
                        "Writing UAT scenarios that only cover the happy path.",
                        "Letting the traceability matrix go out of date once a requirement changes.",
                    ],
                    "difficulty": 5,
                }],
            },
        ],
    },
    "ux-research": {
        "skills": [
            {"key": "research_planning_ethics", "label": "Research Planning and Ethics", "category": "foundation"},
            {"key": "interviewing_moderation", "label": "Interviewing and Moderation", "category": "core"},
            {"key": "ia_methods", "label": "Card Sorting and Tree Testing", "category": "core"},
            {"key": "synthesis_analysis", "label": "Synthesis and Analysis", "category": "advanced"},
            {"key": "influencing_with_evidence", "label": "Reporting and Influencing", "category": "advanced"},
        ],
        "skill_edges": [
            ("research_planning_ethics", "interviewing_moderation"),
            ("interviewing_moderation", "ia_methods"),
            ("ia_methods", "synthesis_analysis"),
            ("synthesis_analysis", "influencing_with_evidence"),
        ],
        "phases": [
            {
                "title": "Foundations",
                "summary": "Learn to plan a study properly and ask neutral questions with consent and privacy built in, because bad questions and weak ethics ruin every later step.",
                "skill_key": "research_planning_ethics",
                "projects": [{
                    "title": "Write a research plan and consent form, repair a leading interview script and pilot it",
                    "teaches": "how to turn a vague question into a research plan, remove leading questions from a script and handle consent and privacy before you meet a participant.",
                    "prerequisites": ["A free Zoom or Google Meet account to record a call", "One friend or colleague willing to act as a pilot participant", "A topic you can ask ordinary people about, such as how they decide what to cook on a weeknight"],
                    "expected_output": "A one page research plan, a consent form, a rewritten neutral interview guide of eight to ten questions, and pilot session notes listing what you changed after the pilot.",
                    "steps": [
                        "Write the research question in one sentence (for example 'How do people decide what to cook on weeknights?') and say what decision the answer would inform.",
                        "Draft a one page research plan: background, goals, research questions, method, participants and how you will recruit them, schedule and risks.",
                        "Write a bad interview script of ten questions on purpose, including leading and closed ones such as 'Don't you find planning meals stressful?'.",
                        "Rewrite each question to be open and neutral (for example 'Tell me about the last time you decided what to cook'), and delete any that ask people to predict their future behaviour.",
                        "Write a consent form in plain language covering what you will record, who will see it, how long you will keep it, that taking part is voluntary and that they can stop at any time.",
                        "Decide how you will protect privacy: label participants P1, P2 and so on in notes, keep recordings in a restricted folder and set a deletion date.",
                        "Run a 20 minute pilot interview over Zoom, with the participant's permission to record, and note where questions confused them or led them.",
                        "Revise the guide and the plan from the pilot, and list at least three changes with the reason for each.",
                    ],
                    "hints": [
                        "Ask about past behaviour ('last time you...') rather than opinions or predictions; people are poor at predicting what they will do.",
                        "Use silence; wait a few seconds after an answer before moving on, because the useful detail often comes next.",
                        "Write the decision the research should inform at the top of the plan; if there is none, the study is probably not worth running.",
                        "Never promise anonymity you cannot deliver, and say what you will do with the recording in terms a participant would accept.",
                    ],
                    "common_mistakes": [
                        "Asking 'would you use...' questions and treating the answers as evidence of demand.",
                        "Burying key consent details in a long document or leaving out recording and retention.",
                        "Skipping the pilot and discovering the confusing questions in the first real session.",
                        "Writing a plan with no research question, so the study collects stories but answers nothing.",
                    ],
                    "difficulty": 1,
                }],
            },
            {
                "title": "Building Real Skills",
                "summary": "Use card sorting and tree testing to see how real people group content and find things, then turn the numbers into a recommended navigation structure.",
                "skill_key": "ia_methods",
                "projects": [{
                    "title": "Run a card sort and tree test on a public website's navigation and recommend a new structure",
                    "teaches": "how to evaluate information architecture with open card sorting and tree testing, read the results honestly and recommend a structure.",
                    "prerequisites": ["Completed a research plan and interview exercise", "A free or trial Optimal Workshop account, or Miro for a manual card sort", "A way to reach at least 15 volunteers, such as friends, a community group or a social media post", "A public website with a large menu, such as a library, council or university help section"],
                    "expected_output": "A short report with the card sort results (agreement between participants and the groupings), a proposed site structure, tree test results with task success and directness for five tasks, and the changes you would make after the tree test.",
                    "steps": [
                        "Choose a public site with a confusing navigation, audit it and list 30 to 40 content items that a visitor might need.",
                        "Write the research plan: what you want to learn, the method, how many participants, and the privacy and consent wording you will show them.",
                        "Set up an open card sort in OptimalSort (or Miro), with each content item as a card and instructions asking participants to group and name the groups.",
                        "Recruit at least 15 participants, send the link, and track how many complete it.",
                        "Analyse the results in the similarity matrix and dendrogram, find the groupings most people agree on and the cards that cause disagreement, and note the names people gave their groups.",
                        "Draft a new site structure with two levels, using the language participants used in their labels.",
                        "Set up a tree test in Treejack with the new structure and five realistic tasks (for example 'Find out how to renew a book online'), each with a correct answer.",
                        "Run the tree test with a new group of participants, record task success and directness for each task, and examine where people went wrong.",
                        "Write the report with your recommendations, and be clear about the sample size and what you can and cannot claim from it.",
                    ],
                    "hints": [
                        "Use the participants' words for labels; a name that a team invented rarely matches how people think.",
                        "Test with people who resemble the real visitors; a card sort with only your friends in the same job tells you about your friends.",
                        "Write tree test tasks as scenarios, never using the exact words in the menu labels, or you will measure word matching instead of understanding.",
                        "With a small sample, report patterns and direction instead of precise percentages.",
                    ],
                    "common_mistakes": [
                        "Using too many cards, so participants get tired and sort carelessly.",
                        "Writing tree test tasks that contain the label you hope participants will pick.",
                        "Presenting percentages from a very small sample as if they were precise.",
                        "Recommending a structure without testing it.",
                    ],
                    "difficulty": 3,
                }],
            },
            {
                "title": "Advanced Practice",
                "summary": "Combine several methods into one body of evidence, build a journey map where every claim is backed by data, and present it in a way that gets a decision.",
                "skill_key": "influencing_with_evidence",
                "projects": [{
                    "title": "Combine a diary study, survey and SUS score into an evidence-based journey map and decision readout",
                    "teaches": "how to triangulate diary, survey and interview data, calculate a SUS score, and present findings so a team makes a decision.",
                    "prerequisites": ["Completed the research plan and card sort projects", "Google Forms and Google Sheets", "A free Dovetail or Miro account for tagging and affinity mapping", "Five diary study participants and 20 or more survey respondents, such as students from a class or members of a club", "A topic such as how students plan and track their study time"],
                    "expected_output": "A research readout with the plan, the data from all three methods, a theme map showing the evidence behind each theme, a journey map in which each stage cites the data that supports it, a SUS score for an existing tool with a note on its limits, and ranked recommendations with a clear decision request.",
                    "steps": [
                        "Write a plan stating the research questions, the decision the study should inform, and consent and privacy wording for all three methods.",
                        "Run a 5-day diary study with five participants using a short Google Form sent daily (for example three questions about what they planned, what happened and what got in the way), and collect their entries.",
                        "Run a survey of 20 or more people in Google Forms with a mix of closed and open questions, and include the ten SUS statements for the planning tool they use now.",
                        "Hold four short follow-up interviews with diary participants, asking about the days that stand out in their entries.",
                        "Calculate each SUS score: for odd-numbered items subtract 1 from the response, for even-numbered items subtract the response from 5, add the results and multiply by 2.5, then average across respondents and note that the commonly cited average is about 68.",
                        "Tag the diary entries, open survey answers and interview notes in Dovetail or Miro, group them with affinity mapping into themes, and count how many participants support each theme.",
                        "Build a journey map from the data with stages, actions, thoughts, pain points and an opportunity row, and cite the evidence for each cell, leaving gaps empty rather than inventing detail.",
                        "Rank the findings by how often they happened and how much they hurt, and write five recommendations, each linked to its supporting evidence.",
                        "Prepare a 10 minute readout that opens with the decision you are asking for, present it to a friend playing a sceptical stakeholder, note their objections and revise.",
                    ],
                    "hints": [
                        "Treat a SUS score as a way to compare tools or versions with similar people, not as a verdict; a small group gives only a rough picture.",
                        "Where the diary and survey disagree, say so; the disagreement is often the most interesting finding.",
                        "Keep each recommendation tied to one finding, and say how confident you are and what would change your mind.",
                        "Put the ask first in the readout; sceptical stakeholders decide how much they trust the evidence before they hear it.",
                    ],
                    "common_mistakes": [
                        "Building personas or journey maps from assumption, with details no participant ever gave.",
                        "Reporting a SUS score without saying how many people answered or what product it describes.",
                        "Leaving the study at a list of findings, with no recommendation and no decision asked for.",
                        "Reading only the data that supports the idea you started with.",
                    ],
                    "difficulty": 5,
                }],
            },
        ],
    },
}
