"""New Cybersecurity careers, batch B: identity and access management, GRC, detection engineering."""

CAREERS = [
    dict(
        slug="identity-access-management", name="Identity and Access Management (IAM)",
        summary="Control who can sign in to what: create and remove accounts as people join and leave, set up single sign-on and MFA, grant the right access, and prove it to auditors.",
        beginner_summary="You'll learn how people and apps prove who they are, how access is granted and taken away, and how to set up sign-in for real services in a free lab.",
        difficulty=3, avg_timeline_weeks=28,
        entry_roles=["Junior IAM Analyst", "Identity and Access Administrator", "Access Management Analyst", "IT Support Analyst (identity focus)"],
        tools=["Microsoft Entra ID", "Active Directory", "Okta", "Keycloak", "PowerShell", "Postman"],
        remote_potential=75,
        earning_notes="Rarely a first job. Most people arrive from IT support or systems administration after they have handled real account requests, then move into an identity team at a larger organisation or a consultancy. Pay tends to move with hands-on depth in one major platform (Microsoft Entra ID or Okta), with privileged access and governance experience, and with a certification that matches the platform your employer uses.",
        icon="key",
        skills_required=[
            "Identity lifecycle management (joiner, mover, leaver)",
            "Authentication protocols (SAML, OAuth 2.0, OpenID Connect) and how to troubleshoot them",
            "Multi-factor authentication and passkey rollout",
            "Role based access design and least privilege",
            "Conditional access and privileged access policy design",
            "Access reviews and audit evidence",
        ],
        certifications=[
            "Microsoft Certified: Identity and Access Administrator Associate (SC-300)",
            "Microsoft Certified: Security, Compliance, and Identity Fundamentals (SC-900)",
            "Okta Certified Professional",
        ],
        interview_prep=[
            "Explain the difference between authentication and authorisation, and where SAML, OAuth 2.0 and OpenID Connect fit",
            "Someone leaves the company on a Friday afternoon. Walk through everything that should happen to their access and how you would prove it afterwards",
            "A user says MFA prompts keep failing after they replaced their phone. How do you help them without opening a hole for an attacker",
            "A manager asks you to copy a colleague's access onto a new contractor to save time. What do you do",
            "What does least privilege look like in practice for a team that keeps asking for admin rights",
            "An access review finds 40 stale accounts in a finance system. How do you remove them without breaking something",
        ],
        learning_resources=[
            {"label": "Microsoft Learn: SC-300 learning paths", "note": "Free, official modules on Microsoft Entra ID, conditional access, privileged identity management and access reviews."},
            {"label": "Keycloak documentation", "note": "The official guides for running Keycloak locally and configuring OpenID Connect, SAML and MFA."},
            {"label": "OAuth 2.0 Simplified by Aaron Parecki", "note": "A clear, free-to-read explanation of OAuth 2.0 flows and why each exists."},
        ],
        roadmap_outline={
            "beginner": [
                "Learn how authentication works: password hashing, MFA factors and passkeys",
                "Learn directory basics: users, groups, organisational units, and how Active Directory differs from Microsoft Entra ID",
                "Build a small Active Directory lab on a Windows Server evaluation VM and manage users and groups with PowerShell",
                "Learn the difference between authentication and authorisation, and the idea of least privilege",
            ],
            "intermediate": [
                "Create a free Microsoft Entra ID tenant and automate joiner, mover and leaver changes",
                "Learn OAuth 2.0, OpenID Connect and SAML well enough to read a login flow in your browser's developer tools",
                "Run Keycloak locally and connect a sample app with single sign-on",
                "Design role based access control for a fictional company and test that each role gets only what it should",
                "Learn SCIM provisioning and what an identity provider sends to an app when a user is created or disabled",
            ],
            "advanced": [
                "Design conditional access policies and test them in report-only mode before enforcing them",
                "Set up privileged access management: just in time elevation, approval and emergency access accounts",
                "Run an access review and collect the evidence an auditor would accept",
                "Study for SC-300 or the Okta Certified Professional exam using a trial tenant",
                "Learn how cloud resource policies fit with workforce identity, and review service accounts and API keys",
            ],
        },
    ),
    dict(
        slug="governance-risk-compliance", name="Governance, Risk and Compliance (GRC)",
        summary="The largely non-coding side of security: write policies, assess and track risk, map controls to frameworks like ISO/IEC 27001 and SOC 2, gather audit evidence and review vendors.",
        beginner_summary="You'll learn how organisations decide what security rules to follow, how to measure risk, and how to show an auditor that the rules are really being followed.",
        difficulty=2, avg_timeline_weeks=20,
        entry_roles=["Junior GRC Analyst", "Compliance Analyst", "IT Risk Analyst (junior)", "Security Compliance Associate"],
        tools=["Microsoft Excel", "Google Sheets", "ISO/IEC 27001", "NIST Cybersecurity Framework", "SOC 2", "PCI DSS", "Jira"],
        remote_potential=80,
        earning_notes="People get in from IT support, operations, project management, audit or compliance in a regulated industry, and from startups that need someone to run their first SOC 2 or ISO/IEC 27001 effort. ISACA certifications (CISA, CRISC, CISM) ask for several years of relevant experience, so they come after your first role rather than before. Pay tends to rise with the frameworks you have actually implemented or audited and with how well you can handle senior stakeholders.",
        icon="clipboard",
        skills_required=[
            "Writing clear, enforceable policies and standards",
            "Qualitative risk assessment and risk register upkeep",
            "Reading control frameworks (ISO/IEC 27001, SOC 2, NIST CSF) and mapping controls to them",
            "Collecting and organising audit evidence",
            "Third party and vendor risk review",
            "Explaining risk to non-technical people and getting teams to act on it",
        ],
        certifications=[
            "ISC2 Certified in Cybersecurity (CC)",
            "ISACA CISA (Certified Information Systems Auditor)",
            "ISACA CRISC (Certified in Risk and Information Systems Control)",
            "ISACA CISM (Certified Information Security Manager)",
            "ISO/IEC 27001 Lead Implementer or Lead Auditor (offered by several training bodies)",
        ],
        interview_prep=[
            "Explain the difference between a policy, a standard and a procedure, with an example of each",
            "What is the difference between ISO/IEC 27001 certification and a SOC 2 report, and when would a company want each",
            "Your company wants its first SOC 2 report in six months and has no formal security programme. Where do you start",
            "An engineering lead says a required control slows releases and wants to skip it. How do you respond",
            "A vendor that holds customer data returns a questionnaire with several vague answers. What do you do next",
            "What is the difference between inherent risk and residual risk, and how would you show the difference to a manager",
        ],
        learning_resources=[
            {"label": "NIST Cybersecurity Framework 2.0", "note": "The free official framework document plus quick start guides, a good map of what a security programme covers."},
            {"label": "AICPA Trust Services Criteria", "note": "The free criteria document that SOC 2 reports are written against, with points of focus for each criterion."},
            {"label": "ICO Guide to the UK GDPR", "note": "A free, plain English walkthrough of data protection principles, lawful bases and individual rights."},
        ],
        roadmap_outline={
            "beginner": [
                "Learn core security vocabulary: confidentiality, integrity, availability, threat, vulnerability, risk and control",
                "Read NIST Cybersecurity Framework 2.0 end to end and explain its six functions in your own words",
                "Learn how policies, standards, procedures and guidelines differ, and read three real public policies",
                "Get comfortable with spreadsheets: filters, lookups, conditional formatting and data validation",
                "Learn the basics of how companies are audited and what auditors mean by evidence",
            ],
            "intermediate": [
                "Write a policy set for a fictional company and map it to a framework",
                "Learn qualitative risk assessment: assets, threats, weaknesses, likelihood, impact and a risk register",
                "Read the structure of ISO/IEC 27001 (management system clauses and Annex A) and the SOC 2 Trust Services Criteria",
                "Learn the principles of GDPR: lawful basis, individual rights and records of processing",
                "Study for ISC2 Certified in Cybersecurity or CompTIA Security+ to prove baseline knowledge",
            ],
            "advanced": [
                "Build a control matrix and evidence request list for a SOC 2 or ISO/IEC 27001 readiness exercise",
                "Practise third party risk assessment: tiering vendors, sending questionnaires and chasing weak answers",
                "Learn what a GRC platform automates in evidence collection and what it cannot replace",
                "Practise explaining risk to non-technical leaders in a one page summary and a five minute briefing",
                "Choose a credential path: ISO/IEC 27001 Lead Implementer or Lead Auditor, or CISA, CRISC or CISM once you have the experience",
            ],
        },
    ),
    dict(
        slug="detection-engineering", name="Detection Engineering",
        summary="Build and maintain the detections the SOC responds to: write rules as code, test them against real attack behaviour, map coverage to MITRE ATT&CK and tune out false positives.",
        beginner_summary="You'll learn what attacks look like in logs, how to write rules that catch them in a SIEM, and how to test and improve those rules like software.",
        difficulty=4, avg_timeline_weeks=40,
        entry_roles=["SOC Analyst (Tier 2)", "Threat Detection Analyst", "SIEM Engineer (junior)", "Junior Detection Engineer (uncommon)"],
        tools=["Splunk", "Elastic Security (SIEM)", "Microsoft Sentinel", "Sigma", "MITRE ATT&CK", "Atomic Red Team", "Sysmon", "Git/GitHub"],
        remote_potential=70,
        earning_notes="Usually a step up rather than a first job: most detection engineers spent time as SOC analysts or security engineers first, and few employers advertise junior openings. The usual route is to start in a SOC or SIEM role, take on rule writing and tuning there, and show it with a public repository of tested detections. Pay tends to follow engineering depth (code, testing, one major SIEM) and the size of the environment you protect.",
        icon="radar",
        skills_required=[
            "Writing detection logic in Sigma and at least one SIEM query language (SPL, KQL or EQL)",
            "Knowing what attackers do on hosts and what traces it leaves in logs",
            "Mapping detections to MITRE ATT&CK and reasoning about coverage gaps",
            "Testing detections with adversary emulation such as Atomic Red Team",
            "Measuring and tuning false positives and alert quality",
            "Version control, code review and CI for detection content",
        ],
        certifications=[
            "GIAC Certified Detection Analyst (GCDA)",
            "Splunk Core Certified User",
            "Splunk Core Certified Power User",
            "Microsoft Certified: Security Operations Analyst Associate (SC-200)",
        ],
        interview_prep=[
            "Walk through how you would write a detection for scheduled task persistence, from the first log line to a deployed and documented rule",
            "A detection fires 400 times a day and analysts have started closing it without reading it. What do you do",
            "Leadership asks for coverage of every ATT&CK technique. How do you respond, and how would you report coverage honestly",
            "A purple team exercise shows your PowerShell rule missed an encoded variant. How do you fix it and prove the fix",
            "What would you check before trusting a new log source as the basis for a detection",
            "A log feed stops sending data and nobody notices for three days. How do you stop that happening again",
        ],
        learning_resources=[
            {"label": "MITRE ATT&CK website and ATT&CK Navigator", "note": "The free knowledge base of attacker techniques and the tool for drawing coverage maps."},
            {"label": "SigmaHQ rule repository and Sigma documentation", "note": "Thousands of free, community written detection rules and the specification for the Sigma format."},
            {"label": "Atomic Red Team documentation", "note": "Free, official guides and test library for running small, safe attack simulations in a lab."},
        ],
        roadmap_outline={
            "beginner": [
                "Learn Windows event logging and Sysmon: which event IDs record process creation, network connections and registry changes",
                "Pick one SIEM (Splunk trial or Elastic) and learn its query language until you can filter, aggregate and join without looking it up",
                "Read the ATT&CK matrix for Windows and learn ten common techniques well enough to say what each looks like in logs",
                "Write simple detections by hand and test them against public sample attack data",
            ],
            "intermediate": [
                "Learn the Sigma rule format and convert rules to your SIEM with sigma-cli",
                "Build a lab with Sysmon and run Atomic Red Team tests to see the telemetry behind each technique",
                "Move your rules into a Git repository with peer review and automated checks",
                "Learn a second query language (Microsoft Sentinel KQL or Elastic EQL) and port rules between platforms",
                "Map each detection to ATT&CK and build a coverage view that shows gaps honestly",
            ],
            "advanced": [
                "Measure each rule by alerts per day, false positive rate and what analysts did with the alerts, then tune",
                "Onboard and normalise a new log source end to end, including parsing and field mapping",
                "Run a purple team exercise and fix every miss with a new or changed detection",
                "Add log source health monitoring so a silent feed is noticed within minutes",
                "Write detection documentation and triage guidance an analyst can act on without asking you",
            ],
        },
    ),
]

META = {
    "identity-access-management": dict(
        keywords=[
            "iam", "identity and access management", "identity management", "access management", "iam analyst", "iam engineer",
            "identity engineer", "identity administrator", "sso", "single sign-on", "saml", "oauth", "oauth 2.0", "openid connect",
            "oidc", "mfa", "multi-factor authentication", "passkeys", "entra id", "azure ad", "active directory", "okta", "keycloak",
            "rbac", "privileged access management", "pam", "scim", "conditional access", "access review", "identity governance",
            "joiner mover leaver", "sc-300",
        ],
        who_its_for="People who like process, detail and systems that touch everyone in a company. It is rarely a first job, because most people arrive from IT support or systems administration with some admin experience. The catch is that mistakes either lock people out or leave a door open, so the work needs patience and careful change control.",
        portfolio_expectations=[
            "A joiner, mover and leaver process for a fictional company, with the automation script and test results",
            "A working single sign-on setup using OpenID Connect and SAML in Keycloak or Okta, with a diagram of each login flow",
            "A set of conditional access and privileged access policies with the reasoning for each, tested in report-only mode",
            "An access review pack showing who had what, who approved or removed it, and the evidence an auditor would ask for",
        ],
        career_progression=[
            "Junior IAM Analyst or Identity Administrator",
            "IAM Engineer",
            "Senior IAM Engineer",
            "Identity Architect or IAM Programme Lead",
        ],
    ),
    "governance-risk-compliance": dict(
        keywords=[
            "grc", "governance risk and compliance", "governance risk compliance", "compliance analyst", "risk analyst", "it risk",
            "iso 27001", "iso/iec 27001", "iso27001", "soc 2", "soc2", "nist csf", "pci dss", "gdpr", "it audit", "security compliance",
            "information security compliance", "risk register", "risk assessment", "vendor risk", "third party risk", "tprm",
            "security policy", "cisa", "crisc", "cism", "isms", "audit evidence", "security awareness",
        ],
        who_its_for="Suits people who write, organise and persuade more than people who code: you will spend your days in documents, spreadsheets and meetings rather than a terminal. It rewards attention to detail, fairness when you have to tell a team their control does not work, and the ability to explain risk to non-technical leaders. The catch is that it can feel like paperwork, and it only matters if you can get people to follow the controls.",
        portfolio_expectations=[
            "A policy set (information security, acceptable use, access control) written for a fictional company, with version history",
            "A risk register with a scoring method, a treatment plan and a one page summary for leadership",
            "A control matrix mapping controls to SOC 2 or ISO/IEC 27001 requirements, with an evidence request list",
            "A vendor risk assessment of fictional suppliers with a tiering method and written findings",
        ],
        career_progression=[
            "Junior GRC Analyst or Compliance Analyst",
            "GRC Analyst or IT Risk Analyst",
            "Senior GRC Analyst, IT Auditor or Security Compliance Manager",
            "GRC Manager, Head of Risk and Compliance, or CISO with wider security experience",
        ],
    ),
    "detection-engineering": dict(
        keywords=[
            "detection engineer", "detection engineering", "detection as code", "siem", "sigma", "sigma rules", "splunk", "spl",
            "elastic", "elastic security", "kql", "eql", "microsoft sentinel", "mitre att&ck", "att&ck", "atomic red team",
            "purple team", "threat detection", "detection rules", "sysmon", "use case development", "log source onboarding",
            "alert tuning", "false positive tuning", "sc-200", "gcda",
        ],
        who_its_for="People who enjoy investigations but would rather build the system that finds attacks than work the alert queue. You need comfort with logs, query languages and Git, and a habit of testing your own work. It is usually a step up from a SOC analyst or security engineering role, so expect to start in one of those and use detection work inside it to make the case for a move.",
        portfolio_expectations=[
            "A Git repository of detections in Sigma format, each with an ATT&CK mapping, a test and false positive notes",
            "An ATT&CK Navigator coverage layer that separates techniques you have tested from ones you have only written rules for",
            "A tuning write-up showing alert volume before and after, and proof the rule still catches the attack",
            "A purple team report listing each technique run, whether it was detected, and the fix for each miss",
        ],
        career_progression=[
            "SOC Analyst or SIEM Engineer",
            "Detection Engineer",
            "Senior Detection Engineer",
            "Detection Engineering Lead or Principal Detection Engineer",
        ],
    ),
}

PROJECTS = {
    "identity-access-management": {
        "skills": [
            {"key": "identity_lifecycle", "label": "Identity Lifecycle Management", "category": "foundation"},
            {"key": "authentication_and_mfa", "label": "Authentication and MFA", "category": "foundation"},
            {"key": "federation_and_sso", "label": "Federation and Single Sign-On", "category": "core"},
            {"key": "authorisation_and_rbac", "label": "Authorisation and Role Based Access", "category": "core"},
            {"key": "privileged_access_and_governance", "label": "Privileged Access and Access Governance", "category": "advanced"},
        ],
        "skill_edges": [
            ("identity_lifecycle", "authentication_and_mfa"),
            ("authentication_and_mfa", "federation_and_sso"),
            ("federation_and_sso", "authorisation_and_rbac"),
            ("authorisation_and_rbac", "privileged_access_and_governance"),
        ],
        "phases": [
            {
                "title": "Foundations",
                "summary": "Learn the heart of identity work, the account lifecycle, by automating joiners, movers and leavers in a free Microsoft Entra ID tenant.",
                "skill_key": "identity_lifecycle",
                "projects": [
                    {
                        "title": "Automate joiner, mover and leaver changes in a free Microsoft Entra ID tenant",
                        "teaches": "how an HR record turns into an account, group memberships and, eventually, a disabled account, and why the leaver step is the one auditors check hardest",
                        "prerequisites": ["Basic comfort running commands in PowerShell", "A free Microsoft account to sign up for a tenant"],
                        "expected_output": "A PowerShell script that reads an HR CSV and creates, moves and disables users in your Entra ID tenant, a CSV audit log of every change it made, and a one page leaver checklist covering systems the script cannot reach.",
                        "steps": [
                            "Invent the company: Fernbrook Supplies, 12 staff across Sales, Finance and Support. Create hr_feed.csv with the columns employee_id, display_name, department, job_title, manager, start_date and status (new, active or left), and fill in 12 rows.",
                            "Create a free tenant: sign up for a free Azure account, open the Microsoft Entra admin center and note the initial domain ending in .onmicrosoft.com.",
                            "In the admin center, create three security groups (Sales, Finance, Support) and one group named app-crm-users, then create two users by hand so you see every field the script will later fill in.",
                            "Install the Microsoft Graph PowerShell SDK with `Install-Module Microsoft.Graph -Scope CurrentUser`, then run `Connect-MgGraph -Scopes \"User.ReadWrite.All\",\"Group.ReadWrite.All\"` and approve the consent prompt.",
                            "Joiner: for each row with status new, call `New-MgUser` with a generated temporary password and ForceChangePasswordNextSignIn set to true, then `New-MgGroupMember` to add the user to the group matching their department.",
                            "Mover: change one person's department in the CSV. Make the script remove them from the old group with `Remove-MgGroupMemberByRef`, add them to the new one and update the department with `Update-MgUser`.",
                            "Leaver: for rows with status left, run `Update-MgUser -AccountEnabled:$false`, then `Revoke-MgUserSignInSession`, then remove the user from every group. Disable first; do not delete.",
                            "Write each action to audit_log.csv with timestamp, employee_id, action, result and error text. Run the script twice and confirm the second run changes nothing, then compare your log with the Audit logs page in the admin center.",
                            "Write a one page leaver checklist for everything the script cannot touch (mailbox, shared drives, SaaS accounts, laptop, API tokens), with a named owner role for each item.",
                        ],
                        "hints": [
                            "Disable first and delete later: a disabled account keeps its history and can be switched back on if HR made a mistake.",
                            "Match people on employee_id, never on display name.",
                            "Run the script against a single test row first and check the result in the admin center before running the whole file.",
                            "Dynamic group membership needs a paid licence, so assign group membership in the script on the free tier.",
                        ],
                        "common_mistakes": [
                            "Writing temporary passwords into the CSV or the audit log.",
                            "Matching on display name, which breaks as soon as two people share one.",
                            "Disabling the account but not revoking sessions, so existing tokens keep working for a while.",
                            "Testing on your own admin account and locking yourself out of the tenant.",
                        ],
                        "difficulty": 1,
                    }
                ],
            },
            {
                "title": "Building Real Skills",
                "summary": "Learn how applications trust an identity provider by wiring up OpenID Connect, SAML and MFA yourself and reading what actually travels between browser, app and provider.",
                "skill_key": "federation_and_sso",
                "projects": [
                    {
                        "title": "Add single sign-on and MFA to two test apps with Keycloak using OpenID Connect and SAML",
                        "teaches": "how the authorisation code flow with PKCE and a SAML assertion each carry identity to an app, and how to troubleshoot them when they fail",
                        "prerequisites": ["Docker installed on your laptop", "The joiner, mover and leaver project, or comfort creating users and groups in a directory", "Postman (free account) and a browser with developer tools"],
                        "expected_output": "A running Keycloak realm with role based users, one OpenID Connect client and one SAML client both signing in successfully, MFA enforced, a troubleshooting table of five deliberate failures, and a sequence diagram of each flow.",
                        "steps": [
                            "Run Keycloak locally: `docker run -p 8080:8080 -e KC_BOOTSTRAP_ADMIN_USERNAME=admin -e KC_BOOTSTRAP_ADMIN_PASSWORD=change-me quay.io/keycloak/keycloak:<version> start-dev`, using a version number from the Keycloak site. Open http://localhost:8080 and sign in to the admin console.",
                            "Create a realm named fernbrook. Add realm roles sales-user, finance-approver and support-agent, create five test users and assign each one a role.",
                            "Create an OpenID Connect client with the standard flow (authorisation code) on and PKCE method S256 required. Set the valid redirect URI to https://oauth.pstmn.io/v1/callback so Postman can act as the app.",
                            "In Postman, open the Authorization tab, choose OAuth 2.0 with grant type Authorization Code (With PKCE), and use the auth and token endpoints from http://localhost:8080/realms/fernbrook/.well-known/openid-configuration. Sign in as a test user and get a token.",
                            "Decode the ID token and the access token (jwt.io or `cut -d. -f2 | base64 -d`) and write down iss, aud, sub, exp and the realm_access.roles claim. Note which token says who signed in and which one says what the app may call.",
                            "Create a SAML client for SAMLtest (samltest.id): import SAMLtest's service provider metadata into Keycloak, upload Keycloak's IdP metadata from /realms/fernbrook/protocol/saml/descriptor to SAMLtest, and sign in. Use the SAML-tracer browser extension to read the assertion and add a role attribute mapper.",
                            "Enforce MFA: add the Configure OTP required action to the test users, set the browser flow to require OTP, and enrol an authenticator app. Then enable the WebAuthn Passwordless policy and register a passkey if your device supports it.",
                            "Break it on purpose five ways (wrong redirect URI, user with no role, expired token, wrong clock, disabled user). For each, record the exact error, the cause and the fix in a troubleshooting table.",
                            "Draw a sequence diagram for each flow in draw.io, marking which steps go through the browser (front channel) and which are direct calls between app and Keycloak (back channel).",
                        ],
                        "hints": [
                            "In the authorisation code flow the browser only carries a short-lived code; the token comes back over a direct call from the app.",
                            "start-dev is for labs only: it uses relaxed settings, so never expose it to the internet.",
                            "SAML is strict about time, so if sign-in fails with a timing error, check your machine's clock first.",
                            "Use a private browser window for each test so an old session does not hide your mistake.",
                        ],
                        "common_mistakes": [
                            "Using a wildcard redirect URI instead of the exact address.",
                            "Confusing the ID token (who signed in) with the access token (what the app may call).",
                            "Treating a decoded token as proof it is valid, when an app must verify the signature against the provider's keys.",
                            "Testing MFA only with the admin account, which may be exempt.",
                        ],
                        "difficulty": 3,
                    }
                ],
            },
            {
                "title": "Advanced Practice",
                "summary": "Do what mature identity teams do: enforce conditional access safely, make admin rights temporary, and run an access review that leaves evidence an auditor can use.",
                "skill_key": "privileged_access_and_governance",
                "projects": [
                    {
                        "title": "Design conditional access, just in time admin rights and a quarterly access review for a fictional 40 person company, with audit evidence",
                        "teaches": "how to roll out access controls without locking people out, and how to produce the population, sample and result an auditor asks for",
                        "prerequisites": ["The Entra ID tenant from the joiner, mover and leaver project", "Comfort with groups and role assignments", "A willingness to start a time limited trial only when you are ready to finish the project"],
                        "expected_output": "Conditional access policies tested in report-only mode, a just in time privileged role assignment with approval, a completed access review with exported results, and an evidence pack where each item is dated and tied to a control statement.",
                        "steps": [
                            "Grow Fernbrook Supplies to 40 staff and write a one page requirements note: which groups need the finance system, who may hold admin roles, which sign-ins must always use MFA.",
                            "Start the Microsoft Entra ID P2 trial in your tenant (check the current trial length first) and add the 40 users and group memberships with your script from the first project.",
                            "Create two emergency access accounts: cloud-only, long random passwords stored offline, permanent Global Administrator. Write a procedure that any sign-in by these accounts is reviewed the same day.",
                            "Turn off security defaults, then create conditional access policies in report-only mode: require MFA for administrator roles, require MFA for all users, and block legacy authentication. Exclude the emergency accounts from all three.",
                            "Use the What If tool for five scenarios, sign in a few times as test users, and read the Conditional Access tab of the sign-in logs to see what each policy would have done. Enforce the admin MFA policy only once you have checked that the emergency accounts still work.",
                            "In Privileged Identity Management, make User Administrator eligible rather than permanent for one test admin: one hour activation, justification required, approval by a second person. Activate it and find the entries in the PIM audit history.",
                            "Create an access review of the Finance group with the group owner as reviewer, quarterly recurrence and 14 days to respond. Seed it first with three disabled or long-idle accounts and two users who changed department.",
                            "Complete the review as the reviewer, apply the results, and export the review results and the group membership before and after.",
                            "Build the evidence pack: for each control statement (for example 'Privileged roles are assigned just in time with approval') include a dated screenshot, the exported policy JSON or review CSV, who performs the check and how often. Export everything before the trial ends.",
                        ],
                        "hints": [
                            "Report-only mode shows what a policy would have done without blocking anyone, and it is the normal way to roll a policy out.",
                            "Keep one admin session open in a different browser while you test, in case a policy locks you out.",
                            "Export policies as JSON from the portal or Microsoft Graph so the evidence outlives the trial.",
                            "Auditors want the population, the sample and the result. Save all three, not just a screenshot of the result.",
                        ],
                        "common_mistakes": [
                            "Forgetting to exclude the emergency accounts from policies, or never testing that they work.",
                            "Enforcing a policy straight away instead of running it in report-only mode first.",
                            "Granting permanent admin rights 'just for now' and never taking them back.",
                            "Collecting screenshots with no date, tenant name or note of what they prove.",
                        ],
                        "difficulty": 5,
                    }
                ],
            },
        ],
    },
    "governance-risk-compliance": {
        "skills": [
            {"key": "policy_and_standards_writing", "label": "Policy and Standards Writing", "category": "foundation"},
            {"key": "control_frameworks", "label": "Control Frameworks", "category": "foundation"},
            {"key": "risk_assessment", "label": "Risk Assessment and Registers", "category": "core"},
            {"key": "audit_and_evidence", "label": "Audit Support and Evidence Collection", "category": "core"},
            {"key": "third_party_risk_and_privacy", "label": "Third Party Risk and Privacy", "category": "advanced"},
        ],
        "skill_edges": [
            ("policy_and_standards_writing", "control_frameworks"),
            ("control_frameworks", "risk_assessment"),
            ("risk_assessment", "audit_and_evidence"),
            ("audit_and_evidence", "third_party_risk_and_privacy"),
        ],
        "phases": [
            {
                "title": "Foundations",
                "summary": "Learn how security rules are written down by inventing a small company, listing what it must protect and writing the policies that govern it.",
                "skill_key": "policy_and_standards_writing",
                "projects": [
                    {
                        "title": "Write a policy set and asset register for Larkfield Clinic Software, a fictional 35 person company",
                        "teaches": "how to turn a company's real situation into short, enforceable policies and how the policy, standard and procedure layers fit together",
                        "prerequisites": ["Basic spreadsheet skills", "Free access to the NIST Cybersecurity Framework 2.0 document", "A word processor or document editor"],
                        "expected_output": "A company profile, an asset register of at least 25 assets, a data classification standard, three policies and one staff incident reporting procedure, each with an owner and version history, plus a table mapping policy statements to NIST CSF 2.0 functions.",
                        "steps": [
                            "Define the company in a half page profile. Larkfield Clinic Software has 35 staff (14 engineers, 6 in support, 5 in sales, 4 in operations and finance, 6 in management and other roles), sells appointment scheduling software to physiotherapy clinics, stores patient names and appointment times, runs on a public cloud provider, uses a cloud office suite, about 12 SaaS vendors, and has no security team (the CTO covers security part time).",
                            "Build the asset register in a spreadsheet with the columns ID, asset, type, owner, data classification, location and business criticality (1 to 3). List at least 25 assets, such as the customer database, source code repository, laptops, payroll system and the office suite.",
                            "Write a one page data classification standard with four levels (Public, Internal, Confidential, Restricted) and, for each level, rules for storing, sharing and disposing of data. Classify every asset in the register.",
                            "Decide which documents you need and where each belongs: policy (what and why, short, approved by leadership), standard (specific rules), procedure (steps) and guideline (advice). Sketch the hierarchy as a table.",
                            "Write three policies: Information Security Policy, Acceptable Use Policy and Access Control Policy. Give each the same sections: purpose, scope, numbered policy statements, roles and responsibilities, exceptions, enforcement, owner, version and review date.",
                            "Write a two page incident reporting procedure for all staff: what to report (a lost laptop, a strange email), how, to whom, and how quickly.",
                            "Map every policy statement to a NIST CSF 2.0 function (Govern, Identify, Protect, Detect, Respond, Recover) in a table and note which functions are thin.",
                            "Ask a non-technical friend to read the Acceptable Use Policy and say what they would do in three scenarios. Rewrite every sentence where they guessed wrong.",
                            "Add an approval block and version history to each document, store them in a folder structure that mirrors your hierarchy, and write an annual review calendar naming who reviews what.",
                        ],
                        "hints": [
                            "A policy says what must be true and who is responsible; put tool settings in standards or procedures.",
                            "Use 'must' for rules you will enforce and 'should' only where you will accept exceptions.",
                            "NIST CSF 2.0 is free to download, and its Govern function is a good guide to what leadership should own.",
                            "Write the shortest policy that is still enforceable. Few people read a 30 page policy.",
                        ],
                        "common_mistakes": [
                            "Copying a template word for word, including promises the company does not keep, which later becomes an audit finding.",
                            "Writing rules the company cannot follow in practice.",
                            "Leaving owner, version and review date blank.",
                            "Mixing policy, procedure and tool settings into one long document.",
                        ],
                        "difficulty": 1,
                    }
                ],
            },
            {
                "title": "Building Real Skills",
                "summary": "Learn the core analytical skill of GRC: turning vague worries into scored, owned risks with a treatment plan that a leadership team can decide on.",
                "skill_key": "risk_assessment",
                "projects": [
                    {
                        "title": "Run a risk assessment and build a scored risk register with a treatment plan for Larkfield Clinic Software",
                        "teaches": "how to define a scoring method, write risks as proper statements, separate inherent from residual risk, and present decisions to leadership",
                        "prerequisites": ["The asset register from the policy project (Larkfield Clinic Software, 35 staff, scheduling software for physiotherapy clinics)", "Spreadsheet skills including conditional formatting"],
                        "expected_output": "A spreadsheet risk register with at least 15 risks, written scoring scales, inherent and residual scores, treatments with owners and dates, a 5 by 5 heat map, and a one page leadership summary naming the top five risks and decisions needed.",
                        "steps": [
                            "Reopen the Larkfield asset register and pick the eight most critical assets (customer database, production environment, source code, staff laptops, payroll, and so on).",
                            "Write your scoring method before you score anything: likelihood 1 to 5 with a written description for each level, impact 1 to 5 across financial, legal, customer and operational harm, score equals likelihood times impact, and bands (1 to 4 low, 5 to 9 medium, 10 to 16 high, 17 to 25 critical).",
                            "Identify at least 15 risks, each written as a full statement: threat, weakness, consequence. For example, a phished engineer's credentials let an attacker reach the production database and expose patient appointment data.",
                            "Build the register with these columns: ID, risk statement, asset, owner, existing controls, inherent likelihood, inherent impact, inherent score, residual likelihood, residual impact, residual score, treatment, action, due date, status and scoring rationale.",
                            "Score every risk first as if no controls existed (inherent), then with only the controls that already exist and work (residual). Have a second person, or yourself a day later, challenge the five highest scores against your written scales.",
                            "Choose a treatment for each risk (mitigate, accept, transfer or avoid). For the top five, write a specific action with a named owner and date. For any accepted risk, write an acceptance statement and name who signs it.",
                            "Draw a 5 by 5 heat map with conditional formatting and count how many risks fall in each band before and after treatment.",
                            "Map each risk to at least one control in NIST CSF 2.0 or in ISO/IEC 27001 Annex A (free summaries of the control titles are widely published, so buying the standard is not needed for this exercise).",
                            "Write a one page summary for the leadership team: the top five risks in plain language, the decisions you need from them, what happens if nothing changes, and a short risk appetite statement they could approve.",
                        ],
                        "hints": [
                            "Write the scale descriptions first, or every score becomes an opinion.",
                            "A risk is a possible event with a consequence. 'No MFA' is a weakness, not a risk.",
                            "Residual risk should drop only for controls that exist and work today, not for ones you plan to add.",
                            "Give every risk a named person as owner. A team is not an owner.",
                        ],
                        "common_mistakes": [
                            "Scoring everything medium so that nothing stands out.",
                            "Listing weaknesses or tasks as if they were risks.",
                            "Reducing residual scores for controls that are only planned.",
                            "Building a register so long that nobody reads past the first screen.",
                        ],
                        "difficulty": 3,
                    }
                ],
            },
            {
                "title": "Advanced Practice",
                "summary": "Practise the work that fills a GRC analyst's calendar before an audit: scoping, control matrices, evidence requests, vendor reviews and an honest gap report.",
                "skill_key": "audit_and_evidence",
                "projects": [
                    {
                        "title": "Prepare Larkfield Clinic Software for a SOC 2 Type I readiness review: control matrix, evidence requests, vendor risk and gap report",
                        "teaches": "how readiness work is organised before an auditor arrives, how to collect evidence that proves a control, and how to review a supplier's answers critically",
                        "prerequisites": ["The policy set and risk register for Larkfield Clinic Software from the earlier projects", "Free access to the AICPA Trust Services Criteria document", "Your own free accounts (for example a personal code hosting account and email account) to produce stand-in evidence"],
                        "expected_output": "A scoped system description, a control matrix mapped to the Security criteria, an evidence request list, a small evidence folder where each item is labelled, a vendor tiering and review of three fictional suppliers, a mini record of processing activities, and a gap report with owners and dates.",
                        "steps": [
                            "Write a one page system description for Larkfield Clinic Software (its scheduling product, infrastructure, people, data and the vendors it relies on) and state the scope: the Security category only, as at a single date (Type I).",
                            "Build a control matrix in a spreadsheet: one row per control, with the control description, owner, frequency and the matching Common Criteria group (CC1 control environment through CC9 risk mitigation). Write at least 25 controls, drawing on your earlier policies and risk treatments.",
                            "Write an evidence request list (what auditors often call a PBC list): for each control, the evidence an auditor would ask for, who provides it, and the date range it must cover.",
                            "Collect stand-in evidence from your own accounts, such as a screenshot of MFA settings or branch protection on a personal repository. Label each item with date, source, who collected it, and the control it supports. Write down honestly which controls you have no evidence for.",
                            "Build a vendor tiering method (for example Tier 1 holds customer data or is critical to service, Tier 3 holds neither) and tier 8 fictional vendors. Write a 20 question security questionnaire for Tier 1 vendors.",
                            "Invent answers from three fictional Tier 1 vendors, making some vague or missing on purpose. Review them, write a follow-up question for every weak answer and record a finding with a risk rating.",
                            "Draft a mini record of processing activities in the style of GDPR Article 30 for Larkfield's three main data uses (customer accounts, appointment data, support tickets): purpose, data categories, lawful basis, who receives it, retention period.",
                            "Write the gap report: every control without evidence or with a weak design becomes a finding with severity, owner, remediation action and target date. Track the findings in a Jira board or a spreadsheet.",
                            "Write a one page executive summary and rehearse a ten minute walkthrough, including answers to the questions an auditor would ask about your three weakest controls.",
                        ],
                        "hints": [
                            "A real SOC 2 report is issued by a licensed CPA firm; your exercise is readiness work, and you should say so in your write-up.",
                            "Evidence should be dated, show its source, and be tied to a specific control. A screenshot with no context proves very little.",
                            "Ask vendors for evidence, such as a recent audit report or policy summary, rather than accepting a yes or no.",
                            "It is better to report an honest gap with a plan than to write a control that you cannot show operating.",
                        ],
                        "common_mistakes": [
                            "Writing controls that describe what the company hopes to do rather than what it does.",
                            "Collecting evidence that shows a setting but not that it applied across the whole population.",
                            "Treating all vendors the same instead of tiering by data and criticality.",
                            "Leaving gaps without an owner or date, so the gap report is never acted on.",
                        ],
                        "difficulty": 5,
                    }
                ],
            },
        ],
    },
    "detection-engineering": {
        "skills": [
            {"key": "log_sources_and_telemetry", "label": "Log Sources and Telemetry", "category": "foundation"},
            {"key": "detection_rule_writing", "label": "Detection Rule Writing", "category": "foundation"},
            {"key": "attack_mapping_and_validation", "label": "ATT&CK Mapping and Validation", "category": "core"},
            {"key": "detection_as_code", "label": "Detection as Code", "category": "core"},
            {"key": "tuning_and_purple_teaming", "label": "Tuning and Purple Teaming", "category": "advanced"},
        ],
        "skill_edges": [
            ("log_sources_and_telemetry", "detection_rule_writing"),
            ("detection_rule_writing", "attack_mapping_and_validation"),
            ("attack_mapping_and_validation", "detection_as_code"),
            ("detection_as_code", "tuning_and_purple_teaming"),
        ],
        "phases": [
            {
                "title": "Foundations",
                "summary": "Learn what a detection is by writing one in Sigma, running it as a Splunk search on public attack data, and seeing how the same logic changes across SIEM platforms.",
                "skill_key": "detection_rule_writing",
                "projects": [
                    {
                        "title": "Write a Sigma rule for scheduled task creation, run it as SPL on public attack data, then port it to Elastic and Sentinel",
                        "teaches": "the structure of a Sigma rule, how it converts into a SIEM query, and why field names and matching behaviour differ between platforms",
                        "prerequisites": ["Basic Windows and command line comfort", "Python 3 and pip installed", "A free Splunk account to download the Splunk Enterprise trial"],
                        "expected_output": "One Sigma rule file with ATT&CK tags and false positive notes, the converted SPL running against a public dataset with a list of hits you judged, converted queries for Elastic and Microsoft Sentinel, and a table comparing the field names across the three platforms.",
                        "steps": [
                            "Install the Splunk Enterprise trial on your laptop or a VM, sign in at http://localhost:8000 and create an index named lab (Settings, Indexes).",
                            "Get data: from the Splunk attack_data repository on GitHub, find the attack_techniques folder for T1053.005 (scheduled task) and download a Windows Sysmon log file. Upload it with Settings, Add Data, Upload into the lab index.",
                            "Explore it with `index=lab | stats count by EventCode`, then look at the process creation events (EventCode 1) and note the fields Image, CommandLine, ParentImage and User.",
                            "Read two existing Sigma rules for process creation in the SigmaHQ repository. List the sections: title, id, status, description, references, author, date, tags, logsource, detection, falsepositives and level.",
                            "Write your own rule file with a new UUID (`python3 -c \"import uuid; print(uuid.uuid4())\"`). Select Image ending with \\schtasks.exe and CommandLine containing /create, tag it attack.persistence and attack.t1053.005, and fill in falsepositives honestly.",
                            "Install the converter: `pip install sigma-cli`, `sigma plugin install splunk`, then `sigma list pipelines` to find the Splunk and Sysmon pipeline names. Run `sigma convert -t splunk -p <pipeline> your_rule.yml` and paste the result into Splunk's search bar.",
                            "Review every hit: parent process, user and command line. Write down which hits look like normal software installers and which look suspicious, and why.",
                            "Install the Elasticsearch and Kusto plugins with `sigma plugin install`, run `sigma list targets`, and convert the same rule for an Elastic query and for Microsoft Sentinel KQL.",
                            "Make a comparison table: how each platform names the process path and command line (Splunk Image and CommandLine, Elastic ECS process.executable and process.command_line, Sentinel DeviceProcessEvents FolderPath and ProcessCommandLine), and note any difference in case sensitivity or wildcard behaviour you noticed.",
                        ],
                        "hints": [
                            "Sysmon event ID 1 records process creation, so Windows process creation rules usually depend on it, or on Security event 4688 with command line auditing turned on.",
                            "Start from an existing SigmaHQ rule and edit it. You learn the format faster than from reading the specification.",
                            "Generate a fresh UUID for every rule and never reuse one.",
                            "Run the converted query yourself. A conversion that runs without errors can still match nothing if the field names are wrong.",
                        ],
                        "common_mistakes": [
                            "Using a field your log source does not have, so the query silently matches nothing.",
                            "Matching only on schtasks.exe with no command line condition, so every task query raises an alert.",
                            "Skipping the false positives section because the rule appears to work.",
                            "Assuming matching is case sensitive (or not) in every platform without testing it.",
                        ],
                        "difficulty": 1,
                    }
                ],
            },
            {
                "title": "Building Real Skills",
                "summary": "Treat detections as code: generate real attack telemetry with Atomic Red Team in a lab, write tested rules, run checks in CI and publish an honest ATT&CK coverage map.",
                "skill_key": "detection_as_code",
                "projects": [
                    {
                        "title": "Build a detection as code repository: Sysmon lab, five Atomic Red Team tests, Sigma rules, CI checks and an ATT&CK Navigator coverage layer",
                        "teaches": "how to prove a detection works against real attack behaviour, how to keep rules in version control with automated checks, and how to report coverage without overclaiming",
                        "prerequisites": ["The Sigma and Splunk basics from the foundations project", "A hypervisor (VirtualBox or Hyper-V) with room for a Windows VM", "A free GitHub account and basic Git"],
                        "expected_output": "A GitHub repository with five tested Sigma rules, a tests folder recording each Atomic Red Team run and its result, a GitHub Actions workflow that checks and converts every rule, and an ATT&CK Navigator layer showing tested techniques.",
                        "steps": [
                            "Create an isolated Windows VM from the Microsoft Evaluation Center image with a host-only network, take a clean snapshot, and install Sysmon with a community configuration such as SwiftOnSecurity's sysmon-config: `sysmon64.exe -accepteula -i sysmonconfig-export.xml`.",
                            "Install Splunk Enterprise (the 60 day trial, because the Free licence cannot run alerts) on your host, create an index named sysmon, install the Splunk Add-on for Sysmon, and install the Universal Forwarder on the VM with an inputs.conf stanza for WinEventLog://Microsoft-Windows-Sysmon/Operational. Confirm data with `index=sysmon | stats count by EventCode`.",
                            "Install Invoke-AtomicRedTeam in the VM (`Install-Module -Name invoke-atomicredteam`) and the atomics folder as its documentation describes. Take a second snapshot.",
                            "Run five techniques one at a time, using `Invoke-AtomicTest <id> -ShowDetailsBrief` to choose a test: T1053.005 scheduled task, T1136.001 local account creation, T1547.001 registry run key, T1059.001 PowerShell and T1218.011 rundll32. Note the exact time of each run, then run `-Cleanup`.",
                            "For each run, find the telemetry in Splunk and record which Sysmon event IDs and fields show the behaviour. Create a GitHub repository with folders rules/windows, tests and docs.",
                            "Write one Sigma rule per technique with an id, status, ATT&CK tags, level and falsepositives. Convert each with sigma-cli to SPL, run it over the matching time window, and record in the matching tests/ file whether it fired.",
                            "Add a GitHub Actions workflow that runs on every pull request: install sigma-cli, run `sigma check rules/` and convert every rule to the Splunk target, failing the build on any error. Open a pull request that breaks a rule on purpose to confirm the check fails.",
                            "Create an ATT&CK Navigator layer file (JSON) that scores only techniques with a passing test, and render it in Navigator. Add a coverage table to the README that lists technique, rule, log source, date last tested and result.",
                            "Revert the VM to the clean snapshot and write a short README section explaining how someone else could reproduce your lab and your tests.",
                        ],
                        "hints": [
                            "Run `sigma list pipelines` and `sigma list targets` after installing a plugin to see the exact names to pass to `sigma convert`.",
                            "Snapshot the VM before the first atomic and revert after each session so every test starts from a known state.",
                            "Microsoft Defender will block many atomics. In a throwaway VM on a host-only network, follow the Atomic Red Team documentation for exclusions, and never do this on your main computer.",
                            "Record the exact time each atomic ran so you can search a narrow window and avoid matching the wrong events.",
                        ],
                        "common_mistakes": [
                            "Running attack simulations on your everyday computer instead of an isolated VM.",
                            "Writing the rule from the technique description and never checking what your lab's logs actually contain.",
                            "Skipping -Cleanup, so leftover accounts and tasks pollute later tests.",
                            "Marking a technique as covered on the Navigator layer when its rule was never tested.",
                        ],
                        "difficulty": 3,
                    }
                ],
            },
            {
                "title": "Advanced Practice",
                "summary": "Do the part of the job that separates detection engineers from rule writers: measure and tune false positives, document rules for analysts, and fix misses found by a purple team exercise.",
                "skill_key": "tuning_and_purple_teaming",
                "projects": [
                    {
                        "title": "Tune a noisy rule set against a benign baseline and run a purple team exercise with before and after metrics",
                        "teaches": "how to cut false positives without blinding a rule, how to find the gaps an attacker variation exposes, and how to onboard a missing log source to close them",
                        "prerequisites": ["The lab, rules repository and CI from the detection as code project", "Comfort with SPL aggregation (stats, eventstats, tstats)", "An isolated Windows VM with Sysmon and a Splunk Enterprise trial still running"],
                        "expected_output": "A tuning report with alert counts per rule before and after, a documented rule set with triage guidance, a purple team report listing detected, missed and fixed results, updated rules in the repository, and a log source health alert that you tested by stopping the forwarder.",
                        "steps": [
                            "Generate a day of benign activity on the VM: install and update common software with winget or Chocolatey, let Windows Update run, run a few administrative PowerShell scripts, and use an installer that creates a scheduled task.",
                            "Run every rule from the previous project over that baseline window, with no atomics. Record alerts per rule per day in a spreadsheet; every alert here is a false positive.",
                            "Take the noisiest rule and review every hit: parent process, user, file path and publisher. Classify each as benign or suspicious, with a reason written next to it.",
                            "Tune it with a filter selection in the Sigma rule (condition: selection and not filter), using specific fields such as parent image and install path. Re-run the baseline and the atomic window: false positives must fall and the atomic must still alert. Commit with the evidence in the message.",
                            "Document every rule: description, ATT&CK ID, required log source, severity, known false positives, triage steps for an analyst, the test that proves it, owner and last reviewed date.",
                            "Plan a purple team exercise before running anything: choose three techniques you already cover, and for each write the variation you will try, the telemetry you expect and the detection you expect.",
                            "Run the variations, such as creating the scheduled task with PowerShell's Register-ScheduledTask instead of schtasks.exe, running PowerShell with -EncodedCommand, or renaming a copied binary. Record each as detected, missed or detected late.",
                            "For each miss, find what did record it. For the PowerShell scheduled task, enable the audit policy that logs Security event 4698 (check with `auditpol /get /category:*`), add the Security log to the forwarder, write a new rule and re-run until it fires. Commit each fix.",
                            "Add a scheduled search that alerts when the VM sends no Sysmon events for 30 minutes (for example with tstats), then stop the forwarder to prove it fires. Finish with a before and after table of alerts per day, true positives kept and gaps closed.",
                        ],
                        "hints": [
                            "Tune on specific fields such as parent process, signer and path, and re-run the original atomic every time to confirm the rule still fires.",
                            "Write the purple team plan before running anything so you cannot grade yourself kindly afterwards.",
                            "Security event 4698 appears only if the Other Object Access Events audit policy is on.",
                            "Keep one results spreadsheet with rule, version, date, atomic result and false positive count. It becomes evidence of your method.",
                        ],
                        "common_mistakes": [
                            "Excluding a whole user or directory to silence a rule, which hands attackers a hiding place.",
                            "Judging a rule only by its false positive count without checking it still catches the attack.",
                            "Testing only the exact atomic used to write the rule, so the test cannot fail.",
                            "Forgetting to revert the VM snapshot, leaving persistence behind that skews the next run.",
                        ],
                        "difficulty": 5,
                    }
                ],
            },
        ],
    },
}
