"""New Software Engineering careers: game development and embedded systems engineering."""

CAREERS = [
    dict(
        slug="game-development",
        name="Game Development",
        summary="Program the gameplay, controls, physics, menus and save systems of a game, and keep it running smoothly every frame.",
        beginner_summary="You'll learn to build small games in a real engine: moving characters, collisions, menus, saving progress, and then finishing and publishing one people can play.",
        difficulty=3,
        avg_timeline_weeks=40,
        entry_roles=["Junior Gameplay Programmer", "Junior Game Developer", "Unity Developer (junior)", "Tools Programmer (junior)"],
        tools=["Godot", "Unity", "C#", "GDScript", "Git/GitHub", "itch.io", "Aseprite", "Unreal Engine"],
        remote_potential=45,
        earning_notes="This is a competitive field with far more applicants than junior openings, and studios hire on playable builds more than on certificates. Many people get in through small studios, game jams, mods, contract work or a general programming job first. Pay at studios is often lower than for comparable non-games software roles, and rises with shipped titles and a strong specialism such as gameplay, tools or engine work.",
        icon="gamepad",
        skills_required=["Writing a game loop and handling input with frame-rate independent movement", "Collision, physics and the maths of vectors needed for movement and aiming", "Structuring behaviour with state machines, events and data-driven design", "Building menus, UI, audio hooks, and save and load systems", "Profiling frame time and fixing performance problems", "Scoping a game small enough to finish, test with players and ship"],
        certifications=[],
        interview_prep=[
            "How do you make character movement behave the same at 30 and 144 frames per second",
            "Walk through how you would structure an enemy that patrols, chases and attacks",
            "Playtesters say your jump feels floaty and unresponsive. What do you check and change",
            "Your game drops from 60 to 25 frames per second in one level. How do you find the cause",
            "You are two weeks from a deadline and a feature is half built. How do you decide what to cut",
            "How would you design a save system so that an update to the game does not break old saves",
        ],
        learning_resources=[
            {"label": "Godot official documentation", "note": "Free, official manual with a step by step tutorial for building a first 2D game in GDScript."},
            {"label": "Unity Learn", "note": "Free, official courses and pathways, including a Junior Programmer pathway in C#."},
            {"label": "Game Programming Patterns by Robert Nystrom", "note": "Free to read online; clear chapters on the game loop, state machines, object pools and more."},
        ],
        roadmap_outline={
            "beginner": [
                "Pick one engine (Godot with GDScript, or Unity with C#) and stay with it for the whole path",
                "Learn programming basics in that language: variables, functions, classes, collections",
                "Understand the game loop, delta time and why movement must not depend on frame rate",
                "Get keyboard, gamepad and mouse input working through the engine's input map",
                "Learn the vector maths you actually use: direction, distance, normalising, dot product basics",
            ],
            "intermediate": [
                "Use the engine's physics bodies and collision layers instead of writing your own collision code",
                "Structure enemies and the player with finite state machines",
                "Build a title screen, pause menu and settings screen, including audio volume",
                "Save and load progress and settings to disk with a version number",
                "Import sprites, sounds and tilemaps and learn the engine's asset pipeline",
            ],
            "advanced": [
                "Use the profiler to find and fix frame time spikes, and learn object pooling",
                "Polish game feel with screen shake, easing, hit pauses, animation and sound",
                "Plan a vertical slice, cut scope on purpose and finish it on a deadline",
                "Run playtests with strangers, record what confuses them and fix the top issues",
                "Publish a build on itch.io, enter a game jam, and write a postmortem; try Unreal Engine with C++ only after this if you want to",
            ],
        },
    ),
    dict(
        slug="embedded-systems-engineering",
        name="Embedded Systems Engineering",
        summary="Write C and C++ firmware that runs directly on microcontrollers, reading sensors and controlling hardware within tight memory, timing and power limits.",
        beginner_summary="You'll learn to program small boards in C, wire up LEDs, buttons and sensors, read datasheets, and build devices that respond to the real world on time.",
        difficulty=4,
        avg_timeline_weeks=44,
        entry_roles=["Junior Embedded Software Engineer", "Firmware Engineer (junior)", "Embedded Test Engineer", "Hardware Support Engineer"],
        tools=["C", "C++", "Arduino", "ESP32", "STM32", "Raspberry Pi Pico", "FreeRTOS", "Logic analyzer"],
        remote_potential=25,
        earning_notes="Many employers prefer an electrical, electronic or computer engineering degree, but a self-taught person with working hardware projects, clean C and the ability to debug with a logic analyzer can get interviews, often through test, support or validation roles first. Work is spread across consumer devices, industrial equipment, automotive, medical and IoT, and pay depends on the sector and on how safety critical or specialised the product is. Hardware access limits remote work.",
        icon="chip",
        skills_required=["Writing reliable C and C++ with careful memory use and no operating system conveniences", "Using GPIO, interrupts, timers and ADC to interact with hardware", "Communicating over UART, I2C and SPI and reading the datasheet to do it", "Reasoning about real time behaviour, task priorities and shared data in an RTOS", "Debugging with a logic analyzer, oscilloscope, multimeter and serial logs", "Basic electronics: voltage, current, resistors, pull-ups and power budgets"],
        certifications=[],
        interview_prep=[
            "What does the volatile keyword do, and where is it required in firmware",
            "Explain how you would debounce a button read through an interrupt",
            "A sensor on your I2C bus returns all zeros. Walk through how you would find the fault",
            "Your device resets randomly after running for a few hours. What do you check first",
            "Two tasks share a variable and one of them runs from an interrupt. How do you protect it",
            "How do you decide between polling, interrupts and DMA for a data stream",
        ],
        learning_resources=[
            {"label": "Making Embedded Systems by Elecia White", "note": "A well regarded O'Reilly book on how to think about firmware design, interfaces and debugging."},
            {"label": "Mastering the FreeRTOS Real Time Kernel", "note": "Free official book from the FreeRTOS project covering tasks, queues, semaphores and timers."},
            {"label": "Raspberry Pi Pico C/C++ SDK documentation", "note": "Free official guides for setting up the toolchain and using GPIO, I2C, SPI and timers on the Pico."},
        ],
        roadmap_outline={
            "beginner": [
                "Learn C properly: pointers, arrays, structs, bit operations and how memory is laid out",
                "Learn basic electronics: Ohm's law, resistors, LEDs, pull-up and pull-down resistors",
                "Get a cheap board (Raspberry Pi Pico, Arduino or ESP32) or a Wokwi simulator and blink an LED",
                "Read a button and drive outputs using GPIO registers or the vendor's SDK",
                "Use a hardware timer and an interrupt without blocking the main loop",
            ],
            "intermediate": [
                "Read an analog value through the ADC and convert it to real units",
                "Send debug output over UART and build a simple command parser",
                "Talk to an I2C sensor by reading its datasheet register map yourself",
                "Drive an SPI device and compare I2C and SPI on a logic analyzer",
                "Learn memory limits: stack versus heap, static allocation and checking binary size",
            ],
            "advanced": [
                "Learn FreeRTOS tasks, queues, semaphores and priorities, and where priority inversion comes from",
                "Capture and decode bus traffic with a logic analyzer, and use an oscilloscope or multimeter for signals and current",
                "Use a hardware debugger, breakpoints and fault handlers to diagnose a crash",
                "Measure and cut power use with sleep modes and wake-up sources",
                "Move a project from Arduino libraries to a vendor SDK such as ESP-IDF or STM32Cube, and write a design note for it",
            ],
        },
    ),
]

META = {
    "game-development": dict(
        keywords=["game developer", "game programmer", "gameplay programmer", "video game programmer", "unity", "unity developer", "c# unity", "godot", "gdscript", "unreal engine", "game engine", "indie game developer", "gamedev", "game dev", "game jam", "itch.io", "tools programmer", "game design programming"],
        who_its_for="People who want to make things that play, and who will finish small games rather than dream about big ones. It suits those who like maths, patience with fiddly feel and quick feedback. The catch is that studio jobs are scarce and competitive, so you need playable builds to show and a plan B in general programming.",
        portfolio_expectations=["A small arcade-style game you built and finished, playable in a browser or as a download", "A game with enemy state machines, menus, settings and a working save and load system", "A polished vertical slice published on itch.io with a short trailer or GIFs", "A written postmortem covering scope cuts, playtest findings and a performance fix"],
        career_progression=["Junior Gameplay Programmer or Junior Game Developer", "Gameplay Programmer", "Senior Gameplay or Engine Programmer", "Lead Programmer, Technical Director or Engineering Manager"],
    ),
    "embedded-systems-engineering": dict(
        keywords=["embedded engineer", "embedded software engineer", "firmware engineer", "firmware developer", "embedded c", "microcontroller", "arduino", "esp32", "stm32", "raspberry pi pico", "rtos", "freertos", "iot developer", "embedded linux", "hardware software", "device programming"],
        who_its_for="People who like making physical things respond to code and enjoy debugging with a meter or logic analyzer as much as with a debugger. It is slower and more exacting than app work, and you need a board and parts on your desk, which limits remote work. Many employers expect an engineering degree, so projects and test roles matter.",
        portfolio_expectations=["A board project with wiring photos, a schematic sketch and firmware on GitHub", "A driver you wrote from a datasheet for an I2C or SPI device, with no vendor library", "A logic analyzer or oscilloscope capture that proves your timing or protocol works", "An RTOS-based project with a design note covering tasks, priorities, memory use and power"],
        career_progression=["Junior Embedded Software Engineer or Embedded Test Engineer", "Embedded Software Engineer or Firmware Engineer", "Senior Firmware Engineer", "Principal Engineer, Embedded Systems Architect or Engineering Manager"],
    ),
}

PROJECTS = {
    "game-development": {
        "skills": [
            {"key": "gd_loop_input", "label": "Game Loop, Input & Frame-Rate Independent Movement", "category": "foundation"},
            {"key": "gd_physics_collision", "label": "Physics, Collision & Game Feel", "category": "core"},
            {"key": "gd_state_systems", "label": "State Machines, Data-Driven Design & Menus", "category": "core"},
            {"key": "gd_save_pipeline", "label": "Save/Load, Audio & Asset Pipeline", "category": "core"},
            {"key": "gd_ship_polish", "label": "Profiling, Scope Control & Shipping a Game", "category": "advanced"},
        ],
        "skill_edges": [
            ("gd_loop_input", "gd_physics_collision"),
            ("gd_physics_collision", "gd_state_systems"),
            ("gd_state_systems", "gd_save_pipeline"),
            ("gd_save_pipeline", "gd_ship_polish"),
        ],
        "phases": [
            {
                "title": "Foundations",
                "summary": "Build a complete tiny arcade game from nothing: a loop, input, collisions, a score and a game over screen, exported as a build you can send to a friend.",
                "skill_key": "gd_loop_input",
                "projects": [
                    {
                        "title": "Clone Breakout in Godot with your own game feel and an exported build",
                        "teaches": "the game loop, delta time, input actions, bouncing off collisions, a three-state game flow and exporting a playable build, using Godot 4 and GDScript (Unity and C# follow the same ideas)",
                        "prerequisites": ["Basic programming in any language", "Godot 4 installed (free, a single download)", "Finished the official 'Your first 2D game' tutorial in the Godot docs"],
                        "expected_output": "A Breakout clone with a paddle, a ball that bounces at believable angles, a grid of bricks that break, a score, lives, and title, playing and game over states, exported as a Windows, Linux, macOS or web build that runs without the editor.",
                        "steps": [
                            "Create a new Godot 4 project, set the window size to 800 by 600 and commit it to Git with a .gitignore that excludes the .godot folder.",
                            "In Project Settings, Input Map, add actions move_left and move_right bound to both arrow keys and A and D, and read them with Input.get_axis in _physics_process.",
                            "Make the paddle a CharacterBody2D that moves by speed times delta and is clamped to the screen edges.",
                            "Make the ball a CharacterBody2D, move it with move_and_collide, and on a hit call velocity.bounce(collision.get_normal()).",
                            "Change the bounce angle based on where the ball hits the paddle so the player can aim, and keep the ball speed constant by normalising the velocity.",
                            "Make bricks StaticBody2D scenes that remove themselves when hit, instantiate a grid of them from code, and add score and lives labels.",
                            "Add a game state variable with TITLE, PLAYING and GAME_OVER, and show or hide the right screens when it changes.",
                            "Add two sound effects and one particle burst when a brick breaks, then use Project, Export to make a build and run it outside the editor.",
                        ],
                        "hints": [
                            "Put movement in _physics_process and multiply by delta so the speed is the same on every machine.",
                            "A ball that slowly speeds up or slows down is usually a normalising problem. Set the length of the velocity every frame.",
                            "Use signals (for example a brick_destroyed signal) rather than having bricks reach into the score label.",
                            "Test the exported build early. Export problems found on the last day are the worst ones.",
                        ],
                        "common_mistakes": [
                            "Moving things by a fixed number of pixels per frame, so the game runs faster on a faster computer.",
                            "Letting the ball get stuck bouncing horizontally forever with no minimum vertical speed.",
                            "Putting every script's logic in one giant main script.",
                            "Adding lots of features before the basic bounce feels good.",
                        ],
                        "difficulty": 1,
                    },
                ],
            },
            {
                "title": "Building Real Skills",
                "summary": "Build a game made of systems rather than one mechanic: enemies with behaviour, upgrades driven by data, menus, settings and a save file that survives a restart.",
                "skill_key": "gd_state_systems",
                "projects": [
                    {
                        "title": "Build a top-down wave survival game with enemy state machines, data-driven upgrades, menus and save/load",
                        "teaches": "finite state machines, data-driven design with custom resources, signals and autoloads, pause and settings menus, object pooling and versioned save files in Godot 4 (Unity ScriptableObjects and JsonUtility play the same roles)",
                        "prerequisites": ["Finished a small game in Godot or Unity", "Comfort with scenes or prefabs, signals or events, and basic vector maths", "Free art such as Kenney asset packs from kenney.nl"],
                        "expected_output": "A top-down survival game in which the player fights waves of enemies that patrol, chase and attack, picks upgrades between waves, and uses a title screen, pause menu and settings screen, with progress and volume settings saved to disk and restored on launch.",
                        "steps": [
                            "Create a player that moves with WASD or a gamepad stick and aims at the mouse, using CharacterBody2D and a normalised input vector so diagonals are not faster.",
                            "Write an enemy with a state machine (IDLE, CHASE, ATTACK, DEAD) as a script with an enum and one function per state, and use an Area2D for detection range.",
                            "Define enemy types and upgrades as custom Resource scripts saved as .tres files (health, speed, damage) so you can add a new enemy without changing code.",
                            "Spawn waves from a wave table, and reuse bullets through a simple object pool rather than creating and freeing one for every shot.",
                            "Add an autoload GameState singleton that holds score, wave number and chosen upgrades, and emits signals the HUD listens to.",
                            "Build a title screen, a pause menu that sets get_tree().paused, and a settings screen with a music and effects volume slider using AudioServer.set_bus_volume_db.",
                            "Save progress and settings as JSON in user:// using FileAccess and JSON.stringify, include a save_version number, and load it safely when the file is missing or damaged.",
                            "Open the Debugger, Monitors and Profiler panels during a busy wave, note the frame time, and fix the worst offender.",
                        ],
                        "hints": [
                            "Keep each state's code in its own function so adding a new state does not mean editing a tangle of if statements.",
                            "Use collision layers and masks so enemy bullets cannot hit enemies and player bullets cannot hit the player.",
                            "Test the save file by editing it by hand into something broken and make sure the game recovers instead of crashing.",
                            "Make a build and run it, because user:// points to a different folder than the editor sometimes appears to.",
                        ],
                        "common_mistakes": [
                            "Hardcoding enemy numbers in scripts so every balance change needs a code change.",
                            "Saving the whole scene tree instead of the small set of values that must persist.",
                            "Forgetting to unpause the tree when returning to the title screen, which freezes the next game.",
                            "Creating and freeing hundreds of bullets per second and getting stutters from it.",
                        ],
                        "difficulty": 3,
                    },
                ],
            },
            {
                "title": "Advanced Practice",
                "summary": "Take a game from idea to a public release with a fixed scope: plan, build, playtest, tune the feel, profile, publish on itch.io and write up what happened.",
                "skill_key": "gd_ship_polish",
                "projects": [
                    {
                        "title": "Ship a ten minute vertical slice on itch.io and write its postmortem",
                        "teaches": "scoping a game to a deadline, polishing game feel, running playtests, profiling performance and publishing with the itch.io tools, then reflecting on the result in a postmortem",
                        "prerequisites": ["A systems-driven game already built", "A free itch.io account", "Five people willing to play and watch silently, or an itch.io game jam to join"],
                        "expected_output": "A public itch.io page with a playable ten minute slice (browser build or downloads), a cover image and GIFs, a short devlog, and a postmortem covering scope cuts, playtest findings, a measured performance fix and what you would do differently.",
                        "steps": [
                            "Write a one page scope document with a one sentence pitch, a must-have list of at most five features, a nice-to-have list and a hard deadline of four to six weeks.",
                            "Build the core loop first and play it every day, cutting anything on the must-have list that is not working by the end of week two.",
                            "Add game feel: screen shake, a short hit pause, easing on UI, anticipation and recovery frames in attacks, and a sound for every action.",
                            "Run a playtest with five people on their own machines without helping them, take notes on where they get confused or stuck, and fix the top three problems.",
                            "Use the engine profiler to find the slowest frames on the lowest-spec machine you can get, fix the worst, and record frame time before and after.",
                            "Export a web build (Godot HTML5 export or Unity WebGL) and a desktop build, and test them on a machine that has never had the engine installed.",
                            "Create the itch.io page with a cover image, three screenshots or GIFs, controls and credits, upload with the itch.io app or the butler command line tool, and mark the build playable in the browser.",
                            "Write a postmortem in the devlog: what went well, what went wrong, what you cut and why, and what the playtests taught you.",
                        ],
                        "hints": [
                            "Scope is the skill being tested. A small finished game beats a large unfinished one every time.",
                            "Watch playtesters in silence. If you have to explain something, the game needs to explain it.",
                            "Enter a jam such as a GMTK Game Jam or a Ludum Dare weekend to practise shipping under a hard deadline.",
                            "Put a build in front of people early. A rough public page now is better than a perfect one never.",
                        ],
                        "common_mistakes": [
                            "Adding new features in the last week instead of fixing the ones that exist.",
                            "Only testing on your own powerful computer.",
                            "Ignoring the first minute of the game, which is the only part many players will see.",
                            "Writing a postmortem that only lists successes.",
                        ],
                        "difficulty": 5,
                    },
                ],
            },
        ],
    },
    "embedded-systems-engineering": {
        "skills": [
            {"key": "emb_c_electronics", "label": "Embedded C & Basic Electronics", "category": "foundation"},
            {"key": "emb_gpio_interrupts", "label": "GPIO, Timers & Interrupts", "category": "core"},
            {"key": "emb_datasheets_buses", "label": "Datasheets, I2C/SPI/UART & Drivers", "category": "core"},
            {"key": "emb_rtos_realtime", "label": "RTOS & Real-Time Design", "category": "advanced"},
            {"key": "emb_debug_power", "label": "Hardware Debugging & Power Optimisation", "category": "advanced"},
        ],
        "skill_edges": [
            ("emb_c_electronics", "emb_gpio_interrupts"),
            ("emb_gpio_interrupts", "emb_datasheets_buses"),
            ("emb_datasheets_buses", "emb_rtos_realtime"),
            ("emb_rtos_realtime", "emb_debug_power"),
        ],
        "phases": [
            {
                "title": "Foundations",
                "summary": "Wire real outputs and an input to a microcontroller and write C that responds on time without blocking: interrupts, debouncing and a state machine.",
                "skill_key": "emb_c_electronics",
                "projects": [
                    {
                        "title": "Build a pedestrian crossing controller with an interrupt-driven button on a Raspberry Pi Pico",
                        "teaches": "wiring LEDs and a button safely, GPIO in C with the Pico SDK, interrupt handlers that stay short, debouncing, and a non-blocking state machine driven by timestamps",
                        "prerequisites": ["Basic C syntax (variables, functions, if and switch)", "A Raspberry Pi Pico with a USB cable, a breadboard, 4 LEDs (red, yellow, green, white), 4 resistors of about 220 ohm, a pushbutton and jumper wires, or a free Wokwi account to simulate them", "Pico SDK and toolchain installed, or the Raspberry Pi Pico VS Code extension"],
                        "expected_output": "A working crossing controller: cars see green, a button press makes the lights go yellow then red, the white walk LED lights for a fixed time, then the sequence returns to green. It never freezes while waiting, ignores bounces and repeat presses mid-cycle, and the code and a wiring photo or Wokwi project link are on GitHub.",
                        "steps": [
                            "Set up the Pico SDK with CMake (or the VS Code extension) and get the stock blink example running with an external LED on GP10 through a 220 ohm resistor.",
                            "Work out the resistor value from the supply, LED forward voltage and a target of a few milliamps, and write the calculation in your README.",
                            "Wire the four LEDs to GP10 to GP13 and the button between GP14 and ground, and enable the internal pull-up with gpio_pull_up(14).",
                            "Initialise the pins with gpio_init, gpio_set_dir and gpio_put, and test every LED from a small function before adding any logic.",
                            "Register a falling-edge interrupt with gpio_set_irq_enabled_with_callback, and in the callback only set a volatile flag and record the time.",
                            "Debounce by ignoring edges that arrive less than 50 milliseconds after the last accepted one, using time_us_32 rather than sleep_ms.",
                            "Write the light sequence as a state machine (CARS_GO, CARS_WARN, CARS_STOP, WALK, WALK_END) in the main loop that compares the current time with a state deadline instead of blocking.",
                            "Press the button repeatedly mid-cycle and confirm it is ignored, then print state changes over USB serial with printf and screenshot them.",
                        ],
                        "hints": [
                            "Keep interrupt handlers to a few lines: set a flag, save a timestamp, return. Do the real work in the main loop.",
                            "A variable shared between an interrupt and the main loop must be volatile.",
                            "If the button seems to press itself, check you enabled the pull-up and wired the other side to ground, not to 3.3 volts.",
                            "In Wokwi, copy your pin numbers into the diagram first so wiring and code agree.",
                        ],
                        "common_mistakes": [
                            "Using sleep_ms for the light timings so the button is dead while the sequence runs.",
                            "Doing printf or long calculations inside the interrupt handler.",
                            "Wiring an LED with no resistor and hoping the pin survives.",
                            "Reading the button in a tight loop with no debounce and seeing several presses for one.",
                        ],
                        "difficulty": 1,
                    },
                ],
            },
            {
                "title": "Building Real Skills",
                "summary": "Write your own driver for an I2C sensor from its datasheet with no vendor library, then prove the bus works by looking at the actual signals.",
                "skill_key": "emb_datasheets_buses",
                "projects": [
                    {
                        "title": "Write an I2C driver for a BMP280 or BME280 sensor from the datasheet and verify it with a logic analyzer",
                        "teaches": "reading a datasheet register map, I2C transactions in C, fixed-point compensation maths, UART logging, and checking a bus with a logic analyzer and its protocol decoder",
                        "prerequisites": ["Completed a GPIO and interrupt project", "A Raspberry Pi Pico, a BMP280 or BME280 breakout board and jumper wires (or a Wokwi project with a simulated I2C sensor such as the MPU6050 or BMP280 part, adapting the registers to its datasheet)", "Optional: an 8 channel USB logic analyzer and the free PulseView or Saleae Logic software"],
                        "expected_output": "A small driver (sensor.c and sensor.h) that identifies the chip, reads calibration data, takes a measurement and prints temperature in degrees Celsius over USB serial once a second, with a logic analyzer capture or decoded screenshot showing the transaction, plus a README with the register map you used.",
                        "steps": [
                            "Download the sensor datasheet (the Bosch BMP280 or BME280 datasheet) and write down the I2C address (0x76 or 0x77), the chip ID register 0xD0, the control register 0xF4 and the data registers from 0xFA.",
                            "Wire SDA to GP4 and SCL to GP5 on i2c0, power the sensor from 3.3 volts, call i2c_init(i2c0, 100000) and set both pins to the I2C function.",
                            "Scan the bus with i2c_write_blocking and i2c_read_blocking and print the addresses that answer.",
                            "Read register 0xD0 and check the value against the datasheet (0x58 for a BMP280, 0x60 for a BME280), and print an error if it does not match.",
                            "Read the 24 bytes of temperature and pressure calibration data starting at 0x88 into a struct and print it.",
                            "Write the control register to start measuring, read the three raw temperature bytes, and apply the datasheet's integer compensation formula to get degrees Celsius.",
                            "Check the reading against a room thermometer, warm the sensor with your finger and watch the value rise.",
                            "Capture the SDA and SCL lines with the logic analyzer, add the I2C decoder in PulseView and save an annotated screenshot of the chip ID read. If you only have the simulator, use the Wokwi logic analyzer part to export a capture.",
                        ],
                        "hints": [
                            "Do not move on until the chip ID read works. Every other register read depends on that.",
                            "I2C needs pull-up resistors on SDA and SCL. Most breakout boards include them. If the bus does not work, check this first.",
                            "Use the datasheet's compensation code as a reference and type it carefully, paying attention to integer types and signed values.",
                            "A wrong address is the most common bug. Try the other of the two possible addresses.",
                        ],
                        "common_mistakes": [
                            "Using a 5 volt supply for a 3.3 volt part, or mixing the sensor's SDA and SCL wires.",
                            "Reading the raw values and skipping the calibration maths, then getting nonsense temperatures.",
                            "Copying a library and calling it a driver without understanding what bytes go on the wire.",
                            "Ignoring the return value of i2c_write_blocking so a missing device goes unnoticed.",
                        ],
                        "difficulty": 3,
                    },
                ],
            },
            {
                "title": "Advanced Practice",
                "summary": "Build a multi-task data logger on an ESP32 under FreeRTOS, measure its timing and current draw, and cut its power use with deep sleep.",
                "skill_key": "emb_rtos_realtime",
                "projects": [
                    {
                        "title": "Build a FreeRTOS sensor logger on an ESP32 with a watchdog, a jitter measurement and a deep sleep power comparison",
                        "teaches": "FreeRTOS tasks, priorities and queues in ESP-IDF, measuring real time jitter with a GPIO and a logic analyzer, task watchdogs, stack sizing and low power design with deep sleep",
                        "prerequisites": ["The sensor driver project, or any working I2C device", "An ESP32 DevKitC board, a USB cable, your I2C sensor, an LED and jumper wires (or the Wokwi ESP32 simulator)", "ESP-IDF installed with the VS Code extension, or the idf.py command line tool", "A multimeter or USB power meter is optional but recommended"],
                        "expected_output": "An ESP-IDF project with a sampling task, a logging task and a queue between them, a measured jitter result for the 100 millisecond sample period, a demonstrated watchdog reset, a stack usage table, and a deep sleep mode with before and after current figures, all in a short design note.",
                        "steps": [
                            "Create an ESP-IDF project, build and flash the hello world example with idf.py build flash monitor, and confirm the serial output.",
                            "Create a sampling task with xTaskCreate that uses vTaskDelayUntil for an exact 100 millisecond period, reads your sensor over I2C and sends a struct to a queue made with xQueueCreate.",
                            "Create a lower-priority logging task that receives from the queue, prints each reading as a CSV line, and keeps the last 100 readings in a ring buffer.",
                            "Toggle a GPIO at the start of every sample and measure the period and jitter on a logic analyzer (or the Wokwi logic analyzer) and record min, max and average.",
                            "Add a higher-priority task that burns CPU for a few milliseconds, repeat the measurement, and explain in your notes what changed and why.",
                            "Subscribe the sampling task to the task watchdog with esp_task_wdt_add, feed it every cycle, then stop feeding it on purpose and capture the reset message.",
                            "Print uxTaskGetStackHighWaterMark for each task, shrink the stack sizes to a safe margin and note the memory saved.",
                            "Add a deep sleep mode with esp_sleep_enable_timer_wakeup and esp_deep_sleep_start that wakes once a minute, takes a reading and sleeps again, and compare current draw awake and asleep with a meter, or compare the datasheet figures if you have no meter.",
                        ],
                        "hints": [
                            "Use vTaskDelayUntil rather than vTaskDelay for periodic work, because it removes the drift caused by the task's own run time.",
                            "A queue is the safe way to hand data between tasks. Avoid sharing globals without a mutex or a critical section.",
                            "Give tasks enough stack at first, then reduce it using the high-water mark rather than guessing.",
                            "When measuring current, the board's USB-serial chip and power LED draw a lot. Note what you measured and what you left out.",
                        ],
                        "common_mistakes": [
                            "Calling blocking or very slow functions inside an interrupt handler.",
                            "Giving every task the same high priority and wondering why nothing behaves predictably.",
                            "Choosing stack sizes by guessing, then getting random crashes under load.",
                            "Claiming a power saving without measuring before and after.",
                        ],
                        "difficulty": 5,
                    },
                ],
            },
        ],
    },
}
