"""initial schema

Revision ID: 0b7001e88cf4
Revises: 
Create Date: 2026-08-16 19:15:24.092803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_paths',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('beginner_summary', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('avg_timeline_weeks', sa.Integer(), nullable=False),
    sa.Column('entry_roles', sa.JSON(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('remote_potential', sa.Integer(), nullable=False),
    sa.Column('earning_notes', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_paths_slug'), 'career_paths', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('persona', sa.Enum('student', 'graduate', 'working', 'switcher', 'entrepreneur', 'other', name='persona'), nullable=True),
    sa.Column('goal', sa.Enum('job', 'freelance', 'startup', 'remote', 'explore', name='goal'), nullable=True),
    sa.Column('device_access', sa.Enum('laptop', 'smartphone', 'both', name='deviceaccess'), nullable=True),
    sa.Column('time_budget_minutes_per_day', sa.Integer(), nullable=True),
    sa.Column('beginner_mode', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', name='plan'), nullable=False),
    sa.Column('role', sa.Enum('user', 'mentor', 'admin', name='role'), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_conversations',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('assessments',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('best_match_path_id', app.db.base.GUID(), nullable=True),
    sa.Column('strong_alt_path_id', app.db.base.GUID(), nullable=True),
    sa.Column('wild_card_path_id', app.db.base.GUID(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('career_dna', sa.JSON(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['best_match_path_id'], ['career_paths.id'], ),
    sa.ForeignKeyConstraint(['strong_alt_path_id'], ['career_paths.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wild_card_path_id'], ['career_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_user_id'), 'assessments', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', app.db.base.GUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communities',
    sa.Column('path_id', app.db.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['career_paths.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_id')
    )
    op.create_table('daily_missions',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tasks', sa.JSON(), nullable=False),
    sa.Column('rationale_text', sa.Text(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_missions_user_id'), 'daily_missions', ['user_id'], unique=False)
    op.create_table('mentors',
    sa.Column('user_id', app.db.base.GUID(), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('headline', sa.String(length=240), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('avatar_seed', sa.String(length=80), nullable=False),
    sa.Column('paths', sa.JSON(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('hourly_rate_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=6), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('path_fit_rules',
    sa.Column('path_id', app.db.base.GUID(), nullable=False),
    sa.Column('trait_key', sa.String(length=80), nullable=False),
    sa.Column('match_value', sa.String(length=80), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['career_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readiness_scores',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('overall', sa.Integer(), nullable=False),
    sa.Column('knowledge_pct', sa.Integer(), nullable=False),
    sa.Column('projects_pct', sa.Integer(), nullable=False),
    sa.Column('portfolio_pct', sa.Integer(), nullable=False),
    sa.Column('interview_pct', sa.Integer(), nullable=False),
    sa.Column('practical_pct', sa.Integer(), nullable=False),
    sa.Column('next_actions', sa.JSON(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readiness_scores_user_id'), 'readiness_scores', ['user_id'], unique=False)
    op.create_table('roadmap_phases',
    sa.Column('path_id', app.db.base.GUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('unlocks_at_skill_pct', sa.Integer(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['career_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_phases_path_id'), 'roadmap_phases', ['path_id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('path_id', app.db.base.GUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'archived', name='roadmapstatus'), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['career_paths.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_user_id'), 'roadmaps', ['user_id'], unique=False)
    op.create_table('simulations',
    sa.Column('path_id', app.db.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scenario_md', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option', sa.String(length=10), nullable=False),
    sa.Column('explanation_md', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['career_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_path_id'), 'simulations', ['path_id'], unique=False)
    op.create_table('skill_nodes',
    sa.Column('path_id', app.db.base.GUID(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['career_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_nodes_path_id'), 'skill_nodes', ['path_id'], unique=False)
    op.create_table('streaks',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('current_streak_days', sa.Integer(), nullable=False),
    sa.Column('longest_streak_days', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaks_user_id'), 'streaks', ['user_id'], unique=True)
    op.create_table('xp_events',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_events_user_id'), 'xp_events', ['user_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('conversation_id', app.db.base.GUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_table('community_posts',
    sa.Column('community_id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_community_id'), 'community_posts', ['community_id'], unique=False)
    op.create_table('leaderboard_entries',
    sa.Column('community_id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_entries_community_id'), 'leaderboard_entries', ['community_id'], unique=False)
    op.create_table('lessons',
    sa.Column('phase_id', app.db.base.GUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('concept_summary', sa.Text(), nullable=False),
    sa.Column('beginner_explainer', sa.Text(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=False),
    sa.Column('skill_node_id', app.db.base.GUID(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['roadmap_phases.id'], ),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_phase_id'), 'lessons', ['phase_id'], unique=False)
    op.create_table('mentor_sessions',
    sa.Column('mentor_id', app.db.base.GUID(), nullable=False),
    sa.Column('mentee_id', app.db.base.GUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'confirmed', 'completed', 'cancelled', name='sessionstatus'), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=6), nullable=False),
    sa.Column('payment_provider_ref', sa.String(length=255), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_sessions_mentee_id'), 'mentor_sessions', ['mentee_id'], unique=False)
    op.create_index(op.f('ix_mentor_sessions_mentor_id'), 'mentor_sessions', ['mentor_id'], unique=False)
    op.create_table('projects',
    sa.Column('phase_id', app.db.base.GUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('teaches', sa.Text(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('hints', sa.JSON(), nullable=False),
    sa.Column('common_mistakes', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('skill_node_id', app.db.base.GUID(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['roadmap_phases.id'], ),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_phase_id'), 'projects', ['phase_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('phase_id', app.db.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('passing_score', sa.Integer(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['roadmap_phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_phase_id'), 'quizzes', ['phase_id'], unique=False)
    op.create_table('skill_edges',
    sa.Column('path_id', app.db.base.GUID(), nullable=False),
    sa.Column('from_skill_id', app.db.base.GUID(), nullable=False),
    sa.Column('to_skill_id', app.db.base.GUID(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_skill_id'], ['skill_nodes.id'], ),
    sa.ForeignKeyConstraint(['path_id'], ['career_paths.id'], ),
    sa.ForeignKeyConstraint(['to_skill_id'], ['skill_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_edges_path_id'), 'skill_edges', ['path_id'], unique=False)
    op.create_table('user_simulation_attempts',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('simulation_id', app.db.base.GUID(), nullable=False),
    sa.Column('chosen_option', sa.String(length=10), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_simulation_attempts_user_id'), 'user_simulation_attempts', ['user_id'], unique=False)
    op.create_table('user_skill_progress',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('skill_node_id', app.db.base.GUID(), nullable=False),
    sa.Column('mastery_pct', sa.Integer(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['skill_node_id'], ['skill_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skill_progress_skill_node_id'), 'user_skill_progress', ['skill_node_id'], unique=False)
    op.create_index(op.f('ix_user_skill_progress_user_id'), 'user_skill_progress', ['user_id'], unique=False)
    op.create_table('community_comments',
    sa.Column('post_id', app.db.base.GUID(), nullable=False),
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_comments_post_id'), 'community_comments', ['post_id'], unique=False)
    op.create_table('exercises',
    sa.Column('lesson_id', app.db.base.GUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('answer_key', sa.JSON(), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_lesson_id'), 'exercises', ['lesson_id'], unique=False)
    op.create_table('mentor_reviews',
    sa.Column('session_id', app.db.base.GUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['mentor_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_reviews_session_id'), 'mentor_reviews', ['session_id'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('project_id', app.db.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=False),
    sa.Column('readme_draft', sa.Text(), nullable=False),
    sa.Column('cv_bullet', sa.Text(), nullable=False),
    sa.Column('linkedin_blurb', sa.Text(), nullable=False),
    sa.Column('case_study_md', sa.Text(), nullable=False),
    sa.Column('skills_demonstrated', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_items_user_id'), 'portfolio_items', ['user_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('lesson_id', app.db.base.GUID(), nullable=True),
    sa.Column('project_id', app.db.base.GUID(), nullable=True),
    sa.Column('quiz_id', app.db.base.GUID(), nullable=True),
    sa.Column('exercise_id', app.db.base.GUID(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', name='progressstatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_portfolio_items_user_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_mentor_reviews_session_id'), table_name='mentor_reviews')
    op.drop_table('mentor_reviews')
    op.drop_index(op.f('ix_exercises_lesson_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_community_comments_post_id'), table_name='community_comments')
    op.drop_table('community_comments')
    op.drop_index(op.f('ix_user_skill_progress_user_id'), table_name='user_skill_progress')
    op.drop_index(op.f('ix_user_skill_progress_skill_node_id'), table_name='user_skill_progress')
    op.drop_table('user_skill_progress')
    op.drop_index(op.f('ix_user_simulation_attempts_user_id'), table_name='user_simulation_attempts')
    op.drop_table('user_simulation_attempts')
    op.drop_index(op.f('ix_skill_edges_path_id'), table_name='skill_edges')
    op.drop_table('skill_edges')
    op.drop_index(op.f('ix_quizzes_phase_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_projects_phase_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_mentor_sessions_mentor_id'), table_name='mentor_sessions')
    op.drop_index(op.f('ix_mentor_sessions_mentee_id'), table_name='mentor_sessions')
    op.drop_table('mentor_sessions')
    op.drop_index(op.f('ix_lessons_phase_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_leaderboard_entries_community_id'), table_name='leaderboard_entries')
    op.drop_table('leaderboard_entries')
    op.drop_index(op.f('ix_community_posts_community_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_xp_events_user_id'), table_name='xp_events')
    op.drop_table('xp_events')
    op.drop_index(op.f('ix_streaks_user_id'), table_name='streaks')
    op.drop_table('streaks')
    op.drop_index(op.f('ix_skill_nodes_path_id'), table_name='skill_nodes')
    op.drop_table('skill_nodes')
    op.drop_index(op.f('ix_simulations_path_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index(op.f('ix_roadmaps_user_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index(op.f('ix_roadmap_phases_path_id'), table_name='roadmap_phases')
    op.drop_table('roadmap_phases')
    op.drop_index(op.f('ix_readiness_scores_user_id'), table_name='readiness_scores')
    op.drop_table('readiness_scores')
    op.drop_table('path_fit_rules')
    op.drop_table('mentors')
    op.drop_index(op.f('ix_daily_missions_user_id'), table_name='daily_missions')
    op.drop_table('daily_missions')
    op.drop_table('communities')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assessments_user_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_career_paths_slug'), table_name='career_paths')
    op.drop_table('career_paths')
    # ### end Alembic commands ###
