"""add mentor marketplace v2 tables and columns

Revision ID: ab1589948938
Revises: 0001
Create Date: 2026-08-24 10:03:41.160855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base


revision: str = 'ab1589948938'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_applications',
    sa.Column('applicant_name', sa.String(length=160), nullable=False),
    sa.Column('applicant_email', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.String(length=240), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('paths', sa.JSON(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='applicationstatus'), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentor_notes',
    sa.Column('session_id', app.db.base.GUID(), nullable=False),
    sa.Column('mentor_id', app.db.base.GUID(), nullable=False),
    sa.Column('what_to_work_on', sa.Text(), nullable=False),
    sa.Column('recommended_resources', sa.JSON(), nullable=False),
    sa.Column('recommended_projects', sa.JSON(), nullable=False),
    sa.Column('next_steps', sa.Text(), nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['mentor_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_notes_mentor_id'), 'mentor_notes', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_mentor_notes_session_id'), 'mentor_notes', ['session_id'], unique=False)
    op.create_table('mentor_recommendations',
    sa.Column('session_id', app.db.base.GUID(), nullable=False),
    sa.Column('mentor_id', app.db.base.GUID(), nullable=False),
    sa.Column('mentee_id', app.db.base.GUID(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['mentor_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_recommendations_mentee_id'), 'mentor_recommendations', ['mentee_id'], unique=False)
    op.create_index(op.f('ix_mentor_recommendations_mentor_id'), 'mentor_recommendations', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_mentor_recommendations_session_id'), 'mentor_recommendations', ['session_id'], unique=False)
    op.create_table('roadmap_custom_items',
    sa.Column('user_id', app.db.base.GUID(), nullable=False),
    sa.Column('roadmap_id', app.db.base.GUID(), nullable=False),
    sa.Column('source_recommendation_id', app.db.base.GUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', app.db.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.ForeignKeyConstraint(['source_recommendation_id'], ['mentor_recommendations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_custom_items_roadmap_id'), 'roadmap_custom_items', ['roadmap_id'], unique=False)
    op.create_index(op.f('ix_roadmap_custom_items_user_id'), 'roadmap_custom_items', ['user_id'], unique=False)
    op.add_column('mentor_reviews', sa.Column('mentor_id', app.db.base.GUID(), nullable=False))
    op.add_column('mentor_reviews', sa.Column('is_demo', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_mentor_reviews_mentor_id'), 'mentor_reviews', ['mentor_id'], unique=False)
    op.create_foreign_key(None, 'mentor_reviews', 'mentors', ['mentor_id'], ['id'])
    op.add_column('mentor_sessions', sa.Column('help_topic', sa.String(length=80), nullable=True))
    op.add_column('mentor_sessions', sa.Column('mentee_message', sa.Text(), nullable=False, server_default=sa.text("''")))
    op.add_column('mentor_sessions', sa.Column('mentee_summary', sa.Text(), nullable=False, server_default=sa.text("''")))
    op.add_column('mentors', sa.Column('is_demo', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('mentors', sa.Column('is_founding_mentor', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('mentors', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('mentors', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('mentors', sa.Column('languages', sa.JSON(), nullable=False, server_default=sa.text('\'["English"]\'::json')))
    op.add_column('mentors', sa.Column('mentorship_formats', sa.JSON(), nullable=False, server_default=sa.text('\'["video_call"]\'::json')))
    op.add_column('mentors', sa.Column('session_durations_minutes', sa.JSON(), nullable=False, server_default=sa.text('\'[30, 60]\'::json')))
    op.add_column('mentors', sa.Column('value_proposition', sa.Text(), nullable=False, server_default=sa.text("''")))
    op.add_column('mentors', sa.Column('focus_beginner_friendly', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('mentors', sa.Column('availability_note', sa.Text(), nullable=False, server_default=sa.text("'Availability coming soon — check back or ask a question.'")))
    op.add_column('mentors', sa.Column('mentee_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.alter_column('mentors', 'years_experience',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mentors', 'years_experience',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('mentors', 'mentee_count')
    op.drop_column('mentors', 'availability_note')
    op.drop_column('mentors', 'focus_beginner_friendly')
    op.drop_column('mentors', 'value_proposition')
    op.drop_column('mentors', 'session_durations_minutes')
    op.drop_column('mentors', 'mentorship_formats')
    op.drop_column('mentors', 'languages')
    op.drop_column('mentors', 'avatar_url')
    op.drop_column('mentors', 'contact_email')
    op.drop_column('mentors', 'is_founding_mentor')
    op.drop_column('mentors', 'is_demo')
    op.drop_column('mentor_sessions', 'mentee_summary')
    op.drop_column('mentor_sessions', 'mentee_message')
    op.drop_column('mentor_sessions', 'help_topic')
    op.drop_constraint(None, 'mentor_reviews', type_='foreignkey')
    op.drop_index(op.f('ix_mentor_reviews_mentor_id'), table_name='mentor_reviews')
    op.drop_column('mentor_reviews', 'is_demo')
    op.drop_column('mentor_reviews', 'mentor_id')
    op.drop_index(op.f('ix_roadmap_custom_items_user_id'), table_name='roadmap_custom_items')
    op.drop_index(op.f('ix_roadmap_custom_items_roadmap_id'), table_name='roadmap_custom_items')
    op.drop_table('roadmap_custom_items')
    op.drop_index(op.f('ix_mentor_recommendations_session_id'), table_name='mentor_recommendations')
    op.drop_index(op.f('ix_mentor_recommendations_mentor_id'), table_name='mentor_recommendations')
    op.drop_index(op.f('ix_mentor_recommendations_mentee_id'), table_name='mentor_recommendations')
    op.drop_table('mentor_recommendations')
    op.drop_index(op.f('ix_mentor_notes_session_id'), table_name='mentor_notes')
    op.drop_index(op.f('ix_mentor_notes_mentor_id'), table_name='mentor_notes')
    op.drop_table('mentor_notes')
    op.drop_table('mentor_applications')
    # ### end Alembic commands ###
