"""Full career path catalog — all 20 paths from the product spec, with real,
non-lorem-ipsum copy. Two paths (cybersecurity, software-engineering) get a
complete phased roadmap in seed_data.py; the rest are fully browsable/
assessable today and clearly marked as "roadmap content coming soon" if a
user tries to generate a roadmap for them.
"""

CAREER_PATHS = [
    dict(
        slug="cybersecurity",
        name="Cybersecurity",
        summary="Protect organizations from attackers by finding, fixing, and defending against security weaknesses across networks, systems, and applications.",
        beginner_summary="You'll learn how computers and networks talk to each other, then how to spot and stop people trying to break in.",
        difficulty=3, avg_timeline_weeks=32,
        entry_roles=["SOC Analyst (Tier 1)", "IT Security Support", "Junior Security Analyst"],
        tools=["Wireshark", "Linux", "Python", "Splunk/SIEM basics", "Nmap"],
        remote_potential=75,
        earning_notes="Entry-level SOC roles commonly start in the $45k-$70k range in the US (lower in many regions, higher with certifications); pay grows quickly with 1-2 years of experience.",
        icon="shield",
    ),
    dict(
        slug="software-engineering",
        name="Software Engineering",
        summary="Design, build, and maintain the applications and systems that power products people use every day.",
        beginner_summary="You'll learn to write instructions computers follow to build real, working apps, starting from your very first program.",
        difficulty=3, avg_timeline_weeks=36,
        entry_roles=["Junior Software Engineer", "Associate Developer", "Software Engineer I"],
        tools=["Python or JavaScript", "Git/GitHub", "SQL", "REST APIs", "VS Code"],
        remote_potential=85,
        earning_notes="Entry-level roles vary hugely by market, commonly $55k-$95k in the US, with strong remote demand globally for developers who can demonstrate real projects.",
        icon="code",
    ),
    dict(
        slug="frontend-development", name="Frontend Development",
        summary="Build the visual, interactive part of websites and apps that users see and click on.",
        beginner_summary="You'll learn to turn a design into a real, working webpage people can use.",
        difficulty=2, avg_timeline_weeks=24,
        entry_roles=["Junior Frontend Developer", "UI Developer"],
        tools=["HTML/CSS", "JavaScript", "React", "Git"], remote_potential=85,
        earning_notes="Often one of the more accessible entry points into software, with strong freelance/remote demand.",
        icon="layout",
    ),
    dict(
        slug="backend-engineering", name="Backend Engineering",
        summary="Build the servers, databases, and APIs that power an app behind the scenes.",
        beginner_summary="You'll learn how apps store data and respond to requests: the engine room most users never see.",
        difficulty=3, avg_timeline_weeks=30,
        entry_roles=["Junior Backend Developer", "API Developer"],
        tools=["Python/Node.js", "SQL", "REST/GraphQL", "Docker basics"], remote_potential=85,
        earning_notes="Backend roles often pay slightly above average entry-level dev salaries due to systems complexity.",
        icon="server",
    ),
    dict(
        slug="full-stack-development", name="Full-Stack Development",
        summary="Build both the visible part of an app and the systems that power it behind the scenes.",
        beginner_summary="You'll learn to build a complete app end-to-end, from what users click to where their data is stored.",
        difficulty=4, avg_timeline_weeks=40,
        entry_roles=["Junior Full-Stack Developer"],
        tools=["JavaScript/TypeScript", "React", "Node.js", "SQL"], remote_potential=85,
        earning_notes="Versatility is valued by smaller companies and startups especially; pay is competitive with backend roles.",
        icon="layers",
    ),
    dict(
        slug="cloud-engineering", name="Cloud Engineering",
        summary="Set up and run computer systems that live on the internet ('the cloud') instead of one physical machine.",
        beginner_summary="You'll learn to rent and configure computing power from providers like AWS instead of buying physical servers.",
        difficulty=3, avg_timeline_weeks=28,
        entry_roles=["Junior Cloud Engineer", "Cloud Support Associate"],
        tools=["AWS/Azure/GCP basics", "Linux", "Terraform", "Docker"], remote_potential=80,
        earning_notes="Cloud certifications (e.g. AWS Cloud Practitioner) meaningfully boost entry-level offers.",
        icon="cloud",
    ),
    dict(
        slug="cloud-security", name="Cloud Security",
        summary="Protect internet-based (cloud) systems from misconfigurations and attackers.",
        beginner_summary="You'll learn how cloud systems get set up, then how to spot the mistakes that let attackers in.",
        difficulty=4, avg_timeline_weeks=34,
        entry_roles=["Junior Cloud Security Analyst"],
        tools=["AWS/Azure security tools", "IAM", "Linux", "Python"], remote_potential=75,
        earning_notes="A growing, higher-paying specialization once foundational cloud + security skills are in place.",
        icon="lock",
    ),
    dict(
        slug="soc-analysis", name="SOC Analysis",
        summary="Watch over a company's systems in real time and catch attacks as they happen.",
        beginner_summary="You'll learn to read alerts from security tools and decide which ones are real threats.",
        difficulty=2, avg_timeline_weeks=20,
        entry_roles=["SOC Analyst (Tier 1)"],
        tools=["SIEM (Splunk)", "Linux basics", "Networking fundamentals"], remote_potential=60,
        earning_notes="One of the more accessible entry points into cybersecurity; often the first rung on the ladder.",
        icon="monitor",
    ),
    dict(
        slug="penetration-testing", name="Penetration Testing",
        summary="Legally break into systems on purpose to find weaknesses before criminals do.",
        beginner_summary="You'll learn how attackers think, then practice finding (and safely reporting) real vulnerabilities.",
        difficulty=4, avg_timeline_weeks=40,
        entry_roles=["Junior Penetration Tester"],
        tools=["Kali Linux", "Burp Suite", "Python", "Metasploit"], remote_potential=65,
        earning_notes="Usually requires 1-2 years of foundational security experience first; pay rises quickly once certified.",
        icon="crosshair",
    ),
    dict(
        slug="devops", name="DevOps",
        summary="Make sure software gets built, tested, and delivered smoothly and reliably.",
        beginner_summary="You'll learn to automate the process of getting code from a developer's laptop safely into production.",
        difficulty=3, avg_timeline_weeks=30,
        entry_roles=["Junior DevOps Engineer"],
        tools=["Docker", "CI/CD (GitHub Actions)", "Linux", "Cloud basics"], remote_potential=80,
        earning_notes="Often a step taken after some software or sysadmin experience, but increasingly a direct entry path.",
        icon="git-branch",
    ),
    dict(
        slug="data-analysis", name="Data Analysis",
        summary="Turn raw numbers into insights that help people make decisions.",
        beginner_summary="You'll learn to explore spreadsheets and datasets to answer real business questions.",
        difficulty=2, avg_timeline_weeks=22,
        entry_roles=["Junior Data Analyst"],
        tools=["SQL", "Excel/Sheets", "Python (pandas)", "Tableau/Looker"], remote_potential=75,
        earning_notes="A common, accessible entry point into the broader data field.",
        icon="bar-chart",
    ),
    dict(
        slug="data-engineering", name="Data Engineering",
        summary="Build the pipelines that move and organize data so others can use it.",
        beginner_summary="You'll learn to build the plumbing that gets data from where it's created to where it's needed, cleanly.",
        difficulty=4, avg_timeline_weeks=32,
        entry_roles=["Junior Data Engineer"],
        tools=["SQL", "Python", "Airflow", "Cloud data warehouses"], remote_potential=80,
        earning_notes="Higher entry-level pay than data analysis due to engineering complexity.",
        icon="database",
    ),
    dict(
        slug="ai-ml-engineering", name="AI/ML Engineering",
        summary="Build systems that learn patterns from data to make predictions.",
        beginner_summary="You'll learn the math and code behind systems that improve from examples instead of fixed rules.",
        difficulty=5, avg_timeline_weeks=44,
        entry_roles=["Junior ML Engineer", "ML Intern"],
        tools=["Python", "NumPy/pandas", "scikit-learn", "PyTorch basics"], remote_potential=75,
        earning_notes="Highly competitive entry-level field; strong math/stats foundation pays off significantly.",
        icon="cpu",
    ),
    dict(
        slug="product-design", name="Product Design",
        summary="Shape how a product looks, feels, and solves a user's problem.",
        beginner_summary="You'll learn to turn a user's problem into a clear, usable design.",
        difficulty=2, avg_timeline_weeks=24,
        entry_roles=["Junior Product Designer"],
        tools=["Figma", "User research basics", "Prototyping"], remote_potential=80,
        earning_notes="A strong portfolio matters more than credentials for entry-level roles.",
        icon="figma",
    ),
    dict(
        slug="ui-ux-design", name="UI/UX Design",
        summary="Design interfaces that are easy and pleasant for people to use.",
        beginner_summary="You'll learn the principles behind screens and flows that feel effortless to use.",
        difficulty=2, avg_timeline_weeks=22,
        entry_roles=["Junior UX Designer", "UI Designer"],
        tools=["Figma", "Usability testing", "Design systems"], remote_potential=80,
        earning_notes="Similar to product design; portfolio-driven hiring.",
        icon="pen-tool",
    ),
    dict(
        slug="product-management", name="Product Management",
        summary="Decide what a product should do next and why.",
        beginner_summary="You'll learn how to turn user problems and business goals into a plan engineers and designers can build.",
        difficulty=3, avg_timeline_weeks=26,
        entry_roles=["Associate Product Manager"],
        tools=["Roadmapping tools", "Analytics basics", "User research"], remote_potential=70,
        earning_notes="Often hired from adjacent roles (support, engineering, design) rather than as a pure first job.",
        icon="target",
    ),
    dict(
        slug="technical-writing", name="Technical Writing",
        summary="Explain complex technical things in a way anyone can understand.",
        beginner_summary="You'll learn to write docs, guides, and explanations that make technical products usable.",
        difficulty=2, avg_timeline_weeks=18,
        entry_roles=["Junior Technical Writer"],
        tools=["Markdown", "Docs-as-code tools", "API documentation"], remote_potential=90,
        earning_notes="One of the most remote-friendly entry points into tech.",
        icon="file-text",
    ),
    dict(
        slug="qa-engineering", name="QA Engineering",
        summary="Test software methodically to catch bugs before users do.",
        beginner_summary="You'll learn to think like a user (and a troublemaker) to find what's broken before it ships.",
        difficulty=2, avg_timeline_weeks=20,
        entry_roles=["Junior QA Engineer", "QA Tester"],
        tools=["Test case design", "Selenium/Playwright basics", "Bug tracking tools"], remote_potential=75,
        earning_notes="A practical, accessible entry point into a software team.",
        icon="check-circle",
    ),
    dict(
        slug="no-code-automation", name="No-Code/Automation",
        summary="Build working software tools without writing much or any code.",
        beginner_summary="You'll learn to connect apps and automate work using visual tools instead of code.",
        difficulty=1, avg_timeline_weeks=12,
        entry_roles=["Automation Specialist", "No-Code Developer"],
        tools=["Zapier/Make", "Airtable", "Webflow/Bubble"], remote_potential=85,
        earning_notes="Fast to learn, often freelance-friendly; strong option for very limited time budgets.",
        icon="zap",
    ),
    dict(
        slug="it-support", name="IT Support",
        summary="Help people solve everyday computer and technology problems.",
        beginner_summary="You'll learn to troubleshoot common tech problems and support people who use computers at work.",
        difficulty=1, avg_timeline_weeks=14,
        entry_roles=["IT Support Technician", "Help Desk Analyst"],
        tools=["Windows/Mac fundamentals", "Networking basics", "Ticketing systems"], remote_potential=45,
        earning_notes="Often the most accessible first tech job with no prior experience, a common launchpad into other paths.",
        icon="headphones",
    ),
    dict(
        slug="solutions-architecture", name="Solutions Architecture",
        summary="Design the overall blueprint for how a company's systems fit together.",
        beginner_summary="You'll eventually learn to see the 'big picture' of how all of a company's tech connects. This comes after hands-on experience elsewhere.",
        difficulty=5, avg_timeline_weeks=52,
        entry_roles=["Associate Solutions Architect (typically after 2+ years elsewhere)"],
        tools=["Cloud platforms", "System design", "Cross-domain fundamentals"], remote_potential=70,
        earning_notes="Not usually a first job, a senior-track destination after backend, cloud, or DevOps experience.",
        icon="git-merge",
    ),
]
