MENTORS = [
    dict(
        display_name="Chidinma Okafor",
        headline="Senior SOC Manager, ex-Tier 1 analyst, now hires and trains junior analysts",
        bio="8 years in security operations across fintech and telecom. I love helping career switchers get their first SOC role, since I was one myself.",
        avatar_seed="chidinma",
        paths=["cybersecurity", "soc-analysis"],
        years_experience=8,
        hourly_rate_cents=4500,
        currency="USD",
        rating_avg=4.9,
        rating_count=61,
    ),
    dict(
        display_name="Marcus Webb",
        headline="Staff Software Engineer, resume and mock interview specialist",
        bio="I've interviewed 200+ junior engineer candidates. I'll tell you honestly what's working and what's not in your resume and portfolio.",
        avatar_seed="marcus",
        paths=["software-engineering", "backend-engineering", "full-stack-development"],
        years_experience=11,
        hourly_rate_cents=6000,
        currency="USD",
        rating_avg=4.8,
        rating_count=94,
    ),
    dict(
        display_name="Priya Nair",
        headline="Cloud Security Engineer, AWS & Azure certified",
        bio="Helping beginners bridge from general IT into cloud security. Happy to review your home-lab projects.",
        avatar_seed="priya",
        paths=["cloud-security", "cloud-engineering"],
        years_experience=6,
        hourly_rate_cents=5000,
        currency="USD",
        rating_avg=4.9,
        rating_count=38,
    ),
    dict(
        display_name="Daniel Kim",
        headline="Senior Data Analyst turned Data Engineer",
        bio="I made the analyst-to-engineer jump myself two years ago and love helping others plan that path.",
        avatar_seed="daniel",
        paths=["data-analysis", "data-engineering"],
        years_experience=7,
        hourly_rate_cents=4000,
        currency="USD",
        rating_avg=4.7,
        rating_count=29,
    ),
    dict(
        display_name="Aisha Bello",
        headline="Product Designer, ex-Figma community lead",
        bio="Portfolio reviews are my specialty. I'll give you the same feedback I give designers I actually hire.",
        avatar_seed="aisha",
        paths=["product-design", "ui-ux-design"],
        years_experience=9,
        hourly_rate_cents=5500,
        currency="USD",
        rating_avg=5.0,
        rating_count=52,
    ),
    dict(
        display_name="Ryan Achterberg",
        headline="Senior Frontend Engineer, React and accessibility specialist",
        bio="I lead frontend at a mid-size fintech and mentor bootcamp grads on the side. Bring me a portfolio project and I'll rip it apart (kindly) and tell you what a hiring manager actually notices.",
        avatar_seed="ryan",
        paths=["frontend-development"],
        years_experience=8,
        hourly_rate_cents=5000,
        currency="USD",
        rating_avg=4.8,
        rating_count=44,
    ),
    dict(
        display_name="Femi Adeyemi",
        headline="Offensive Security Consultant, OSCP",
        bio="I run pentest engagements for mid-market clients and got my start through TryHackMe and home labs, no CS degree. Great for people who feel like they need a 'perfect' background to break in: you don't.",
        avatar_seed="femi",
        paths=["penetration-testing"],
        years_experience=7,
        hourly_rate_cents=6500,
        currency="USD",
        rating_avg=4.9,
        rating_count=33,
    ),
    dict(
        display_name="Elena Vasquez",
        headline="DevOps Lead, Kubernetes and CI/CD at scale",
        bio="I've built deployment pipelines for teams of 5 and teams of 200. I like working with people transitioning from sysadmin or backend roles into DevOps specifically.",
        avatar_seed="elena",
        paths=["devops"],
        years_experience=9,
        hourly_rate_cents=5500,
        currency="USD",
        rating_avg=4.8,
        rating_count=41,
    ),
    dict(
        display_name="Wei Zhang",
        headline="ML Engineer, ex-research, now shipping models in production",
        bio="I spent 3 years in academic ML before moving to industry, so I know exactly which parts of a CS/ML degree matter for a job and which don't. I focus on making your projects portfolio-ready, not just technically correct.",
        avatar_seed="wei",
        paths=["ai-ml-engineering"],
        years_experience=6,
        hourly_rate_cents=7000,
        currency="USD",
        rating_avg=4.9,
        rating_count=27,
    ),
    dict(
        display_name="Sofia Marchetti",
        headline="Senior Product Manager, B2B SaaS",
        bio="I've hired 4 associate PMs from non-traditional backgrounds. Happy to mock-interview, review a PRD, or help you figure out if PM is even the right fit before you commit months to it.",
        avatar_seed="sofia",
        paths=["product-management"],
        years_experience=10,
        hourly_rate_cents=6000,
        currency="USD",
        rating_avg=4.7,
        rating_count=36,
    ),
    dict(
        display_name="Grace Mensah",
        headline="Staff Technical Writer, API documentation focus",
        bio="I write and manage docs for a developer-tools company used by thousands of engineers. Great fit if you're coming from teaching, journalism, or engineering and want a remote-friendly path into tech.",
        avatar_seed="grace",
        paths=["technical-writing"],
        years_experience=8,
        hourly_rate_cents=4500,
        currency="USD",
        rating_avg=5.0,
        rating_count=22,
    ),
    dict(
        display_name="Tomas Novak",
        headline="QA Automation Lead, Playwright and CI pipelines",
        bio="I built the automated regression suite at my company from scratch. I'm most useful for people who already know how to test manually and want to make the jump into automation.",
        avatar_seed="tomas",
        paths=["qa-engineering"],
        years_experience=7,
        hourly_rate_cents=4000,
        currency="USD",
        rating_avg=4.8,
        rating_count=31,
    ),
    dict(
        display_name="Ngozi Eze",
        headline="No-Code Consultant, Zapier, Airtable and Bubble certified partner",
        bio="I run a small agency building automations and internal tools for small businesses, all without traditional code. Perfect if you want a fast, practical path into tech without learning to program first.",
        avatar_seed="ngozi",
        paths=["no-code-automation"],
        years_experience=5,
        hourly_rate_cents=3500,
        currency="USD",
        rating_avg=4.9,
        rating_count=48,
    ),
    dict(
        display_name="Carlos Reyes",
        headline="IT Manager, hires and trains help desk and support techs",
        bio="I started in a mall Genius Bar and now manage IT for a 300-person company. I know exactly what gets an entry-level support candidate hired with zero degree or certs required.",
        avatar_seed="carlos",
        paths=["it-support"],
        years_experience=12,
        hourly_rate_cents=3000,
        currency="USD",
        rating_avg=4.9,
        rating_count=57,
    ),
    dict(
        display_name="Rebecca Lin",
        headline="Principal Solutions Architect, ex-AWS",
        bio="I design enterprise cloud architectures and mentor engineers who are 2-5 years in and aiming for an architect track. Not a beginner-friendly first mentor: best once you already have hands-on cloud/backend experience.",
        avatar_seed="rebecca",
        paths=["solutions-architecture"],
        years_experience=15,
        hourly_rate_cents=9000,
        currency="USD",
        rating_avg=4.9,
        rating_count=19,
    ),
]


# --- Founding mentor -------------------------------------------------------
#
# A single real profile, distinct from the fictional MENTORS list above.
# Deliberately conservative: no years_experience, certifications, employer,
# or income figures are claimed anywhere below because none were provided —
# those fields stay unset (None / defaults) and are meant to be filled in
# from the mentor dashboard (PATCH /mentors/me/profile) rather than
# invented here. contact_email is used only by the self-serve claim flow
# (POST /mentors/claim) to link this row to a real logged-in account.
FOUNDING_MENTOR_EMAIL = "opeyemitoriola41@gmail.com"

FOUNDING_MENTOR = dict(
    display_name="Toriola Opeyemi",
    headline="Cybersecurity & Cloud Security Engineer | Cybersecurity Mentor",
    bio=(
        "I mentor people who are figuring out how to break into tech, especially complete "
        "beginners with little or no technical background. My focus is cybersecurity, cloud "
        "security, and security engineering: what to learn first, how to structure your learning "
        "path, and how to avoid the mistakes that slow beginners down most. If you're stuck on "
        "'where do I even start,' that's exactly what I help with."
    ),
    avatar_seed="toriola",
    avatar_url="/mentors/toriola.jpg",
    paths=["cybersecurity", "cloud-security"],
    years_experience=None,
    hourly_rate_cents=0,
    currency="USD",
    rating_avg=0.0,
    rating_count=0,
    languages=["English"],
    mentorship_formats=["video_call"],
    session_durations_minutes=[30, 60],
    value_proposition=(
        "Toriola mentors beginners entering cybersecurity and can help you understand what to "
        "learn first, how to structure your learning journey, and how to avoid common beginner "
        "mistakes."
    ),
    focus_beginner_friendly=True,
    contact_email=FOUNDING_MENTOR_EMAIL,
    mentee_count=0,
    mentorship_duration_label="2 months",
    mentorship_price_label="₦250,000 ($200)",
    consultation_duration_label="30 minutes",
    consultation_price_label="₦10,000 ($7)",
)
